// Graham's knowledge retrieval: the chunker the generator uses, the BM25 index
// the browser builds, what the reference seed puts into a message and when it
// stays silent, and the wikitext conversion the wiki snapshot goes through.
// The real index is probed too when editor/public/knowledge.json exists (it is
// generated by `npm run blocks`, which `npm test` runs first), because the
// whole point is that a query in the vocabulary of the task lands.
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { bundleModule } from './bundle-module.mjs';
import { wikitextToText } from '../../scripts/wikitext.mjs';
import { aiPanelSource as panel, mainSource as main } from './editor-contract-source.mjs';

const {
  EXCERPT_CHARS, KNOWLEDGE_URL, SEED_BYTES, SEED_LIMIT, SEED_MIN_SCORE,
  buildIndex, excerpt, loadKnowledge, seedReferences, tokenize,
} = await bundleModule('../src/ai/knowledge.ts');

// ---- tokens ------------------------------------------------------------------

assert.deepEqual(tokenize('Rational_Resampler resamplers, the QT GUI Time Sink'),
  ['rational', 'resampler', 'resampler', 'qt', 'gui', 'time', 'sink'],
  'ids split at underscores, plurals fold, stop words drop');
assert.deepEqual(tokenize('symbolSync'), ['symbol', 'sync'], 'camel case splits');

// ---- the index -----------------------------------------------------------------

const chunks = [
  { id: 'block:rational_resampler_xxx', source: 'block', ref: 'rational_resampler_xxx', block: 'rational_resampler_xxx',
    title: 'Rational Resampler (rational_resampler_xxx)',
    text: 'Rational resampling polyphase FIR filter. Interpolation and decimation set the fractional rate change.' },
  { id: 'block:analog_agc_xx', source: 'block', ref: 'analog_agc_xx', block: 'analog_agc_xx',
    title: 'AGC (analog_agc_xx)', text: 'Automatic gain control block with a single rate parameter.' },
  { id: 'docs:audio.md#clock', source: 'docs', ref: 'audio.md#clock', title: 'Audio › The sink is the clock',
    text: 'Audio Sink paces the flowgraph by blocking on ring space, exactly as it does natively.',
    url: 'https://example.test/audio' },
  { id: 'wiki:analog_agc_xx#usage', source: 'wiki', ref: 'analog_agc_xx#usage', block: 'analog_agc_xx',
    title: 'AGC — GNU Radio wiki › Usage', text: 'Automatic gain control: set the rate low for a slow loop. ' + 'x'.repeat(700),
    url: 'https://wiki.gnuradio.org/index.php/AGC' },
  { id: 'example:analog/fm', source: 'example', ref: 'analog/fm', title: 'Example: FM Loopback',
    text: 'Example flowgraph FM loopback. Blocks used: Signal Source, Frequency Mod, AGC, Audio Sink.' },
  // Filler, so term rarity means something: BM25's idf is nearly flat over
  // five documents, and the seed's score floor is set against the real corpus.
  ...Array.from({ length: 60 }, (_, n) => ({
    id: `docs:filler.md#${n}`, source: 'docs', ref: `filler.md#${n}`, title: `Filler ${n}`,
    text: `Section ${n} describes an unrelated matter: cables, connectors, enclosures, mounting hardware, shipping, warranty.`,
  })),
];
const index = buildIndex(chunks);

{
  const hits = index.search('fractional rate resampler');
  assert.equal(hits[0].chunk.ref, 'rational_resampler_xxx', 'the block is found by what it does');
  assert.ok(hits[0].score > (hits[1]?.score || 0));
}
assert.deepEqual(index.search('gain control', { source: 'wiki' }).map(hit => hit.chunk.id),
  ['wiki:analog_agc_xx#usage'], 'a source filter keeps only that source');
assert.deepEqual(index.search('', {}), [], 'no terms, no hits');
assert.deepEqual(index.search('zzzz'), [], 'no matching term, no hits');
assert.equal(index.search('agc rate audio', { limit: 2 }).length, 2, 'limit is honoured');

assert.deepEqual(index.read('audio.md#clock').map(chunk => chunk.id), ['docs:audio.md#clock']);
assert.deepEqual(index.read('analog_agc_xx').map(chunk => chunk.id), ['block:analog_agc_xx', 'wiki:analog_agc_xx#usage'],
  'a block id reads its own docs chunk and its wiki sections together');
assert.deepEqual(index.read('analog_agc_xx#usage').map(chunk => chunk.id), ['wiki:analog_agc_xx#usage']);
assert.deepEqual(index.read('nope'), []);

// ---- excerpts and the seed ------------------------------------------------------

assert.ok(excerpt(chunks[3]).length <= EXCERPT_CHARS + 1 && excerpt(chunks[3]).endsWith('…'),
  'a long chunk is cut to the excerpt length with an ellipsis');
assert.equal(excerpt(chunks[1]), chunks[1].text, 'a short one is itself');

assert.equal(seedReferences(index, 'hello'), '', 'one word seeds nothing');
assert.equal(seedReferences(index, 'run it again'), '', 'a message about nothing in the corpus seeds nothing');
{
  const seed = seedReferences(index, 'add an automatic gain control block with a slow rate');
  assert.match(seed, /^\[reference — matched to this message; search_docs finds more, read_doc reads one in full\]\n/);
  assert.match(seed, /- block analog_agc_xx — AGC \(analog_agc_xx\): Automatic gain control/);
  assert.ok(!seed.includes('Example:'), 'examples never ride in the seed');
  assert.ok(seed.split('\n').length - 1 <= SEED_LIMIT);
  assert.ok(seed.length <= SEED_BYTES + 200, `seed stays bounded (${seed.length})`);
}
assert.ok(SEED_MIN_SCORE > 0);

// ---- loading ---------------------------------------------------------------------

assert.equal(KNOWLEDGE_URL, '/knowledge.json');
{
  let calls = 0;
  const fetchImpl = async () => { calls++; return { ok: true, json: async () => ({ chunks }) }; };
  const a = await loadKnowledge(fetchImpl);
  const b = await loadKnowledge(fetchImpl);
  assert.equal(a, b, 'the index is fetched and built once per page');
  assert.equal(calls, 1);
}

// ---- wikitext --------------------------------------------------------------------

assert.equal(wikitextToText("== Usage ==\n{{Template|x}}\nThis is '''bold''' and a [[Link|shown]] link.\n* one\n# first\n<syntaxhighlight lang=python>x = 1</syntaxhighlight>"),
  '## Usage\nThis is bold and a shown link.\n- one\n1. first\n\n```\nx = 1\n```');
assert.equal(wikitextToText('{| class="wikitable"\n! A !! B\n|-\n| 1 || 2\n|}'), 'A | B\n1 | 2');

// ---- the real index, when it has been generated ----------------------------------

const generated = new URL('../public/knowledge.json', import.meta.url);
if (existsSync(generated)) {
  const file = JSON.parse(await readFile(generated, 'utf8'));
  assert.ok(file.chunks.length > 500, `the generated index holds the corpus (${file.chunks.length} chunks)`);
  assert.ok(file.chunks.every(chunk => chunk.text.length <= 2400), 'every chunk fits the chunk size');
  assert.ok(file.chunks.every(chunk => ['block', 'wiki', 'docs', 'example'].includes(chunk.source)));
  const real = buildIndex(file.chunks);
  const top = (query, source) => real.search(query, { limit: 5, source }).map(hit => hit.chunk.ref);
  assert.ok(top('resampler with a fractional rate', 'block').includes('rational_resampler_xxx'),
    'a task-vocabulary query finds the block: ' + top('resampler with a fractional rate', 'block'));
  assert.ok(top('automatic gain control', 'block')[0].startsWith('analog_agc'), top('automatic gain control', 'block'));
  assert.ok(top('print a byte stream as readable text', 'block').includes('wasm_text_sink'),
    top('print a byte stream as readable text', 'block'));
  assert.ok(top('single threaded scheduler blocks inside work', 'docs').some(ref => ref.startsWith('schedulers.md#')),
    top('single threaded scheduler blocks inside work', 'docs'));
  assert.ok(top('example that decodes RDS', 'example')[0] === 'gr-rds/rds_receiver',
    top('example that decodes RDS', 'example'));
  assert.equal(seedReferences(real, 'run it again'), '', 'the real corpus stays quiet on a message about nothing');
  assert.match(seedReferences(real, 'resample from 48 kHz to 32 kHz with a fractional rate'),
    /rational_resampler_xxx|mmse_resampler_xx/, 'either resampler is the right seed for a fractional rate');
  assert.deepEqual(tokenize('48 khz to 32 khz'), ['khz', 'khz'], 'bare numbers are not terms');
} else {
  console.log('editor/public/knowledge.json not generated; the real-corpus probes were skipped');
}

// ---- wiring --------------------------------------------------------------------------

assert.ok(main.includes('knowledge: () => loadKnowledge()'), 'the editor supplies the index to the tools');
assert.ok(panel.includes('seedReferences(index, text)'), 'the panel seeds references into the message');
assert.match(panel, /\[message\]\\n\$\{text\}/, 'the seed comes before the [message] marker the transcript splits on');

console.log('ai-knowledge.test.mjs: ok');
