import puppeteer from 'puppeteer-core';
import { readdirSync, existsSync } from 'node:fs';
const base = new URL('./chrome-headless-shell/', import.meta.url).pathname;
const exe = readdirSync(base).map(d=>`${base}${d}/chrome-headless-shell-linux64/chrome-headless-shell`).find(existsSync);
const b = await puppeteer.launch({executablePath: exe, headless:true, args:['--no-sandbox','--disable-gpu']});
const p = await b.newPage(); await p.setViewport({width:1200,height:760});
await p.goto('http://localhost:8090/editor/dist/index.html',{waitUntil:'load',timeout:30000});
await new Promise(r=>setTimeout(r,600));
await p.type('.palsearch', 'waterfall');
await new Promise(r=>setTimeout(r,200));
const res = await p.evaluate(()=>{ const vis=el=>el.offsetParent!==null;
  const items=[...document.querySelectorAll('#palette .pal-item')].filter(vis).map(i=>i.textContent);
  const cats=[...document.querySelectorAll('#palette .cat-row')].filter(vis).map(c=>c.textContent.replace(/[▸▾]/,'').trim());
  return {items, cats}; });
console.log('SEARCH "waterfall" -> items:', JSON.stringify(res.items));
console.log('  visible categories:', JSON.stringify(res.cats));
await b.close(); process.exit(0);
