import puppeteer from 'puppeteer-core';
import { readdirSync, existsSync } from 'node:fs';
const base = new URL('./chrome-headless-shell/', import.meta.url).pathname;
const exe = readdirSync(base).map(d=>`${base}${d}/chrome-headless-shell-linux64/chrome-headless-shell`).find(existsSync);
const b = await puppeteer.launch({executablePath: exe, headless:true, args:['--no-sandbox','--disable-gpu','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const p = await b.newPage(); await p.setViewport({width:1200,height:720});
p.on('console',m=>console.log('[c]',m.text().slice(0,140)));
p.on('pageerror',e=>console.log('[E]',e.message.slice(0,140)));
await p.goto('http://localhost:8090/editor/dist/index.html',{waitUntil:'load',timeout:30000});
await new Promise(r=>setTimeout(r,1500));
await p.screenshot({path: process.argv[2]});
const info = await p.evaluate(()=>({nodes:document.querySelectorAll('#nodes .blk').length, wires:document.querySelectorAll('#wires .wire').length, pal:document.querySelectorAll('.pal-item').length}));
console.log('EDITOR', JSON.stringify(info));
await b.close();
