// The Help ▸ Software Versions dialog: every piece of software this build is
// made of, and which version of it.
//
// The numbers are not written here. `virtual:versions` is generated by
// editor/gen/gen_versions.mjs at build time, straight out of the files that pin
// each dependency, so this module only lays them out. Anything that needs a
// version therefore needs a *pin file* change, never an edit here.
//
// It reaches into the editor only through VersionsDeps, the same way the debug
// panel does.
import versions from 'virtual:versions';

export interface VersionsDeps {
  /** main.ts's modal opener: (title, buildBody, wide). */
  openDialog: (title: string, build: (body: HTMLElement) => void, wide?: boolean) => void;
  /** main.ts's clipboard write, which falls back to execCommand off https. */
  copyText: (text: string) => Promise<boolean>;
}

interface VersionRow { name: string; version: string; detail: string; url: string }
interface VersionGroup { name: string; note: string; rows: VersionRow[] }
interface VersionManifest {
  app: { commit: string; commitDate: string; branch: string; dirty: boolean; buildDate: string };
  groups: VersionGroup[];
}

const V = versions as VersionManifest;

function link(text: string, url: string): HTMLElement {
  if (!url) { const s = document.createElement('span'); s.textContent = text; return s; }
  const a = document.createElement('a');
  a.href = url; a.target = '_blank'; a.rel = 'noopener'; a.textContent = text;
  return a;
}

/** The whole manifest as plain text, for pasting into a bug report. */
function asText(): string {
  const { app } = V;
  const lines = [
    `GNU Radio World — commit ${app.commit}${app.dirty ? '+local changes' : ''} ` +
    `(${app.branch}, committed ${app.commitDate}), built ${app.buildDate}`,
  ];
  for (const g of V.groups) {
    lines.push('', `## ${g.name}`);
    for (const r of g.rows) {
      lines.push(`  ${r.name}: ${r.version}${r.detail ? `  (${r.detail})` : ''}`);
    }
  }
  return lines.join('\n') + '\n';
}

export function showVersionsDialog(deps: VersionsDeps): void {
  deps.openDialog('Software Versions', body => {
    body.classList.add('debug-body');
    const { app } = V;

    const head = document.createElement('div');
    head.className = 'debug-section';
    head.appendChild(Object.assign(document.createElement('div'),
      { className: 'debug-h', textContent: 'This build' }));
    const kv = (k: string, v: string) => {
      const row = document.createElement('div'); row.className = 'debug-kv';
      row.append(
        Object.assign(document.createElement('span'), { className: 'debug-k', textContent: k }),
        Object.assign(document.createElement('span'), { className: 'debug-v', textContent: v }));
      head.appendChild(row);
    };
    kv('GNU Radio World', `commit ${app.commit}${app.dirty ? ' + uncommitted changes' : ''} on ${app.branch}`);
    kv('Source committed', app.commitDate);
    kv('Built', app.buildDate);
    body.appendChild(head);

    for (const g of V.groups) {
      if (!g.rows.length) continue;
      const sec = document.createElement('div'); sec.className = 'debug-section';
      sec.appendChild(Object.assign(document.createElement('div'),
        { className: 'debug-h', textContent: g.name }));
      if (g.note) sec.appendChild(Object.assign(document.createElement('div'),
        { className: 'debug-note', textContent: g.note }));
      const tbl = document.createElement('table'); tbl.className = 'debug-table';
      const thead = document.createElement('thead');
      thead.innerHTML = '<tr><th>Component</th><th>Version</th><th>Details</th></tr>';
      const tbody = document.createElement('tbody');
      for (const r of g.rows) {
        const tr = document.createElement('tr');
        const nameCell = document.createElement('td');
        nameCell.appendChild(link(r.name, r.url));
        const verCell = document.createElement('td'); verCell.className = 'mono';
        verCell.textContent = r.version || '—';
        const detCell = document.createElement('td'); detCell.className = 'ver-detail';
        detCell.textContent = r.detail;
        tr.append(nameCell, verCell, detCell);
        tbody.appendChild(tr);
      }
      tbl.append(thead, tbody); sec.appendChild(tbl);
      body.appendChild(sec);
    }

    // Copying beats retyping a dozen commit hashes into an issue.
    const foot = document.createElement('div'); foot.className = 'debug-totals';
    const copy = document.createElement('button');
    copy.className = 'ver-copy'; copy.textContent = 'Copy all versions';
    copy.onclick = () => {
      void deps.copyText(asText()).then(ok => {
        copy.textContent = ok ? 'Copied' : 'Copy failed — see the browser console';
        if (!ok) console.log(asText());
      });
    };
    foot.appendChild(copy);
    body.appendChild(foot);
  }, true);
}
