// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <rds/decoder.h>
#include <rds/encoder.h>
#include <rds/parser.h>
#include <rds/tag_to_msg.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_rds {
    Registrar_rds()
    {
    wasm_registry_add("rds_decoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = rds::decoder::make(wasm_registry::boolean(p, "log", false), wasm_registry::boolean(p, "debug", false));
        return { block, nullptr };
    });
    wasm_registry_add("rds_encoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = rds::encoder::make(wasm_registry::number<int>(p, "pty_locale", 0), wasm_registry::number<int>(p, "pty", 14), wasm_registry::boolean(p, "ms", true), wasm_registry::text(p, "ps", "WDR 3"), wasm_registry::number<double>(p, "af1", 89800000.0), wasm_registry::boolean(p, "tp", true), wasm_registry::boolean(p, "ta", false), wasm_registry::number<int>(p, "pi_country_code", 13), wasm_registry::number<int>(p, "pi_coverage_area", 3), wasm_registry::number<int>(p, "pi_reference_number", 147), wasm_registry::text(p, "radiotext", "GNU Radio <3"), wasm_registry::number<int>(p, "max_latency", -1));
        return { block, nullptr };
    });
    wasm_registry_add("rds_parser", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = rds::parser::make(wasm_registry::boolean(p, "log", false), wasm_registry::boolean(p, "debug", false), wasm_registry::number<int>(p, "pty_locale", 0));
        return { block, nullptr };
    });
    wasm_registry_add("rds_tag_to_msg", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "complex") == "complex") {
            auto block = rds::tag_to_msg::make(sizeof(gr_complex)*wasm_registry::number<int>(p, "vlen", 1));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "float") {
            auto block = rds::tag_to_msg::make(sizeof(float)*wasm_registry::number<int>(p, "vlen", 1));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "int") {
            auto block = rds::tag_to_msg::make(sizeof(int)*wasm_registry::number<int>(p, "vlen", 1));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "short") {
            auto block = rds::tag_to_msg::make(sizeof(short)*wasm_registry::number<int>(p, "vlen", 1));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "byte") {
            auto block = rds::tag_to_msg::make(sizeof(char)*wasm_registry::number<int>(p, "vlen", 1));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for rds_tag_to_msg");
    });
    }
} g_registrar_rds;
} // namespace
