// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <gnuradio/pdu/pdu_to_tagged_stream.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_pdu {
    Registrar_pdu()
    {
    wasm_registry_add("pdu_pdu_to_tagged_stream", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "byte") == "byte") {
            auto block = pdu::pdu_to_tagged_stream::make(gr::types::byte_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "complex") {
            auto block = pdu::pdu_to_tagged_stream::make(gr::types::complex_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "float") {
            auto block = pdu::pdu_to_tagged_stream::make(gr::types::float_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for pdu_pdu_to_tagged_stream");
    });
    }
} g_registrar_pdu;
} // namespace
