// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include "ham_blocks.hpp"

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_ham {
    Registrar_ham()
    {
    wasm_registry_add("ham_chu_decode", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_ham::make_chu_decode();
        return { block, nullptr };
    });
    wasm_registry_add("ham_varicode_rx", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_ham::make_varicode_rx();
        return { block, nullptr };
    });
    wasm_registry_add("ham_varicode_tx", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_ham::make_varicode_tx();
        return { block, nullptr };
    });
    }
} g_registrar_ham;
} // namespace
