// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <digital_hier.hpp>
#include <gnuradio/digital/additive_scrambler.h>
#include <gnuradio/digital/binary_slicer_fb.h>
#include <gnuradio/digital/burst_shaper.h>
#include <gnuradio/digital/chunks_to_symbols.h>
#include <gnuradio/digital/clock_recovery_mm_cc.h>
#include <gnuradio/digital/clock_recovery_mm_ff.h>
#include <gnuradio/digital/corr_est_cc.h>
#include <gnuradio/digital/correlate_access_code_bb_ts.h>
#include <gnuradio/digital/correlate_access_code_ff_ts.h>
#include <gnuradio/digital/correlate_access_code_tag_bb.h>
#include <gnuradio/digital/correlate_access_code_tag_ff.h>
#include <gnuradio/digital/cpmmod_bc.h>
#include <gnuradio/digital/crc16_async_bb.h>
#include <gnuradio/digital/crc32_async_bb.h>
#include <gnuradio/digital/crc32_bb.h>
#include <gnuradio/digital/crc_append.h>
#include <gnuradio/digital/crc_check.h>
#include <gnuradio/digital/descrambler_bb.h>
#include <gnuradio/digital/diff_decoder_bb.h>
#include <gnuradio/digital/diff_encoder_bb.h>
#include <gnuradio/digital/diff_phasor_cc.h>
#include <gnuradio/digital/fll_band_edge_cc.h>
#include <gnuradio/digital/glfsr_source_b.h>
#include <gnuradio/digital/glfsr_source_f.h>
#include <gnuradio/digital/hdlc_deframer_bp.h>
#include <gnuradio/digital/hdlc_framer_pb.h>
#include <gnuradio/digital/header_payload_demux.h>
#include <gnuradio/digital/map_bb.h>
#include <gnuradio/digital/mpsk_snr_est_cc.h>
#include <gnuradio/digital/msk_timing_recovery_cc.h>
#include <gnuradio/digital/ofdm_chanest_vcvc.h>
#include <gnuradio/digital/ofdm_cyclic_prefixer.h>
#include <gnuradio/digital/ofdm_sync_sc_cfb.h>
#include <gnuradio/digital/packet_headergenerator_bb.h>
#include <gnuradio/digital/packet_headerparser_b.h>
#include <gnuradio/digital/pfb_clock_sync_ccf.h>
#include <gnuradio/digital/pfb_clock_sync_fff.h>
#include <gnuradio/digital/pn_correlator_cc.h>
#include <gnuradio/digital/probe_density_b.h>
#include <gnuradio/digital/probe_mpsk_snr_est_c.h>
#include <gnuradio/digital/scrambler_bb.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_digital {
    Registrar_digital()
    {
    wasm_registry_add("digital_additive_scrambler_bb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::additive_scrambler_bb::make(
            wasm_registry::number<std::uint64_t>(p, "mask", 138),
            wasm_registry::number<std::uint64_t>(p, "seed", 127),
            wasm_registry::number<int>(p, "len", 7),
            wasm_registry::number<int>(p, "count", 0),
            wasm_registry::number<int>(p, "bits_per_byte", 1),
            wasm_registry::text(p, "reset_tag_key", ""));
        return { block, nullptr };
    });
    wasm_registry_add("digital_additive_scrambler_xx", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "byte") == "complex") {
            auto block = digital::additive_scrambler_cc::make(
                wasm_registry::number<std::uint64_t>(p, "mask", 138),
                wasm_registry::number<std::uint64_t>(p, "seed", 127),
                wasm_registry::number<int>(p, "len", 7),
                wasm_registry::number<int>(p, "count", 0),
                wasm_registry::number<int>(p, "bits_per_byte", 1),
                wasm_registry::text(p, "reset_tag_key", ""));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "float") {
            auto block = digital::additive_scrambler_ff::make(
                wasm_registry::number<std::uint64_t>(p, "mask", 138),
                wasm_registry::number<std::uint64_t>(p, "seed", 127),
                wasm_registry::number<int>(p, "len", 7),
                wasm_registry::number<int>(p, "count", 0),
                wasm_registry::number<int>(p, "bits_per_byte", 1),
                wasm_registry::text(p, "reset_tag_key", ""));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "int") {
            auto block = digital::additive_scrambler_ii::make(
                wasm_registry::number<std::uint64_t>(p, "mask", 138),
                wasm_registry::number<std::uint64_t>(p, "seed", 127),
                wasm_registry::number<int>(p, "len", 7),
                wasm_registry::number<int>(p, "count", 0),
                wasm_registry::number<int>(p, "bits_per_byte", 1),
                wasm_registry::text(p, "reset_tag_key", ""));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "short") {
            auto block = digital::additive_scrambler_ss::make(
                wasm_registry::number<std::uint64_t>(p, "mask", 138),
                wasm_registry::number<std::uint64_t>(p, "seed", 127),
                wasm_registry::number<int>(p, "len", 7),
                wasm_registry::number<int>(p, "count", 0),
                wasm_registry::number<int>(p, "bits_per_byte", 1),
                wasm_registry::text(p, "reset_tag_key", ""));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "byte") {
            auto block = digital::additive_scrambler_bb::make(
                wasm_registry::number<std::uint64_t>(p, "mask", 138),
                wasm_registry::number<std::uint64_t>(p, "seed", 127),
                wasm_registry::number<int>(p, "len", 7),
                wasm_registry::number<int>(p, "count", 0),
                wasm_registry::number<int>(p, "bits_per_byte", 1),
                wasm_registry::text(p, "reset_tag_key", ""));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for digital_additive_scrambler_xx");
    });
    wasm_registry_add("digital_binary_slicer_fb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::binary_slicer_fb::make();
        return { block, nullptr };
    });
    wasm_registry_add("digital_burst_shaper_xx", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "float") == "float") {
            auto window = wasm_registry::vector<float>(p, "window");
            auto block = digital::burst_shaper_ff::make(
                window,
                wasm_registry::number<int>(p, "pre_padding", 0),
                wasm_registry::number<int>(p, "post_padding", 0),
                wasm_registry::choice(p, "insert_phasing", {{"False", false}, {"True", true}}, false),
                wasm_registry::text(p, "length_tag_name", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "float") == "complex") {
            auto window = wasm_registry::vector<gr_complex>(p, "window");
            auto block = digital::burst_shaper_cc::make(
                window,
                wasm_registry::number<int>(p, "pre_padding", 0),
                wasm_registry::number<int>(p, "post_padding", 0),
                wasm_registry::choice(p, "insert_phasing", {{"False", false}, {"True", true}}, false),
                wasm_registry::text(p, "length_tag_name", "packet_len"));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for digital_burst_shaper_xx");
    });
    wasm_registry_add("digital_chunks_to_symbols_xx", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "in_type", "int") == "int" && wasm_registry::text(p, "out_type", "complex") == "complex") {
            auto symbol_table = wasm_registry::vector<gr_complex>(p, "symbol_table");
            auto block = digital::chunks_to_symbols_ic::make(
                symbol_table,
                wasm_registry::number<int>(p, "dimension", 2));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "in_type", "int") == "int" && wasm_registry::text(p, "out_type", "complex") == "float") {
            auto symbol_table = wasm_registry::vector<float>(p, "symbol_table");
            auto block = digital::chunks_to_symbols_if::make(
                symbol_table,
                wasm_registry::number<int>(p, "dimension", 2));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "in_type", "int") == "short" && wasm_registry::text(p, "out_type", "complex") == "complex") {
            auto symbol_table = wasm_registry::vector<gr_complex>(p, "symbol_table");
            auto block = digital::chunks_to_symbols_sc::make(
                symbol_table,
                wasm_registry::number<int>(p, "dimension", 2));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "in_type", "int") == "short" && wasm_registry::text(p, "out_type", "complex") == "float") {
            auto symbol_table = wasm_registry::vector<float>(p, "symbol_table");
            auto block = digital::chunks_to_symbols_sf::make(
                symbol_table,
                wasm_registry::number<int>(p, "dimension", 2));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "in_type", "int") == "byte" && wasm_registry::text(p, "out_type", "complex") == "complex") {
            auto symbol_table = wasm_registry::vector<gr_complex>(p, "symbol_table");
            auto block = digital::chunks_to_symbols_bc::make(
                symbol_table,
                wasm_registry::number<int>(p, "dimension", 2));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "in_type", "int") == "byte" && wasm_registry::text(p, "out_type", "complex") == "float") {
            auto symbol_table = wasm_registry::vector<float>(p, "symbol_table");
            auto block = digital::chunks_to_symbols_bf::make(
                symbol_table,
                wasm_registry::number<int>(p, "dimension", 2));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for digital_chunks_to_symbols_xx");
    });
    wasm_registry_add("digital_clock_recovery_mm_xx", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "complex") == "complex") {
            auto block = digital::clock_recovery_mm_cc::make(
                wasm_registry::number<double>(p, "omega", 0.0),
                wasm_registry::number<double>(p, "gain_omega", 0.0),
                wasm_registry::number<double>(p, "mu", 0.5),
                wasm_registry::number<double>(p, "gain_mu", 0.175),
                wasm_registry::number<double>(p, "omega_relative_limit", 0.005));
            BuiltBlock built{ block };
            built.numeric_setters["omega"] = [block](double value) { block->set_omega(static_cast<double>(value)); };
            built.numeric_setters["gain_omega"] = [block](double value) { block->set_gain_omega(static_cast<double>(value)); };
            built.numeric_setters["mu"] = [block](double value) { block->set_mu(static_cast<double>(value)); };
            built.numeric_setters["gain_mu"] = [block](double value) { block->set_gain_mu(static_cast<double>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "complex") == "float") {
            auto block = digital::clock_recovery_mm_ff::make(
                wasm_registry::number<double>(p, "omega", 0.0),
                wasm_registry::number<double>(p, "gain_omega", 0.0),
                wasm_registry::number<double>(p, "mu", 0.5),
                wasm_registry::number<double>(p, "gain_mu", 0.175),
                wasm_registry::number<double>(p, "omega_relative_limit", 0.005));
            BuiltBlock built{ block };
            built.numeric_setters["omega"] = [block](double value) { block->set_omega(static_cast<double>(value)); };
            built.numeric_setters["gain_omega"] = [block](double value) { block->set_gain_omega(static_cast<double>(value)); };
            built.numeric_setters["mu"] = [block](double value) { block->set_mu(static_cast<double>(value)); };
            built.numeric_setters["gain_mu"] = [block](double value) { block->set_gain_mu(static_cast<double>(value)); };
            return built;
        }
        throw std::runtime_error("unsupported type selection for digital_clock_recovery_mm_xx");
    });
    wasm_registry_add("digital_corr_est_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto symbols = wasm_registry::vector<gr_complex>(p, "symbols");
        auto block = digital::corr_est_cc::make(
            symbols,
            wasm_registry::number<double>(p, "sps", 0.0),
            wasm_registry::number<int>(p, "mark_delay", 0),
            wasm_registry::number<double>(p, "threshold", 0.9),
            wasm_registry::choice(p, "threshold_method", {{"digital::THRESHOLD_ABSOLUTE", digital::THRESHOLD_ABSOLUTE}, {"digital::THRESHOLD_DYNAMIC", digital::THRESHOLD_DYNAMIC}}, digital::THRESHOLD_ABSOLUTE));
        BuiltBlock built{ block };
        built.numeric_setters["mark_delay"] = [block](double value) { block->set_mark_delay(static_cast<int>(value)); };
        built.numeric_setters["threshold"] = [block](double value) { block->set_threshold(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("digital_correlate_access_code_tag_xx", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "byte") == "byte") {
            auto block = digital::correlate_access_code_tag_bb::make(
                wasm_registry::text(p, "access_code", "101010"),
                wasm_registry::number<int>(p, "threshold", 0),
                wasm_registry::text(p, "tagname", ""));
            BuiltBlock built{ block };
            built.numeric_setters["threshold"] = [block](double value) { block->set_threshold(static_cast<int>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "byte") == "float") {
            auto block = digital::correlate_access_code_tag_ff::make(
                wasm_registry::text(p, "access_code", "101010"),
                wasm_registry::number<int>(p, "threshold", 0),
                wasm_registry::text(p, "tagname", ""));
            BuiltBlock built{ block };
            built.numeric_setters["threshold"] = [block](double value) { block->set_threshold(static_cast<int>(value)); };
            return built;
        }
        throw std::runtime_error("unsupported type selection for digital_correlate_access_code_tag_xx");
    });
    wasm_registry_add("digital_correlate_access_code_xx_ts", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "float") == "float") {
            auto block = digital::correlate_access_code_ff_ts::make(
                wasm_registry::text(p, "access_code", "101010"),
                wasm_registry::number<int>(p, "threshold", 0),
                wasm_registry::text(p, "tagname", ""));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "float") == "byte") {
            auto block = digital::correlate_access_code_bb_ts::make(
                wasm_registry::text(p, "access_code", "101010"),
                wasm_registry::number<int>(p, "threshold", 0),
                wasm_registry::text(p, "tagname", ""));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for digital_correlate_access_code_xx_ts");
    });
    wasm_registry_add("digital_cpmmod_bc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::cpmmod_bc::make(
            wasm_registry::choice(p, "type", {{"analog::cpm::LREC", analog::cpm::LREC}, {"analog::cpm::LRC", analog::cpm::LRC}, {"analog::cpm::LSRC", analog::cpm::LSRC}, {"analog::cpm::TFM", analog::cpm::TFM}, {"analog::cpm::GAUSSIAN", analog::cpm::GAUSSIAN}}, analog::cpm::LREC),
            wasm_registry::number<double>(p, "mod_index", 0.5),
            wasm_registry::number<int>(p, "samples_per_symbol", 4),
            wasm_registry::number<int>(p, "L", 4),
            wasm_registry::number<double>(p, "beta", 0.3));
        return { block, nullptr };
    });
    wasm_registry_add("digital_crc16_async_bb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::crc16_async_bb::make(
            wasm_registry::choice(p, "check", {{"False", false}, {"True", true}}, false));
        return { block, nullptr };
    });
    wasm_registry_add("digital_crc32_async_bb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::crc32_async_bb::make(
            wasm_registry::choice(p, "check", {{"False", false}, {"True", true}}, false));
        return { block, nullptr };
    });
    wasm_registry_add("digital_crc32_bb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::crc32_bb::make(
            wasm_registry::choice(p, "check", {{"False", false}, {"True", true}}, false),
            wasm_registry::text(p, "lengthtagname", "packet_len"),
            wasm_registry::boolean(p, "packed", true));
        return { block, nullptr };
    });
    wasm_registry_add("digital_crc_append", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::crc_append::make(
            wasm_registry::number<int>(p, "num_bits", 32), wasm_registry::number<std::uint64_t>(p, "poly", 79764919), wasm_registry::number<std::uint64_t>(p, "initial_value", 4294967295), wasm_registry::number<std::uint64_t>(p, "final_xor", 4294967295),
            wasm_registry::boolean(p, "input_reflected", true), wasm_registry::boolean(p, "result_reflected", true), wasm_registry::boolean(p, "swap_endianness", false),
            wasm_registry::number<int>(p, "skip_header_bytes", 0));
        return { block, nullptr };
    });
    wasm_registry_add("digital_crc_check", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::crc_check::make(
            wasm_registry::number<int>(p, "num_bits", 32), wasm_registry::number<std::uint64_t>(p, "poly", 79764919), wasm_registry::number<std::uint64_t>(p, "initial_value", 4294967295), wasm_registry::number<std::uint64_t>(p, "final_xor", 4294967295),
            wasm_registry::boolean(p, "input_reflected", true), wasm_registry::boolean(p, "result_reflected", true), wasm_registry::boolean(p, "swap_endianness", false),
            wasm_registry::boolean(p, "discard_crc", false), wasm_registry::number<int>(p, "skip_header_bytes", 0));
        return { block, nullptr };
    });
    wasm_registry_add("digital_descrambler_bb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::descrambler_bb::make(
            wasm_registry::number<std::uint64_t>(p, "mask", 138),
            wasm_registry::number<std::uint64_t>(p, "seed", 127),
            wasm_registry::number<int>(p, "len", 7));
        return { block, nullptr };
    });
    wasm_registry_add("digital_diff_decoder_bb", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "coding", "digital.DIFF_DIFFERENTIAL") == "digital.DIFF_DIFFERENTIAL") {
            auto block = digital::diff_decoder_bb::make(wasm_registry::number<int>(p, "modulus", 0), digital::DIFF_DIFFERENTIAL);
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "coding", "digital.DIFF_DIFFERENTIAL") == "digital.DIFF_NRZI") {
            auto block = digital::diff_decoder_bb::make(2, digital::DIFF_NRZI);
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for digital_diff_decoder_bb");
    });
    wasm_registry_add("digital_diff_encoder_bb", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "coding", "digital.DIFF_DIFFERENTIAL") == "digital.DIFF_DIFFERENTIAL") {
            auto block = digital::diff_encoder_bb::make(wasm_registry::number<int>(p, "modulus", 0), digital::DIFF_DIFFERENTIAL);
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "coding", "digital.DIFF_DIFFERENTIAL") == "digital.DIFF_NRZI") {
            auto block = digital::diff_encoder_bb::make(2, digital::DIFF_NRZI);
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for digital_diff_encoder_bb");
    });
    wasm_registry_add("digital_diff_phasor_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::diff_phasor_cc::make();
        return { block, nullptr };
    });
    wasm_registry_add("digital_fll_band_edge_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::fll_band_edge_cc::make(
            wasm_registry::number<double>(p, "samps_per_sym", 0.0),
            wasm_registry::number<double>(p, "rolloff", 0.0),
            wasm_registry::number<int>(p, "filter_size", 0),
            wasm_registry::number<double>(p, "w", 0.0));
        BuiltBlock built{ block };
        built.numeric_setters["w"] = [block](double value) { block->set_loop_bandwidth(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("digital_gfsk_demod", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = GfskDemod::make(wasm_registry::number<int>(p, "samples_per_symbol", 2), wasm_registry::number<double>(p, "sensitivity", 1.0), wasm_registry::number<double>(p, "gain_mu", 0.175), wasm_registry::number<double>(p, "omega_relative_limit", 0.005), wasm_registry::number<double>(p, "freq_error", 0.0));
        return { block, nullptr };
    });
    wasm_registry_add("digital_gfsk_mod", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = GfskMod::make(wasm_registry::number<int>(p, "samples_per_symbol", 2), wasm_registry::number<double>(p, "sensitivity", 1.0), wasm_registry::number<double>(p, "bt", 0.35), wasm_registry::boolean(p, "do_unpack", true));
        return { block, nullptr };
    });
    wasm_registry_add("digital_glfsr_source_x", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "float") == "float") {
            auto block = digital::glfsr_source_f::make(
                wasm_registry::number<int>(p, "degree", 0),
                wasm_registry::choice(p, "repeat", {{"True", true}, {"False", false}}, true),
                wasm_registry::number<int>(p, "mask", 0),
                wasm_registry::number<int>(p, "seed", 1));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "float") == "byte") {
            auto block = digital::glfsr_source_b::make(
                wasm_registry::number<int>(p, "degree", 0),
                wasm_registry::choice(p, "repeat", {{"True", true}, {"False", false}}, true),
                wasm_registry::number<int>(p, "mask", 0),
                wasm_registry::number<int>(p, "seed", 1));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for digital_glfsr_source_x");
    });
    wasm_registry_add("digital_gmsk_demod", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = GmskDemod::make(wasm_registry::number<int>(p, "samples_per_symbol", 2), wasm_registry::number<double>(p, "gain_mu", 0.175), wasm_registry::number<double>(p, "omega_relative_limit", 0.005), wasm_registry::number<double>(p, "freq_error", 0.0));
        return { block, nullptr };
    });
    wasm_registry_add("digital_gmsk_mod", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = GmskMod::make(wasm_registry::number<int>(p, "samples_per_symbol", 2), wasm_registry::number<double>(p, "bt", 0.35), wasm_registry::boolean(p, "do_unpack", true));
        return { block, nullptr };
    });
    wasm_registry_add("digital_gmskmod_bc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::cpmmod_bc::make_gmskmod_bc(wasm_registry::number<int>(p, "samples_per_symbol", 2), wasm_registry::number<int>(p, "L", 4), wasm_registry::number<double>(p, "bt", 0.3));
        return { block, nullptr };
    });
    wasm_registry_add("digital_hdlc_deframer_bp", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::hdlc_deframer_bp::make(
            wasm_registry::number<int>(p, "min", 32),
            wasm_registry::number<int>(p, "max", 500));
        return { block, nullptr };
    });
    wasm_registry_add("digital_hdlc_framer_pb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::hdlc_framer_pb::make(wasm_registry::text(p, "frame_tag_name", ""));
        return { block, nullptr };
    });
    wasm_registry_add("digital_header_payload_demux", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "complex") == "complex") {
            auto block = digital::header_payload_demux::make(
                wasm_registry::number<int>(p, "header_len", 0),
                wasm_registry::number<int>(p, "items_per_symbol", 0),
                wasm_registry::number<int>(p, "guard_interval", 0),
                wasm_registry::text(p, "length_tag_key", "frame_len"),
                wasm_registry::text(p, "trigger_tag_key", ""),
                wasm_registry::choice(p, "output_symbols", {{"False", false}, {"True", true}}, false),
                sizeof(gr_complex),
                wasm_registry::text(p, "timing_tag_key", "rx_time"),
                wasm_registry::number<double>(p, "samp_rate", 0.0),
                wasm_registry::vector<std::string>(p, "special_tags"),
                wasm_registry::number<int>(p, "header_padding", 0));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "float") {
            auto block = digital::header_payload_demux::make(
                wasm_registry::number<int>(p, "header_len", 0),
                wasm_registry::number<int>(p, "items_per_symbol", 0),
                wasm_registry::number<int>(p, "guard_interval", 0),
                wasm_registry::text(p, "length_tag_key", "frame_len"),
                wasm_registry::text(p, "trigger_tag_key", ""),
                wasm_registry::choice(p, "output_symbols", {{"False", false}, {"True", true}}, false),
                sizeof(float),
                wasm_registry::text(p, "timing_tag_key", "rx_time"),
                wasm_registry::number<double>(p, "samp_rate", 0.0),
                wasm_registry::vector<std::string>(p, "special_tags"),
                wasm_registry::number<int>(p, "header_padding", 0));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "int") {
            auto block = digital::header_payload_demux::make(
                wasm_registry::number<int>(p, "header_len", 0),
                wasm_registry::number<int>(p, "items_per_symbol", 0),
                wasm_registry::number<int>(p, "guard_interval", 0),
                wasm_registry::text(p, "length_tag_key", "frame_len"),
                wasm_registry::text(p, "trigger_tag_key", ""),
                wasm_registry::choice(p, "output_symbols", {{"False", false}, {"True", true}}, false),
                sizeof(int),
                wasm_registry::text(p, "timing_tag_key", "rx_time"),
                wasm_registry::number<double>(p, "samp_rate", 0.0),
                wasm_registry::vector<std::string>(p, "special_tags"),
                wasm_registry::number<int>(p, "header_padding", 0));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "short") {
            auto block = digital::header_payload_demux::make(
                wasm_registry::number<int>(p, "header_len", 0),
                wasm_registry::number<int>(p, "items_per_symbol", 0),
                wasm_registry::number<int>(p, "guard_interval", 0),
                wasm_registry::text(p, "length_tag_key", "frame_len"),
                wasm_registry::text(p, "trigger_tag_key", ""),
                wasm_registry::choice(p, "output_symbols", {{"False", false}, {"True", true}}, false),
                sizeof(short),
                wasm_registry::text(p, "timing_tag_key", "rx_time"),
                wasm_registry::number<double>(p, "samp_rate", 0.0),
                wasm_registry::vector<std::string>(p, "special_tags"),
                wasm_registry::number<int>(p, "header_padding", 0));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "byte") {
            auto block = digital::header_payload_demux::make(
                wasm_registry::number<int>(p, "header_len", 0),
                wasm_registry::number<int>(p, "items_per_symbol", 0),
                wasm_registry::number<int>(p, "guard_interval", 0),
                wasm_registry::text(p, "length_tag_key", "frame_len"),
                wasm_registry::text(p, "trigger_tag_key", ""),
                wasm_registry::choice(p, "output_symbols", {{"False", false}, {"True", true}}, false),
                sizeof(char),
                wasm_registry::text(p, "timing_tag_key", "rx_time"),
                wasm_registry::number<double>(p, "samp_rate", 0.0),
                wasm_registry::vector<std::string>(p, "special_tags"),
                wasm_registry::number<int>(p, "header_padding", 0));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for digital_header_payload_demux");
    });
    wasm_registry_add("digital_map_bb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto map = wasm_registry::vector<int>(p, "map");
        auto block = digital::map_bb::make(map);
        return { block, nullptr };
    });
    wasm_registry_add("digital_mpsk_snr_est_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::mpsk_snr_est_cc::make(
            static_cast<digital::snr_est_type_t>(wasm_registry::choice(p, "type", {{"0", 0}, {"1", 1}, {"2", 2}, {"3", 3}}, 0)),
            wasm_registry::number<int>(p, "tag_nsamples", 10000),
            wasm_registry::number<double>(p, "alpha", 0.001));
        BuiltBlock built{ block };
        built.numeric_setters["tag_nsamples"] = [block](double value) { block->set_tag_nsample(static_cast<int>(value)); };
        built.numeric_setters["alpha"] = [block](double value) { block->set_alpha(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("digital_msk_timing_recovery_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::msk_timing_recovery_cc::make(
            wasm_registry::number<double>(p, "sps", 0.0),
            wasm_registry::number<double>(p, "gain", 0.0),
            wasm_registry::number<double>(p, "limit", 0.0),
            wasm_registry::number<int>(p, "osps", 0));
        BuiltBlock built{ block };
        built.numeric_setters["gain"] = [block](double value) { block->set_gain(static_cast<double>(value)); };
        built.numeric_setters["sps"] = [block](double value) { block->set_sps(static_cast<double>(value)); };
        built.numeric_setters["limit"] = [block](double value) { block->set_limit(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("digital_ofdm_chanest_vcvc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto sync_symbol1 = wasm_registry::vector<gr_complex>(p, "sync_symbol1");
        auto sync_symbol2 = wasm_registry::vector<gr_complex>(p, "sync_symbol2");
        auto block = digital::ofdm_chanest_vcvc::make(
            sync_symbol1,
            sync_symbol2,
            wasm_registry::number<int>(p, "n_data_symbols", 1),
            wasm_registry::number<int>(p, "eq_noise_red_len", 0),
            wasm_registry::number<int>(p, "max_carr_offset", -1),
            wasm_registry::choice(p, "force_one_symbol", {{"False", false}, {"True", true}}, false));
        return { block, nullptr };
    });
    wasm_registry_add("digital_ofdm_cyclic_prefixer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::ofdm_cyclic_prefixer::make(
            wasm_registry::number<int>(p, "input_size", 0),
            wasm_registry::cp_lengths(p, "cp_len", wasm_registry::number<int>(p, "input_size", 0)),
            wasm_registry::number<int>(p, "rolloff", 0),
            wasm_registry::text(p, "tagname", "frame_len"));
        return { block, nullptr };
    });
    wasm_registry_add("digital_ofdm_sync_sc_cfb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::ofdm_sync_sc_cfb::make(
            wasm_registry::number<int>(p, "fft_len", 0),
            wasm_registry::number<int>(p, "cp_len", 0),
            wasm_registry::choice(p, "use_even_carriers", {{"False", false}, {"True", true}}, false),
            wasm_registry::number<double>(p, "threshold", 0.9));
        BuiltBlock built{ block };
        built.numeric_setters["threshold"] = [block](double value) { block->set_threshold(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("digital_packet_headergenerator_bb_default", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::packet_headergenerator_bb::make(
            wasm_registry::number<int>(p, "header_len", 0),
            wasm_registry::text(p, "len_tag_key", "packet_len"));
        return { block, nullptr };
    });
    wasm_registry_add("digital_packet_headerparser_b_default", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::packet_headerparser_b::make(
            wasm_registry::number<int>(p, "header_len", 0),
            wasm_registry::text(p, "len_tag_key", "packet_len"));
        return { block, nullptr };
    });
    wasm_registry_add("digital_pfb_clock_sync_xxx", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "ccf") == "ccf") {
            auto taps = wasm_registry::vector<float>(p, "taps");
            auto block = digital::pfb_clock_sync_ccf::make(
                wasm_registry::number<double>(p, "sps", 0.0),
                wasm_registry::number<double>(p, "loop_bw", 0.0),
                taps,
                wasm_registry::number<int>(p, "filter_size", 32),
                wasm_registry::number<double>(p, "init_phase", 16.0),
                wasm_registry::number<double>(p, "max_dev", 1.5),
                wasm_registry::number<int>(p, "osps", 1));
            BuiltBlock built{ block };
            built.numeric_setters["loop_bw"] = [block](double value) { block->set_loop_bandwidth(static_cast<double>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "ccf") == "fff") {
            auto taps = wasm_registry::vector<float>(p, "taps");
            auto block = digital::pfb_clock_sync_fff::make(
                wasm_registry::number<double>(p, "sps", 0.0),
                wasm_registry::number<double>(p, "loop_bw", 0.0),
                taps,
                wasm_registry::number<int>(p, "filter_size", 32),
                wasm_registry::number<double>(p, "init_phase", 16.0),
                wasm_registry::number<double>(p, "max_dev", 1.5),
                wasm_registry::number<int>(p, "osps", 1));
            BuiltBlock built{ block };
            built.numeric_setters["loop_bw"] = [block](double value) { block->set_loop_bandwidth(static_cast<double>(value)); };
            return built;
        }
        throw std::runtime_error("unsupported type selection for digital_pfb_clock_sync_xxx");
    });
    wasm_registry_add("digital_pn_correlator_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::pn_correlator_cc::make(
            wasm_registry::number<int>(p, "degree", 0),
            wasm_registry::number<int>(p, "mask", 0),
            wasm_registry::number<int>(p, "seed", 1));
        return { block, nullptr };
    });
    wasm_registry_add("digital_probe_density_b", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::probe_density_b::make(wasm_registry::number<double>(p, "alpha", 1.0));
        BuiltBlock built{ block };
        built.numeric_setters["alpha"] = [block](double value) { block->set_alpha(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("digital_probe_mpsk_snr_est_c", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::probe_mpsk_snr_est_c::make(
            static_cast<digital::snr_est_type_t>(wasm_registry::choice(p, "type", {{"0", 0}, {"1", 1}, {"2", 2}, {"3", 3}}, 0)),
            wasm_registry::number<int>(p, "msg_nsamples", 10000),
            wasm_registry::number<double>(p, "alpha", 0.001));
        BuiltBlock built{ block };
        built.numeric_setters["msg_nsamples"] = [block](double value) { block->set_msg_nsample(static_cast<int>(value)); };
        built.numeric_setters["alpha"] = [block](double value) { block->set_alpha(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("digital_scrambler_bb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = digital::scrambler_bb::make(wasm_registry::number<std::uint64_t>(p, "mask", 138), wasm_registry::number<std::uint64_t>(p, "seed", 127), wasm_registry::number<int>(p, "len", 7));
        return { block, nullptr };
    });
    }
} g_registrar_digital;
} // namespace
