// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <foo/burst_tagger.h>
#include <foo/channel_model.h>
#include <foo/packet_dropper.h>
#include <foo/packet_pad2.h>
#include <foo/pad_tagged_stream.h>
#include <foo/periodic_msg_source.h>
#include <foo/random_periodic_msg_source.h>
#include <foo/rtt_measure.h>
#include <foo/wireshark_connector.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_foo {
    Registrar_foo()
    {
    wasm_registry_add("foo_burst_tagger", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = foo::burst_tagger::make(pmt::intern(wasm_registry::text(p, "tag_name", "burst_len")), wasm_registry::number<int>(p, "mult", 1));
        return { block, nullptr };
    });
    wasm_registry_add("foo_channel_model", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = foo::channel_model::make(wasm_registry::number<double>(p, "noise_voltage", 0.0), wasm_registry::number<double>(p, "freq_offset", 0.0), wasm_registry::number<double>(p, "epsilon", 1.0), wasm_registry::vector<gr_complex>(p, "taps"), wasm_registry::number<int>(p, "seed", 0), wasm_registry::choice(p, "block_tags", {{"True", true}, {"False", false}}, false));
        return { block, nullptr };
    });
    wasm_registry_add("foo_packet_dropper", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = foo::packet_dropper::make(wasm_registry::number<double>(p, "drop_rate", 0.5), wasm_registry::number<int>(p, "seed", 42));
        return { block, nullptr };
    });
    wasm_registry_add("foo_packet_pad2", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = foo::packet_pad2::make(wasm_registry::boolean(p, "debug", false), wasm_registry::boolean(p, "delay", false), wasm_registry::number<double>(p, "delay_sec", 0.001), wasm_registry::number<int>(p, "pad_front", 0), wasm_registry::number<int>(p, "pad_tail", 0));
        return { block, nullptr };
    });
    wasm_registry_add("foo_pad_tagged_stream", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = foo::pad_tagged_stream::make(wasm_registry::number<int>(p, "buffer_size", 32768), wasm_registry::text(p, "len_tag_name", ""));
        return { block, nullptr };
    });
    wasm_registry_add("foo_periodic_msg_source", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = foo::periodic_msg_source::make(pmt::intern(wasm_registry::text(p, "msg", "Hello World!")), wasm_registry::number<int>(p, "interval", 1000), wasm_registry::number<int>(p, "num", -1), wasm_registry::boolean(p, "quit", true), wasm_registry::boolean(p, "debug", false));
        return { block, nullptr };
    });
    wasm_registry_add("foo_random_periodic_msg_source", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = foo::random_periodic_msg_source::make(wasm_registry::number<int>(p, "msg_len", 64), wasm_registry::number<int>(p, "interval", 1000), wasm_registry::number<int>(p, "num", 1), wasm_registry::boolean(p, "quit", true), wasm_registry::boolean(p, "debug", false), wasm_registry::number<int>(p, "seed", 1));
        return { block, nullptr };
    });
    wasm_registry_add("foo_rtt_measure", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = foo::rtt_measure::make(wasm_registry::number<int>(p, "interval", 500));
        return { block, nullptr };
    });
    wasm_registry_add("foo_wireshark_connector", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = foo::wireshark_connector::make(static_cast<foo::LinkType>(wasm_registry::choice(p, "tech", {{"127", 127}, {"195", 195}, {"283", 283}}, 127)), wasm_registry::boolean(p, "debug", false));
        return { block, nullptr };
    });
    }
} g_registrar_foo;
} // namespace
