// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <gnuradio/fft/window.h>
#include <gnuradio/inspector/ofdm_synchronizer_cc.h>
#include <gnuradio/inspector/ofdm_zkf_c.h>
#include <gnuradio/inspector/signal_detector_cvf.h>
#include <gnuradio/inspector/signal_extractor_c.h>
#include <gnuradio/inspector/signal_separator_c.h>
#include <map>
#include <vector>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_inspector {
    Registrar_inspector()
    {
    wasm_registry_add("inspector_ofdm_synchronizer_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = inspector::ofdm_synchronizer_cc::make(wasm_registry::number<int>(p, "min_items", 4096));
        return { block, nullptr };
    });
    wasm_registry_add("inspector_ofdm_zkf_c", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = inspector::ofdm_zkf_c::make(wasm_registry::number<double>(p, "samp_rate", 0.0), wasm_registry::number<int>(p, "signal", 0), wasm_registry::number<int>(p, "min_items", 7000), wasm_registry::vector<int>(p, "alpha"), wasm_registry::vector<int>(p, "beta"));
        BuiltBlock built{ block };
        built.numeric_setters["samp_rate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("inspector_signal_detector_cvf", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = inspector::signal_detector_cvf::make(wasm_registry::number<double>(p, "samp_rate", 0.0), wasm_registry::number<int>(p, "fft_len", 1024), wasm_registry::choice(p, "window", {{"window.WIN_BLACKMAN_hARRIS", fft::window::WIN_BLACKMAN_hARRIS}, {"window.WIN_HAMMING", fft::window::WIN_HAMMING}, {"window.WIN_HANN", fft::window::WIN_HANN}, {"window.WIN_BLACKMAN", fft::window::WIN_BLACKMAN}, {"window.WIN_RECTANGULAR", fft::window::WIN_RECTANGULAR}, {"window.WIN_KAISER", fft::window::WIN_KAISER}, {"window.WIN_FLATTOP", fft::window::WIN_FLATTOP}}, fft::window::WIN_BLACKMAN_hARRIS), wasm_registry::number<double>(p, "threshold", 0.7), wasm_registry::number<double>(p, "sensitivity", 0.2), wasm_registry::boolean(p, "auto", true), wasm_registry::number<double>(p, "avg", 0.8), wasm_registry::number<double>(p, "quant", 0.0001), wasm_registry::number<double>(p, "min_bw", 0.0), wasm_registry::text(p, "logfile", "").c_str());
        BuiltBlock built{ block };
        built.numeric_setters["samp_rate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
        built.numeric_setters["sensitivity"] = [block](double value) { block->set_sensitivity(static_cast<double>(value)); };
        built.numeric_setters["auto"] = [block](double value) { block->set_auto_threshold(static_cast<bool>(value)); };
        built.numeric_setters["avg"] = [block](double value) { block->set_average(static_cast<double>(value)); };
        built.numeric_setters["threshold"] = [block](double value) { block->set_threshold(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("inspector_signal_extractor_c", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = inspector::signal_extractor_c::make(wasm_registry::number<int>(p, "signal", 0), wasm_registry::boolean(p, "resample", false), wasm_registry::number<double>(p, "rate", 48000.0), wasm_registry::number<double>(p, "osf", 1.0));
        BuiltBlock built{ block };
        built.numeric_setters["signal"] = [block](double value) { block->set_signal(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("inspector_signal_separator_c", +[](const nlohmann::json& p) -> BuiltBlock {
        std::map<float, std::vector<float>> inspector_taps{{0.0f, {0.0f}}};
        auto block = inspector::signal_separator_c::make(wasm_registry::number<double>(p, "samp_rate", 0.0), wasm_registry::choice(p, "window", {{"window.WIN_BLACKMAN_hARRIS", fft::window::WIN_BLACKMAN_hARRIS}, {"window.WIN_HAMMING", fft::window::WIN_HAMMING}, {"window.WIN_HANN", fft::window::WIN_HANN}, {"window.WIN_BLACKMAN", fft::window::WIN_BLACKMAN}, {"window.WIN_RECTANGULAR", fft::window::WIN_RECTANGULAR}, {"window.WIN_KAISER", fft::window::WIN_KAISER}, {"window.WIN_FLATTOP", fft::window::WIN_FLATTOP}}, fft::window::WIN_BLACKMAN_hARRIS), wasm_registry::number<double>(p, "trans_width", 0.0), wasm_registry::number<double>(p, "oversample", 0.0), false, inspector_taps);
        BuiltBlock built{ block };
        built.numeric_setters["samp_rate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
        built.numeric_setters["trans_width"] = [block](double value) { block->set_trans_width(static_cast<double>(value)); };
        built.numeric_setters["oversample"] = [block](double value) { block->set_oversampling(static_cast<double>(value)); };
        return built;
    });
    }
} g_registrar_inspector;
} // namespace
