// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <gnuradio/droneid/decode.h>
#include <gnuradio/droneid/demodulation.h>
#include <gnuradio/droneid/extractor.h>
#include <gnuradio/droneid/normalized_xcorr_estimate.h>
#include <gnuradio/droneid/time_sync.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_droneid {
    Registrar_droneid()
    {
    wasm_registry_add("droneid_decode", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gr::droneid::decode::make(wasm_registry::text(p, "debug_path", ""));
        return { block, nullptr };
    });
    wasm_registry_add("droneid_demodulation", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gr::droneid::demodulation::make(wasm_registry::number<double>(p, "sample_rate", 30720000.0), wasm_registry::text(p, "debug_path", ""));
        return { block, nullptr };
    });
    wasm_registry_add("droneid_extractor", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gr::droneid::extractor::make(wasm_registry::number<double>(p, "sample_rate", 30720000.0), wasm_registry::number<double>(p, "threshold", 0.5));
        return { block, nullptr };
    });
    wasm_registry_add("droneid_normalized_xcorr_estimate", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gr::droneid::normalized_xcorr_estimate::make(wasm_registry::vector<gr_complex>(p, "taps"));
        return { block, nullptr };
    });
    wasm_registry_add("droneid_time_sync", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gr::droneid::time_sync::make(wasm_registry::number<double>(p, "sample_rate", 30720000.0), wasm_registry::text(p, "debug_path", ""));
        return { block, nullptr };
    });
    }
} g_registrar_droneid;
} // namespace
