// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include "satellites_blocks.hpp"
#include "satellites_deframers.hpp"
#include "satellites_hier.hpp"
#include <satellites/ax100_decode.h>
#include <satellites/convolutional_encoder.h>
#include <satellites/costas_loop_8apsk_cc.h>
#include <satellites/crc_append.h>
#include <satellites/crc_check.h>
#include <satellites/decode_ra_code.h>
#include <satellites/decode_rs.h>
#include <satellites/descrambler308.h>
#include <satellites/distributed_syncframe_soft.h>
#include <satellites/doppler_correction.h>
#include <satellites/encode_rs.h>
#include <satellites/fixedlen_to_pdu.h>
#include <satellites/frame_counter.h>
#include <satellites/kurtosis.h>
#include <satellites/level_to_message.h>
#include <satellites/lilacsat1_demux.h>
#include <satellites/manchester_sync.h>
#include <satellites/matrix_deinterleaver_soft.h>
#include <satellites/message_counter.h>
#include <satellites/nanocom_golay_decode_length.h>
#include <satellites/nrzi_decode.h>
#include <satellites/nrzi_encode.h>
#include <satellites/nusat_decoder.h>
#include <satellites/packet_csma.h>
#include <satellites/pdu_add_meta.h>
#include <satellites/pdu_head_tail.h>
#include <satellites/pdu_length_filter.h>
#include <satellites/pdu_scrambler.h>
#include <satellites/phase_unwrap.h>
#include <satellites/selector.h>
#include <satellites/time_dependent_delay.h>
#include <satellites/u482c_decode.h>
#include <satellites/u482c_encode.h>
#include <satellites/varlen_packet_framer.h>
#include <satellites/varlen_packet_tagger.h>
#include <satellites/viterbi_decoder.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_satellites {
    Registrar_satellites()
    {
    wasm_registry_add("satellites_aalto1_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_aalto1_deframer(wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_aistechsat_2_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_aistechsat_2_deframer(wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ao40_fec_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ao40_fec_deframer(wasm_registry::number<int>(p, "threshold", 0), wasm_registry::boolean(p, "short_frames", false), wasm_registry::boolean(p, "crc", false));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ao40_uncoded_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ao40_uncoded_deframer(wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_astrocast_fx25_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_astrocast_fx25_deframer(wasm_registry::number<int>(p, "threshold", 0), wasm_registry::choice(p, "nrzi", {{"True", true}, {"False", false}}, true));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ax100_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ax100_deframer(wasm_registry::choice(p, "mode", {{"\"RS\"", "RS"}, {"\"ASM\"", "ASM"}}, "RS"), wasm_registry::choice(p, "scrambler", {{"\"CCSDS\"", "CCSDS"}, {"\"none\"", "none"}}, "CCSDS"), wasm_registry::number<int>(p, "threshold", 0), "10010011000010110101000111011110");
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ax25_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ax25_deframer(wasm_registry::boolean(p, "g3ruh_scrambler", true));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_binar1_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_binar1_deframer(0);
        return { block, nullptr };
    });
    wasm_registry_add("satellites_binar2_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_binar2_deframer(0);
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ccsds_concatenated_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ccsds_concatenated_deframer(wasm_registry::number<int>(p, "frame_size", 223), wasm_registry::text(p, "precoding", "None"), true, wasm_registry::choice(p, "rs_basis", {{"\"conventional\"", "conventional"}, {"\"dual\"", "dual"}}, "dual"), wasm_registry::number<int>(p, "rs_interleaving", 1), wasm_registry::choice(p, "scrambler", {{"\"CCSDS\"", "CCSDS"}, {"\"none\"", "none"}}, "CCSDS"), wasm_registry::number<int>(p, "threshold", 0), wasm_registry::choice(p, "convolutional", {{"\"CCSDS\"", "CCSDS"}, {"\"NASA-DSN\"", "NASA-DSN"}, {"\"CCSDS uninverted\"", "CCSDS uninverted"}, {"\"NASA-DSN uninverted\"", "NASA-DSN uninverted"}}, "CCSDS"));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ccsds_rs_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ccsds_rs_deframer(wasm_registry::number<int>(p, "frame_size", 223), wasm_registry::text(p, "precoding", "None"), true, wasm_registry::choice(p, "rs_basis", {{"\"conventional\"", "conventional"}, {"\"dual\"", "dual"}}, "dual"), wasm_registry::number<int>(p, "rs_interleaving", 1), wasm_registry::choice(p, "scrambler", {{"\"CCSDS\"", "CCSDS"}, {"\"none\"", "none"}}, "CCSDS"), wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ccsds_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ccsds_rs_deframer(wasm_registry::number<int>(p, "frame_size", 223), wasm_registry::text(p, "precoding", "None"), false, "dual", 1, wasm_registry::choice(p, "scrambler", {{"\"CCSDS\"", "CCSDS"}, {"\"none\"", "none"}}, "CCSDS"), wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_endurosat_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_endurosat_deframer(wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_fossasat_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_fossasat_deframer(wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_geoscan_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_geoscan_deframer(wasm_registry::number<int>(p, "frame_size", 66), wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_grizu263a_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_grizu263a_deframer(wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_light1_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_reaktor_hello_world_deframer(wasm_registry::number<int>(p, "threshold", 0), "10010011000010110101000111011110");
        return { block, nullptr };
    });
    wasm_registry_add("satellites_lilacsat_1_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_lilacsat_1_deframer(wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_lucky7_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_lucky7_deframer(wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ngham_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ngham_deframer(wasm_registry::boolean(p, "decode_rs", false), wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_nusat_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_nusat_deframer(wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ops_sat_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ops_sat_deframer();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_qubik_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_qubik_deframer(wasm_registry::number<int>(p, "threshold", 4));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_reaktor_hello_world_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_reaktor_hello_world_deframer(wasm_registry::number<int>(p, "threshold", 0), "00110101001011100011010100101110");
        return { block, nullptr };
    });
    wasm_registry_add("satellites_smogp_signalling_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_smogp_signalling_deframer(wasm_registry::choice(p, "protocol", {{"False", false}, {"True", true}}, false), wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_swiatowid_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_swiatowid_deframer(wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_tt64_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_tt64_deframer(wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_u482c_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_u482c_deframer(wasm_registry::number<int>(p, "threshold", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ua01_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ua01_deframer();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_afsk_demodulator", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_afsk_demodulator(wasm_registry::number<double>(p, "baudrate", 0.0), wasm_registry::number<double>(p, "samp_rate", 0.0), wasm_registry::boolean(p, "iq", false), wasm_registry::number<double>(p, "af_carrier", 0.0), wasm_registry::number<double>(p, "deviation", 0.0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_bpsk_demodulator", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_bpsk_demodulator(wasm_registry::number<double>(p, "baudrate", 0.0), wasm_registry::number<double>(p, "samp_rate", 0.0), wasm_registry::number<double>(p, "f_offset", 0.0), wasm_registry::boolean(p, "differential", false), wasm_registry::boolean(p, "manchester", false), wasm_registry::boolean(p, "iq", false));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_fsk_demodulator", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_fsk_demodulator(wasm_registry::number<double>(p, "baudrate", 0.0), wasm_registry::number<double>(p, "samp_rate", 0.0), wasm_registry::boolean(p, "iq", false), wasm_registry::boolean(p, "subaudio", false));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ccsds_descrambler", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ccsds_descrambler();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ccsds_viterbi", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ccsds_viterbi("CCSDS");
        return { block, nullptr };
    });
    wasm_registry_add("satellites_pn9_scrambler", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_pn9_scrambler();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_rms_agc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_rms_agc(wasm_registry::number<double>(p, "alpha", 0.01), wasm_registry::number<double>(p, "reference", 1.0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_si4463_scrambler", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_si4463_scrambler();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_sync_to_pdu", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_sync_to_pdu(wasm_registry::number<int>(p, "packlen", 0), wasm_registry::text(p, "sync", "00011010110011111111110000011101"), wasm_registry::number<int>(p, "threshold", 4));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_sync_to_pdu_packed", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_sync_to_pdu_packed(wasm_registry::number<int>(p, "packlen", 0), wasm_registry::text(p, "sync", "00011010110011111111110000011101"), wasm_registry::number<int>(p, "threshold", 4));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_sync_to_pdu_soft", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_sync_to_pdu_soft(wasm_registry::number<int>(p, "packlen", 0), wasm_registry::text(p, "sync", "00011010110011111111110000011101"), wasm_registry::number<int>(p, "threshold", 4));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_aausat4_check_fsm", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_aausat4_check_fsm();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ax100_decode", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::ax100_decode::make(wasm_registry::boolean(p, "verbose", false));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_beesat_classifier", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_beesat_classifier();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_cc11xx_packet_crop", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_cc11xx_packet_crop(wasm_registry::boolean(p, "use_crc16", false));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_check_address", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_check_address(wasm_registry::text(p, "address", ""), wasm_registry::text(p, "direction", ""), wasm_registry::text(p, "digicallsign", ""));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_check_astrocast_crc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_check_astrocast_crc(wasm_registry::boolean(p, "verbose", false));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_check_hex_string", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_check_hex_string(wasm_registry::text(p, "hexstring", "c0ffee"), wasm_registry::number<int>(p, "startindex", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_convolutional_encoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::convolutional_encoder::make(wasm_registry::number<int>(p, "constraint", 7), wasm_registry::vector<int>(p, "polynomials"));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_costas_loop_8apsk_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::costas_loop_8apsk_cc::make(wasm_registry::number<double>(p, "loop_bw", 0.0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_crc_append", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::crc_append::make(wasm_registry::number<int>(p, "num_bits", 32), wasm_registry::number<std::uint64_t>(p, "poly", 79764919), wasm_registry::number<std::uint64_t>(p, "initial_value", 4294967295), wasm_registry::number<std::uint64_t>(p, "final_xor", 4294967295), wasm_registry::boolean(p, "input_reflected", true), wasm_registry::boolean(p, "result_reflected", true), wasm_registry::boolean(p, "swap_endianness", false), wasm_registry::number<int>(p, "skip_header_bytes", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_crc_check", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::crc_check::make(wasm_registry::number<int>(p, "num_bits", 32), wasm_registry::number<std::uint64_t>(p, "poly", 79764919), wasm_registry::number<std::uint64_t>(p, "initial_value", 4294967295), wasm_registry::number<std::uint64_t>(p, "final_xor", 4294967295), wasm_registry::boolean(p, "input_reflected", true), wasm_registry::boolean(p, "result_reflected", true), wasm_registry::boolean(p, "swap_endianness", false), wasm_registry::boolean(p, "discard_crc", false), wasm_registry::number<int>(p, "skip_header_bytes", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_csp_address_filter", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_csp_address_filter(wasm_registry::vector<int>(p, "allowed_sources"), wasm_registry::vector<int>(p, "allowed_destinations"));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_decode_ra_code", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::decode_ra_code::make(wasm_registry::number<int>(p, "size", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_decode_rs", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::decode_rs::make(wasm_registry::number<int>(p, "nsym", 8), wasm_registry::number<int>(p, "gfpoly", 285), wasm_registry::number<int>(p, "fcr", 1), wasm_registry::number<int>(p, "prim", 1), wasm_registry::number<int>(p, "nroots", 1), wasm_registry::number<int>(p, "interleave", 1));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_decode_rs_ccsds", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::decode_rs::make(wasm_registry::choice(p, "basis", {{"False", false}, {"True", true}}, false), wasm_registry::number<int>(p, "interleave", 1));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_descrambler308", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::descrambler308::make();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_distributed_syncframe_soft", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::distributed_syncframe_soft::make(wasm_registry::number<int>(p, "threshold", 0), wasm_registry::text(p, "syncword", "11111110000111011110010110010010000001000100110001011101011011000"), wasm_registry::number<int>(p, "step", 80));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_doppler_correction", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::doppler_correction::make(wasm_registry::text(p, "file", "").c_str(), wasm_registry::number<double>(p, "samp_rate", 0.0), wasm_registry::number<double>(p, "t0", 0.0), wasm_registry::text(p, "timesync_tag", ""));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_encode_rs", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::encode_rs::make(wasm_registry::number<int>(p, "nsym", 8), wasm_registry::number<int>(p, "gfpoly", 285), wasm_registry::number<int>(p, "fcr", 1), wasm_registry::number<int>(p, "prim", 1), wasm_registry::number<int>(p, "nroots", 1), wasm_registry::number<int>(p, "interleave", 1));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_encode_rs_ccsds", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::encode_rs::make(wasm_registry::choice(p, "basis", {{"False", false}, {"True", true}}, false), wasm_registry::number<int>(p, "interleave", 1));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_encode_rs_ccsds_vector", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::encode_rs::make(wasm_registry::number<int>(p, "frame_size", 223), wasm_registry::choice(p, "basis", {{"False", false}, {"True", true}}, false), wasm_registry::number<int>(p, "interleave", 1));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_encode_rs_vector", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::encode_rs::make(wasm_registry::number<int>(p, "frame_size", 223), wasm_registry::number<int>(p, "nsym", 8), wasm_registry::number<int>(p, "gfpoly", 285), wasm_registry::number<int>(p, "fcr", 1), wasm_registry::number<int>(p, "prim", 1), wasm_registry::number<int>(p, "nroots", 1), wasm_registry::number<int>(p, "interleave", 1));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_eseo_packet_crop", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_eseo_packet_crop(wasm_registry::boolean(p, "drop_rs", false));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_fixedlen_to_pdu", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "complex") == "complex") {
            auto block = satellites::fixedlen_to_pdu::make(types::complex_t, wasm_registry::text(p, "syncword_tag", "syncword"), wasm_registry::number<int>(p, "packet_len", 0), false, wasm_registry::text(p, "packet_len_tag_key", ""));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "float") {
            auto block = satellites::fixedlen_to_pdu::make(types::float_t, wasm_registry::text(p, "syncword_tag", "syncword"), wasm_registry::number<int>(p, "packet_len", 0), false, wasm_registry::text(p, "packet_len_tag_key", ""));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "byte") {
            auto block = satellites::fixedlen_to_pdu::make(types::byte_t, wasm_registry::text(p, "syncword_tag", "syncword"), wasm_registry::number<int>(p, "packet_len", 0), wasm_registry::boolean(p, "pack", false), wasm_registry::text(p, "packet_len_tag_key", ""));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for satellites_fixedlen_to_pdu");
    });
    wasm_registry_add("satellites_frame_counter", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "complex") == "complex") {
            auto block = satellites::frame_counter::make(sizeof(gr_complex)*wasm_registry::number<int>(p, "vlen", 1), wasm_registry::number<int>(p, "frame_size", 0));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "float") {
            auto block = satellites::frame_counter::make(sizeof(float)*wasm_registry::number<int>(p, "vlen", 1), wasm_registry::number<int>(p, "frame_size", 0));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "int") {
            auto block = satellites::frame_counter::make(sizeof(int)*wasm_registry::number<int>(p, "vlen", 1), wasm_registry::number<int>(p, "frame_size", 0));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "short") {
            auto block = satellites::frame_counter::make(sizeof(short)*wasm_registry::number<int>(p, "vlen", 1), wasm_registry::number<int>(p, "frame_size", 0));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "byte") {
            auto block = satellites::frame_counter::make(sizeof(char)*wasm_registry::number<int>(p, "vlen", 1), wasm_registry::number<int>(p, "frame_size", 0));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for satellites_frame_counter");
    });
    wasm_registry_add("satellites_hdlc_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_hdlc_deframer(wasm_registry::boolean(p, "check_fcs", true), wasm_registry::number<int>(p, "max_length", 10000));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_hdlc_framer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_hdlc_framer(wasm_registry::number<int>(p, "preamble_bytes", 50), wasm_registry::number<int>(p, "postamble_bytes", 7));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ks1q_header_remover", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ks1q_header_remover(wasm_registry::boolean(p, "verbose", false));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_kurtosis", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::kurtosis::make(wasm_registry::number<int>(p, "block_size", 0), wasm_registry::number<int>(p, "vlen", 1));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_level_to_message", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::level_to_message::make(wasm_registry::number<double>(p, "threshold", 0.5));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_lilacsat1_demux", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::lilacsat1_demux::make(wasm_registry::text(p, "tag", "syncword"));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_manchester_sync", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "complex") == "complex") {
            auto block = satellites::manchester_sync_cc::make(wasm_registry::number<int>(p, "block_size", 0));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "float") {
            auto block = satellites::manchester_sync_ff::make(wasm_registry::number<int>(p, "block_size", 0));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for satellites_manchester_sync");
    });
    wasm_registry_add("satellites_matrix_deinterleaver_soft", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::matrix_deinterleaver_soft::make(wasm_registry::number<int>(p, "rows", 80), wasm_registry::number<int>(p, "cols", 65), wasm_registry::number<int>(p, "output_size", 5132), wasm_registry::number<int>(p, "output_skip", 65));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_message_counter", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::message_counter::make();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_nanocom_golay_decode_length", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::nanocom_golay_decode_length::make(wasm_registry::text(p, "golay_start_tag_key", "golay"), wasm_registry::text(p, "length_tag_key", "packet_len"));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ngham_packet_crop", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ngham_packet_crop();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_ngham_remove_padding", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_ngham_remove_padding();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_nrzi_decode", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::nrzi_decode::make();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_nrzi_encode", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::nrzi_encode::make();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_nusat_decoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::nusat_decoder::make();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_packet_csma", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "complex") == "complex") {
            auto block = satellites::packet_csma::make(sizeof(gr_complex)*wasm_registry::number<int>(p, "vlen", 1), wasm_registry::choice(p, "back_to_back_priority", {{"True", true}, {"False", false}}, false), wasm_registry::text(p, "len_tag_key", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "float") {
            auto block = satellites::packet_csma::make(sizeof(float)*wasm_registry::number<int>(p, "vlen", 1), wasm_registry::choice(p, "back_to_back_priority", {{"True", true}, {"False", false}}, false), wasm_registry::text(p, "len_tag_key", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "int") {
            auto block = satellites::packet_csma::make(sizeof(int)*wasm_registry::number<int>(p, "vlen", 1), wasm_registry::choice(p, "back_to_back_priority", {{"True", true}, {"False", false}}, false), wasm_registry::text(p, "len_tag_key", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "short") {
            auto block = satellites::packet_csma::make(sizeof(short)*wasm_registry::number<int>(p, "vlen", 1), wasm_registry::choice(p, "back_to_back_priority", {{"True", true}, {"False", false}}, false), wasm_registry::text(p, "len_tag_key", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "byte") {
            auto block = satellites::packet_csma::make(sizeof(char)*wasm_registry::number<int>(p, "vlen", 1), wasm_registry::choice(p, "back_to_back_priority", {{"True", true}, {"False", false}}, false), wasm_registry::text(p, "len_tag_key", "packet_len"));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for satellites_packet_csma");
    });
    wasm_registry_add("satellites_pdu_add_meta", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::pdu_add_meta::make(wasm_registry::pmt_value(p, "meta"));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_pdu_head_tail", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::pdu_head_tail::make(wasm_registry::choice(p, "mode", {{"0", 0}, {"1", 1}, {"2", 2}, {"3", 3}}, 0), wasm_registry::number<int>(p, "num", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_pdu_length_filter", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::pdu_length_filter::make(wasm_registry::number<int>(p, "min", 0), wasm_registry::number<int>(p, "max", -1));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_pdu_scrambler", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::pdu_scrambler::make(wasm_registry::vector<std::uint8_t>(p, "sequence"));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_phase_unwrap", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::phase_unwrap::make();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_print_header", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_print_header();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_print_timestamp", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_print_timestamp(wasm_registry::text(p, "fmt", "%Y-%m-%d %H:%M:%S"), wasm_registry::boolean(p, "count", true));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_reflect_bytes", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_reflect_bytes();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_selector", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "complex") == "complex") {
            auto block = satellites::selector::make(sizeof(gr_complex)*wasm_registry::number<int>(p, "vlen", 1),wasm_registry::number<int>(p, "input_index", 0),wasm_registry::number<int>(p, "output_index", 0));
            block->set_enabled(wasm_registry::boolean(p, "enabled", true));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "float") {
            auto block = satellites::selector::make(sizeof(float)*wasm_registry::number<int>(p, "vlen", 1),wasm_registry::number<int>(p, "input_index", 0),wasm_registry::number<int>(p, "output_index", 0));
            block->set_enabled(wasm_registry::boolean(p, "enabled", true));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "int") {
            auto block = satellites::selector::make(sizeof(int)*wasm_registry::number<int>(p, "vlen", 1),wasm_registry::number<int>(p, "input_index", 0),wasm_registry::number<int>(p, "output_index", 0));
            block->set_enabled(wasm_registry::boolean(p, "enabled", true));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "short") {
            auto block = satellites::selector::make(sizeof(short)*wasm_registry::number<int>(p, "vlen", 1),wasm_registry::number<int>(p, "input_index", 0),wasm_registry::number<int>(p, "output_index", 0));
            block->set_enabled(wasm_registry::boolean(p, "enabled", true));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "complex") == "byte") {
            auto block = satellites::selector::make(sizeof(char)*wasm_registry::number<int>(p, "vlen", 1),wasm_registry::number<int>(p, "input_index", 0),wasm_registry::number<int>(p, "output_index", 0));
            block->set_enabled(wasm_registry::boolean(p, "enabled", true));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for satellites_selector");
    });
    wasm_registry_add("satellites_snet_classifier", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_snet_classifier();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_swap_crc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_swap_crc();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_swap_header", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_swap_header();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_swiatowid_packet_crop", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_swiatowid_packet_crop();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_swiatowid_packet_split", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_swiatowid_packet_split();
        return { block, nullptr };
    });
    wasm_registry_add("satellites_sx12xx_packet_crop", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_satellites::make_sx12xx_packet_crop(wasm_registry::number<int>(p, "crc_len", 2));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_time_dependent_delay", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::time_dependent_delay::make(wasm_registry::text(p, "file", "").c_str(), wasm_registry::number<double>(p, "samp_rate", 0.0), wasm_registry::number<double>(p, "t0", 0.0), wasm_registry::vector<float>(p, "taps"), wasm_registry::number<int>(p, "num_filters", 0));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_u482c_decode", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::u482c_decode::make(wasm_registry::boolean(p, "verbose", false), wasm_registry::number<int>(p, "viterbi", -1), wasm_registry::number<int>(p, "scrambler", -1), wasm_registry::number<int>(p, "rs", -1));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_u482c_encode", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::u482c_encode::make(wasm_registry::boolean(p, "convolutional", false), wasm_registry::boolean(p, "scrambler", true), wasm_registry::boolean(p, "rs", true), wasm_registry::number<int>(p, "preamble_len", 50), wasm_registry::boolean(p, "flags_in_golay", false));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_varlen_packet_framer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::varlen_packet_framer::make(wasm_registry::text(p, "packetlen_tag", "packet_len"), wasm_registry::number<int>(p, "length_field_size", 12), wasm_registry::choice(p, "endianness", {{"gr.GR_MSB_FIRST", gr::GR_MSB_FIRST}, {"gr.GR_LSB_FIRST", gr::GR_LSB_FIRST}}, gr::GR_MSB_FIRST), wasm_registry::boolean(p, "use_golay", true), wasm_registry::vector<std::uint8_t>(p, "sync_word"));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_varlen_packet_tagger", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::varlen_packet_tagger::make(wasm_registry::text(p, "syncword_tag", "syncword"), wasm_registry::text(p, "packetlen_tag", "packet_len"), wasm_registry::number<int>(p, "length_field_size", 12), wasm_registry::number<int>(p, "mtu", 0), wasm_registry::choice(p, "endianness", {{"gr.GR_MSB_FIRST", gr::GR_MSB_FIRST}, {"gr.GR_LSB_FIRST", gr::GR_LSB_FIRST}}, gr::GR_MSB_FIRST), wasm_registry::boolean(p, "use_golay", true));
        return { block, nullptr };
    });
    wasm_registry_add("satellites_viterbi_decoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = satellites::viterbi_decoder::make(wasm_registry::number<int>(p, "constraint", 7), wasm_registry::vector<int>(p, "polynomials"));
        return { block, nullptr };
    });
    }
} g_registrar_satellites;
} // namespace
