// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include "ieee802_15_4_params.hpp"
#include <ieee802_15_4/access_code_prefixer.h>
#include <ieee802_15_4/access_code_removal_b.h>
#include <ieee802_15_4/chips_to_bits_fb.h>
#include <ieee802_15_4/codeword_demapper_ib.h>
#include <ieee802_15_4/codeword_mapper_bi.h>
#include <ieee802_15_4/codeword_soft_demapper_fb.h>
#include <ieee802_15_4/deinterleaver_ff.h>
#include <ieee802_15_4/dqcsk_demapper_cc.h>
#include <ieee802_15_4/dqcsk_mapper_fc.h>
#include <ieee802_15_4/dqpsk_mapper_ff.h>
#include <ieee802_15_4/dqpsk_soft_demapper_cc.h>
#include <ieee802_15_4/frame_buffer_cc.h>
#include <ieee802_15_4/interleaver_ii.h>
#include <ieee802_15_4/mac.h>
#include <ieee802_15_4/multiuser_chirp_detector_cc.h>
#include <ieee802_15_4/packet_sink.h>
#include <ieee802_15_4/phr_prefixer.h>
#include <ieee802_15_4/phr_removal.h>
#include <ieee802_15_4/preamble_sfd_prefixer_ii.h>
#include <ieee802_15_4/preamble_tagger_cc.h>
#include <ieee802_15_4/qpsk_demapper_fi.h>
#include <ieee802_15_4/qpsk_mapper_if.h>
#include <ieee802_15_4/rime_stack.h>
#include <ieee802_15_4/zeropadding_b.h>
#include <ieee802_15_4/zeropadding_removal_b.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_ieee802_15_4 {
    Registrar_ieee802_15_4()
    {
    wasm_registry_add("ieee802_15_4_access_code_prefixer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::access_code_prefixer::make(wasm_registry::number<std::uint64_t>(p, "pad", 0), wasm_registry::number<std::uint64_t>(p, "preamble", 167));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_access_code_removal_b", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::access_code_removal_b::make(wasm_registry::number<int>(p, "payload_len", 0));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_chips_to_bits_fb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::chips_to_bits_fb::make(wasm_registry::matrix<float>(p, "chip_seq"));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_codeword_demapper_ib", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::codeword_demapper_ib::make(wasm_registry::number<int>(p, "bits_per_cw", 0), wasm_registry::matrix<int>(p, "codewords"));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_codeword_mapper_bi", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::codeword_mapper_bi::make(wasm_registry::number<int>(p, "bits_per_cw", 0), wasm_registry::matrix<int>(p, "codewords"));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_codeword_soft_demapper_fb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::codeword_soft_demapper_fb::make(wasm_registry::number<int>(p, "bits_per_cw", 0), wasm_registry::matrix<float>(p, "codewords"));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_deinterleaver_ff", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::deinterleaver_ff::make(wasm_registry::vector<int>(p, "intlv_seq"));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_dqcsk_demapper_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::dqcsk_demapper_cc::make(wasm_registry::vector<gr_complex>(p, "chirp_seq"), wasm_registry::vector<gr_complex>(p, "time_gap_1"), wasm_registry::vector<gr_complex>(p, "time_gap_2"), wasm_registry::number<int>(p, "len_subchirp", 0), wasm_registry::number<int>(p, "num_subchirps", 0));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_dqcsk_mapper_fc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::dqcsk_mapper_fc::make(wasm_registry::vector<gr_complex>(p, "chirp_seq"), wasm_registry::vector<gr_complex>(p, "time_gap_1"), wasm_registry::vector<gr_complex>(p, "time_gap_2"), wasm_registry::number<int>(p, "len_subchirp", 0), wasm_registry::number<int>(p, "num_subchirps", 0), wasm_registry::number<int>(p, "nsym_frame", 0));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_dqpsk_mapper_ff", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::dqpsk_mapper_ff::make(wasm_registry::number<int>(p, "framelen", 0), wasm_registry::boolean(p, "forward", true));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_dqpsk_soft_demapper_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::dqpsk_soft_demapper_cc::make(wasm_registry::number<int>(p, "framelen", 0));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_frame_buffer_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::frame_buffer_cc::make(wasm_registry::number<int>(p, "nsym_frame", 0));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_interleaver_ii", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::interleaver_ii::make(wasm_registry::vector<int>(p, "intlv_seq"), wasm_registry::boolean(p, "forward", true));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_mac", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::mac::make(wasm_registry::boolean(p, "debug", false), wasm_registry::number<std::uint64_t>(p, "fcf", 34881), wasm_registry::number<std::uint64_t>(p, "seq_nr", 0), wasm_registry::number<std::uint64_t>(p, "dst_pan", 6826), wasm_registry::number<std::uint64_t>(p, "dst", 65535), wasm_registry::number<std::uint64_t>(p, "src", 13124));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_multiuser_chirp_detector_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::multiuser_chirp_detector_cc::make(wasm_registry::vector<gr_complex>(p, "chirp_seq"), wasm_registry::number<int>(p, "time_gap_1", 0), wasm_registry::number<int>(p, "time_gap_2", 0), wasm_registry::number<int>(p, "len_subchirp", 0), wasm_registry::number<double>(p, "threshold", 0.0));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_packet_sink", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::packet_sink::make(wasm_registry::number<int>(p, "th", 10));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_phr_prefixer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::phr_prefixer::make(wasm_registry::vector<std::uint8_t>(p, "phr"));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_phr_removal", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::phr_removal::make(wasm_registry::vector<std::uint8_t>(p, "phr"));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_preamble_sfd_prefixer_ii", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::preamble_sfd_prefixer_ii::make(wasm_registry::vector<int>(p, "preamble"), wasm_registry::vector<int>(p, "sfd"), wasm_registry::number<int>(p, "nsym_frame", 0));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_preamble_tagger_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::preamble_tagger_cc::make(wasm_registry::number<int>(p, "len_preamble", 0));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_qpsk_demapper_fi", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::qpsk_demapper_fi::make();
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_qpsk_mapper_if", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::qpsk_mapper_if::make();
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_rime_stack", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::rime_stack::make(wasm_ieee802_15_4::channels(wasm_registry::vector<int>(p, "bc_channels")), wasm_ieee802_15_4::channels(wasm_registry::vector<int>(p, "uc_channels")), wasm_ieee802_15_4::channels(wasm_registry::vector<int>(p, "ruc_channels")), wasm_ieee802_15_4::address(wasm_registry::vector<int>(p, "rime_add")));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_zeropadding_b", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::zeropadding_b::make(wasm_registry::number<int>(p, "nzeros", 0));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_15_4_zeropadding_removal_b", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_15_4::zeropadding_removal_b::make(wasm_registry::number<int>(p, "phr_payload_len", 0), wasm_registry::number<int>(p, "nzeros", 0));
        return { block, nullptr };
    });
    }
} g_registrar_ieee802_15_4;
} // namespace
