// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <gnuradio/tempest/Hsync.h>
#include <gnuradio/tempest/fft_peak_fine_sampling_sync.h>
#include <gnuradio/tempest/fine_sampling_synchronization.h>
#include <gnuradio/tempest/frame_drop.h>
#include <gnuradio/tempest/framing.h>
#include <gnuradio/tempest/infer_screen_resolution.h>
#include <gnuradio/tempest/normalize_flow.h>
#include <gnuradio/tempest/sampling_synchronization.h>
#include <gnuradio/tempest/ssamp_correction.h>
#include <gnuradio/tempest/sync_detector.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_tempest {
    Registrar_tempest()
    {
    wasm_registry_add("tempest_Hsync", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = tempest::Hsync::make(wasm_registry::number<int>(p, "Htotal", 0), wasm_registry::number<int>(p, "delay", 0));
        BuiltBlock built{ block };
        struct LiveCallbackParams {
            int p_Htotal;
            int p_delay;
        };
        auto live = std::make_shared<LiveCallbackParams>();
        live->p_Htotal = wasm_registry::number<int>(p, "Htotal", 0);
        live->p_delay = wasm_registry::number<int>(p, "delay", 0);
        auto apply_callback_0 = [block, live]() { block->set_Htotal_and_delay(live->p_Htotal, live->p_delay); };
        wasm_registry::add_numeric_setter(built, "Htotal", live, &LiveCallbackParams::p_Htotal, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "delay", live, &LiveCallbackParams::p_delay, apply_callback_0);
        return built;
    });
    wasm_registry_add("tempest_fft_peak_fine_sampling_sync", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = tempest::fft_peak_fine_sampling_sync::make(wasm_registry::number<int>(p, "sample_rate", 0), wasm_registry::number<int>(p, "size", 0), wasm_registry::number<int>(p, "refresh_rate", 0), wasm_registry::number<int>(p, "Vvisible", 0), wasm_registry::number<int>(p, "Hvisible", 0), wasm_registry::boolean(p, "automatic_mode", false));
        return { block, nullptr };
    });
    wasm_registry_add("tempest_fine_sampling_synchronization", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = tempest::fine_sampling_synchronization::make(wasm_registry::number<int>(p, "Htotal", 0), wasm_registry::number<int>(p, "Vtotal", 0), wasm_registry::choice(p, "correct_sampling", {{"1", 1}, {"0", 0}}, 1), wasm_registry::number<double>(p, "max_deviation", 0.0), wasm_registry::number<double>(p, "update_proba", 0.0));
        block->set_output_multiple((wasm_registry::number<int>(p, "Htotal", 0) * wasm_registry::number<int>(p, "Vtotal", 0) * 3) / 2);
        BuiltBlock built{ block };
        struct LiveCallbackParams {
            int p_Htotal;
            int p_Vtotal;
        };
        auto live = std::make_shared<LiveCallbackParams>();
        live->p_Htotal = wasm_registry::number<int>(p, "Htotal", 0);
        live->p_Vtotal = wasm_registry::number<int>(p, "Vtotal", 0);
        auto apply_callback_0 = [block, live]() { block->set_Htotal_Vtotal(live->p_Htotal, live->p_Vtotal); };
        wasm_registry::add_numeric_setter(built, "Htotal", live, &LiveCallbackParams::p_Htotal, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "Vtotal", live, &LiveCallbackParams::p_Vtotal, apply_callback_0);
        return built;
    });
    wasm_registry_add("tempest_frame_drop", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = tempest::frame_drop::make(wasm_registry::number<int>(p, "Htotal", 0), wasm_registry::number<int>(p, "Vtotal", 0), wasm_registry::choice(p, "correct_sampling", {{"1", 1}, {"0", 0}}, 1), wasm_registry::number<double>(p, "max_deviation", 0.0), wasm_registry::number<double>(p, "update_proba", 0.0), wasm_registry::number<double>(p, "actual_samp_rate", 0.0));
        return { block, nullptr };
    });
    wasm_registry_add("tempest_framing", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = tempest::framing::make(wasm_registry::number<int>(p, "Htotal", 0), wasm_registry::number<int>(p, "Vtotal", 0), wasm_registry::number<int>(p, "Hdisplay", 0), wasm_registry::number<int>(p, "Vdisplay", 0));
        BuiltBlock built{ block };
        struct LiveCallbackParams {
            int p_Htotal;
            int p_Vtotal;
        };
        auto live = std::make_shared<LiveCallbackParams>();
        live->p_Htotal = wasm_registry::number<int>(p, "Htotal", 0);
        live->p_Vtotal = wasm_registry::number<int>(p, "Vtotal", 0);
        auto apply_callback_0 = [block, live]() { block->set_Htotal_and_Vtotal(live->p_Htotal, live->p_Vtotal); };
        wasm_registry::add_numeric_setter(built, "Htotal", live, &LiveCallbackParams::p_Htotal, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "Vtotal", live, &LiveCallbackParams::p_Vtotal, apply_callback_0);
        return built;
    });
    wasm_registry_add("tempest_infer_screen_resolution", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = tempest::infer_screen_resolution::make(wasm_registry::number<int>(p, "sample_rate", 0), wasm_registry::number<int>(p, "fft_size", 0), wasm_registry::number<double>(p, "refresh_rate", 0.0), wasm_registry::boolean(p, "automatic_mode", true));
        BuiltBlock built{ block };
        built.numeric_setters["refresh_rate"] = [block](double value) { block->set_refresh_rate(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("tempest_normalize_flow", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = tempest::normalize_flow::make(wasm_registry::number<double>(p, "min", 0.0), wasm_registry::number<double>(p, "max", 0.0), wasm_registry::number<int>(p, "window", 0), wasm_registry::number<double>(p, "alpha_avg", 0.0), wasm_registry::number<double>(p, "update_proba", 0.0));
        BuiltBlock built{ block };
        struct LiveCallbackParams {
            double p_min;
            double p_max;
        };
        auto live = std::make_shared<LiveCallbackParams>();
        live->p_min = wasm_registry::number<double>(p, "min", 0.0);
        live->p_max = wasm_registry::number<double>(p, "max", 0.0);
        auto apply_callback_0 = [block, live]() { block->set_min_max(live->p_min, live->p_max); };
        wasm_registry::add_numeric_setter(built, "min", live, &LiveCallbackParams::p_min, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "max", live, &LiveCallbackParams::p_max, apply_callback_0);
        return built;
    });
    wasm_registry_add("tempest_sampling_synchronization", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = tempest::sampling_synchronization::make(wasm_registry::number<int>(p, "Htotal", 0), wasm_registry::number<double>(p, "manual_correction", 0.0));
        BuiltBlock built{ block };
        built.numeric_setters["Htotal"] = [block](double value) { block->set_Htotal(static_cast<int>(value)); };
        built.numeric_setters["manual_correction"] = [block](double value) { block->set_manual_correction(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("tempest_ssamp_correction", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = tempest::ssamp_correction::make(wasm_registry::number<int>(p, "Htotal", 0), wasm_registry::number<int>(p, "Vtotal", 0), wasm_registry::choice(p, "correct_sampling", {{"1", 1}, {"0", 0}}, 1), wasm_registry::number<double>(p, "max_deviation", 10.0));
        BuiltBlock built{ block };
        struct LiveCallbackParams {
            int p_Htotal;
            int p_Vtotal;
        };
        auto live = std::make_shared<LiveCallbackParams>();
        live->p_Htotal = wasm_registry::number<int>(p, "Htotal", 0);
        live->p_Vtotal = wasm_registry::number<int>(p, "Vtotal", 0);
        auto apply_callback_0 = [block, live]() { block->set_Htotal_Vtotal(live->p_Htotal, live->p_Vtotal); };
        wasm_registry::add_numeric_setter(built, "Htotal", live, &LiveCallbackParams::p_Htotal, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "Vtotal", live, &LiveCallbackParams::p_Vtotal, apply_callback_0);
        return built;
    });
    wasm_registry_add("tempest_sync_detector", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = tempest::sync_detector::make(wasm_registry::number<int>(p, "hscreen", 0), wasm_registry::number<int>(p, "vscreen", 0), wasm_registry::number<int>(p, "hblanking", 0), wasm_registry::number<int>(p, "vblanking", 0));
        return { block, nullptr };
    });
    }
} g_registrar_tempest;
} // namespace
