// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include "lora_sdr_hier.hpp"
#include <gnuradio/lora_sdr/RH_RF95_header.h>
#include <gnuradio/lora_sdr/add_crc.h>
#include <gnuradio/lora_sdr/crc_verif.h>
#include <gnuradio/lora_sdr/data_source.h>
#include <gnuradio/lora_sdr/deinterleaver.h>
#include <gnuradio/lora_sdr/dewhitening.h>
#include <gnuradio/lora_sdr/fft_demod.h>
#include <gnuradio/lora_sdr/frame_sync.h>
#include <gnuradio/lora_sdr/gray_demap.h>
#include <gnuradio/lora_sdr/gray_mapping.h>
#include <gnuradio/lora_sdr/hamming_dec.h>
#include <gnuradio/lora_sdr/hamming_enc.h>
#include <gnuradio/lora_sdr/header.h>
#include <gnuradio/lora_sdr/header_decoder.h>
#include <gnuradio/lora_sdr/interleaver.h>
#include <gnuradio/lora_sdr/modulate.h>
#include <gnuradio/lora_sdr/payload_id_inc.h>
#include <gnuradio/lora_sdr/whitening.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_lora_sdr {
    Registrar_lora_sdr()
    {
    wasm_registry_add("lora_sdr_RH_RF95_header", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::RH_RF95_header::make(wasm_registry::number<int>(p, "_to", 0), wasm_registry::number<int>(p, "_from", 0), wasm_registry::number<int>(p, "_id", 0), wasm_registry::number<int>(p, "_flags", 0));
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_add_crc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::add_crc::make(wasm_registry::boolean(p, "has_crc", false));
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_crc_verif", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::crc_verif::make(wasm_registry::choice(p, "print_rx_msg", {{"0", 0}, {"1", 1}, {"2", 2}}, 1), wasm_registry::choice(p, "output_crc_check", {{"False", false}, {"True", true}}, false));
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_data_source", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::data_source::make(wasm_registry::number<int>(p, "pay_len", 0), wasm_registry::number<int>(p, "n_frames", 0));
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_deinterleaver", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::deinterleaver::make(wasm_registry::boolean(p, "soft_decoding", false));
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_dewhitening", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::dewhitening::make();
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_fft_demod", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::fft_demod::make(wasm_registry::boolean(p, "soft_decoding", false), wasm_registry::choice(p, "max_log_approx", {{"False", false}, {"True", true}}, true));
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_frame_sync", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::frame_sync::make(wasm_registry::number<int>(p, "center_freq", 0), wasm_registry::number<int>(p, "bandwidth", 0), wasm_registry::number<int>(p, "sf", 0), wasm_registry::boolean(p, "impl_head", false), wasm_registry::vector<std::uint16_t>(p, "sync_word", {0x12}), wasm_registry::number<int>(p, "os_factor", 4), wasm_registry::number<int>(p, "preamb_len", 8));
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_gray_demap", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::gray_demap::make(wasm_registry::number<int>(p, "sf", 0));
        BuiltBlock built{ block };
        built.numeric_setters["sf"] = [block](double value) { block->set_sf(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("lora_sdr_gray_mapping", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::gray_mapping::make(wasm_registry::boolean(p, "soft_decoding", false));
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_hamming_dec", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::hamming_dec::make(wasm_registry::boolean(p, "soft_decoding", false));
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_hamming_enc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::hamming_enc::make(wasm_registry::number<int>(p, "cr", 1), wasm_registry::number<int>(p, "sf", 7));
        BuiltBlock built{ block };
        built.numeric_setters["cr"] = [block](double value) { block->set_cr(static_cast<int>(value)); };
        built.numeric_setters["sf"] = [block](double value) { block->set_sf(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("lora_sdr_header", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::header::make(wasm_registry::boolean(p, "impl_head", false), wasm_registry::boolean(p, "has_crc", false), wasm_registry::number<int>(p, "cr", 0));
        BuiltBlock built{ block };
        built.numeric_setters["cr"] = [block](double value) { block->set_cr(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("lora_sdr_header_decoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::header_decoder::make(wasm_registry::boolean(p, "impl_head", false), wasm_registry::number<int>(p, "cr", 3), wasm_registry::number<int>(p, "pay_len", 255), wasm_registry::boolean(p, "has_crc", false), wasm_registry::number<int>(p, "ldro", 2), wasm_registry::choice(p, "print_header", {{"True", true}, {"False", false}}, true));
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_interleaver", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::interleaver::make(wasm_registry::number<int>(p, "cr", 0), wasm_registry::number<int>(p, "sf", 0), wasm_registry::number<int>(p, "ldro", 2), wasm_registry::number<int>(p, "bw", 125000));
        BuiltBlock built{ block };
        built.numeric_setters["cr"] = [block](double value) { block->set_cr(static_cast<int>(value)); };
        built.numeric_setters["sf"] = [block](double value) { block->set_sf(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("lora_rx", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_lora_sdr::make_lora_rx(wasm_registry::number<int>(p, "samp_rate", 500000), wasm_registry::number<int>(p, "bw", 125000), wasm_registry::number<int>(p, "sf", 7), wasm_registry::choice(p, "impl_head", {{"True", true}, {"False", false}}, false), wasm_registry::choice(p, "cr", {{"0", 0}, {"1", 1}, {"2", 2}, {"3", 3}, {"4", 4}}, 1), wasm_registry::choice(p, "has_crc", {{"True", true}, {"False", false}}, true), wasm_registry::number<int>(p, "pay_len", 255), wasm_registry::choice(p, "soft_decoding", {{"True", true}, {"False", false}}, true), wasm_registry::choice(p, "ldro", {{"0", 0}, {"1", 1}, {"2", 2}}, 2), wasm_registry::vector<std::uint16_t>(p, "sync_word", {0x12}), wasm_registry::text(p, "print_rx", "[true,true]"));
        return { block, nullptr };
    });
    wasm_registry_add("lora_tx", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_lora_sdr::make_lora_tx(wasm_registry::number<int>(p, "samp_rate", 500000), wasm_registry::number<int>(p, "bw", 125000), wasm_registry::number<int>(p, "sf", 7), wasm_registry::choice(p, "impl_head", {{"True", true}, {"False", false}}, false), wasm_registry::number<int>(p, "cr", 1), wasm_registry::choice(p, "has_crc", {{"True", true}, {"False", false}}, true), wasm_registry::choice(p, "ldro", {{"0", 0}, {"1", 1}, {"2", 2}}, 2), wasm_registry::vector<std::uint16_t>(p, "sync_word", {0x12}), wasm_registry::number<int>(p, "frame_zero_padd", 1280));
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_modulate", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::modulate::make(wasm_registry::number<int>(p, "sf", 0), wasm_registry::number<int>(p, "samp_rate", 0), wasm_registry::number<int>(p, "bw", 0), wasm_registry::vector<std::uint16_t>(p, "sync_words", {0x12}), wasm_registry::number<int>(p, "frame_zero_padd", 0), wasm_registry::number<int>(p, "preamb_len", 8));
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_payload_id_inc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::payload_id_inc::make(wasm_registry::text(p, "separator", ":"));
        return { block, nullptr };
    });
    wasm_registry_add("lora_sdr_whitening", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lora_sdr::whitening::make(wasm_registry::boolean(p, "is_hex", false), wasm_registry::choice(p, "use_length_tag", {{"True", true}, {"False", false}}, false), (wasm_registry::text(p, "separator", ",") + ",")[0], wasm_registry::text(p, "length_tag_name", "packet_len"));
        return { block, nullptr };
    });
    }
} g_registrar_lora_sdr;
} // namespace
