// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

// Hand-written, in the block implementation this side module links.
BuiltBlock make_wasm_usrp_b2xx_source(const nlohmann::json& params);

namespace {
struct Registrar_b2xx {
    Registrar_b2xx()
    {
        wasm_registry_add("wasm_usrp_b2xx_source", &make_wasm_usrp_b2xx_source);
    }
} g_registrar_b2xx;
} // namespace
