// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <channels_hier.hpp>
#include <gnuradio/channels/cfo_model.h>
#include <gnuradio/channels/channel_model.h>
#include <gnuradio/channels/channel_model2.h>
#include <gnuradio/channels/dynamic_channel_model.h>
#include <gnuradio/channels/selective_fading_model2.h>
#include <gnuradio/channels/sro_model.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_channels {
    Registrar_channels()
    {
    wasm_registry_add("channels_amp_bal", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = AmpBal::make(wasm_registry::number<double>(p, "alpha", 0.0));
        BuiltBlock built{ block };
        built.numeric_setters["alpha"] = [block](double value) { block->set_alpha(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_cfo_model", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = channels::cfo_model::make(wasm_registry::number<double>(p, "srate", 0.0), wasm_registry::number<double>(p, "stdev", 0.01), wasm_registry::number<double>(p, "maxdev", 1000.0), wasm_registry::number<int>(p, "seed", 0));
        BuiltBlock built{ block };
        built.numeric_setters["stdev"] = [block](double value) { block->set_std_dev(static_cast<double>(value)); };
        built.numeric_setters["maxdev"] = [block](double value) { block->set_max_dev(static_cast<double>(value)); };
        built.numeric_setters["srate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_channel_model", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = channels::channel_model::make(wasm_registry::number<double>(p, "noise_voltage", 0.0), wasm_registry::number<double>(p, "freq_offset", 0.0), wasm_registry::number<double>(p, "epsilon", 1.0), wasm_registry::vector<gr_complex>(p, "taps"), wasm_registry::number<int>(p, "seed", 0), wasm_registry::choice(p, "block_tags", {{"True", true}, {"False", false}}, false));
        BuiltBlock built{ block };
        built.numeric_setters["noise_voltage"] = [block](double value) { block->set_noise_voltage(static_cast<double>(value)); };
        built.numeric_setters["freq_offset"] = [block](double value) { block->set_frequency_offset(static_cast<double>(value)); };
        built.numeric_setters["epsilon"] = [block](double value) { block->set_timing_offset(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_channel_model2", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = channels::channel_model2::make(wasm_registry::number<double>(p, "noise_voltage", 0.0), wasm_registry::number<double>(p, "epsilon", 1.0), wasm_registry::vector<gr_complex>(p, "taps"), wasm_registry::number<int>(p, "seed", 0), wasm_registry::choice(p, "block_tags", {{"True", true}, {"False", false}}, false));
        BuiltBlock built{ block };
        built.numeric_setters["noise_voltage"] = [block](double value) { block->set_noise_voltage(static_cast<double>(value)); };
        built.numeric_setters["epsilon"] = [block](double value) { block->set_timing_offset(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_conj_fs_iqcorr", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ConjFsIqcorr::make(wasm_registry::number<int>(p, "delay", 0), wasm_registry::vector<gr_complex>(p, "taps"));
        BuiltBlock built{ block };
        built.numeric_setters["delay"] = [block](double value) { block->set_delay(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("channels_distortion_2_gen", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = Distortion2Gen::make(wasm_registry::number<double>(p, "beta", 0.0));
        BuiltBlock built{ block };
        built.numeric_setters["beta"] = [block](double value) { block->set_beta(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_distortion_3_gen", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = Distortion3Gen::make(wasm_registry::number<double>(p, "beta", 0.0));
        BuiltBlock built{ block };
        built.numeric_setters["beta"] = [block](double value) { block->set_beta(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_dynamic_channel_model", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = channels::dynamic_channel_model::make(wasm_registry::number<double>(p, "samp_rate", 0.0), wasm_registry::number<double>(p, "sro_stdev", 0.01), wasm_registry::number<double>(p, "sro_maxdev", 1000.0), wasm_registry::number<double>(p, "cfo_stdev", 0.01), wasm_registry::number<double>(p, "cfo_maxdev", 1000.0), wasm_registry::number<int>(p, "N", 8), wasm_registry::number<double>(p, "fD", 2.0), wasm_registry::choice(p, "LOS", {{"False", false}, {"True", true}}, false), wasm_registry::number<double>(p, "K", 4.0), wasm_registry::vector<float>(p, "delays"), wasm_registry::vector<float>(p, "mags"), wasm_registry::number<int>(p, "ntaps", 8), wasm_registry::number<double>(p, "noise_amp", 1.0), wasm_registry::number<int>(p, "seed", 0));
        BuiltBlock built{ block };
        built.numeric_setters["samp_rate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
        built.numeric_setters["sro_stdev"] = [block](double value) { block->set_sro_dev_std(static_cast<double>(value)); };
        built.numeric_setters["sro_maxdev"] = [block](double value) { block->set_sro_dev_max(static_cast<double>(value)); };
        built.numeric_setters["cfo_stdev"] = [block](double value) { block->set_cfo_dev_std(static_cast<double>(value)); };
        built.numeric_setters["cfo_maxdev"] = [block](double value) { block->set_cfo_dev_max(static_cast<double>(value)); };
        built.numeric_setters["noise_amp"] = [block](double value) { block->set_noise_amp(static_cast<double>(value)); };
        built.numeric_setters["fD"] = [block](double value) { block->set_doppler_freq(static_cast<double>(value)); };
        built.numeric_setters["K"] = [block](double value) { block->set_K(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_impairments", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = Impairments::make(wasm_registry::number<double>(p, "phase_noise_mag", 0.0), wasm_registry::number<double>(p, "magbal", 0.0), wasm_registry::number<double>(p, "phasebal", 0.0), wasm_registry::number<double>(p, "q_ofs", 0.0), wasm_registry::number<double>(p, "i_ofs", 0.0), wasm_registry::number<double>(p, "freq_offset", 0.0), wasm_registry::number<double>(p, "gamma", 0.0), wasm_registry::number<double>(p, "beta", 0.0));
        BuiltBlock built{ block };
        built.numeric_setters["phase_noise_mag"] = [block](double value) { block->set_phase_noise_mag(static_cast<double>(value)); };
        built.numeric_setters["magbal"] = [block](double value) { block->set_magbal(static_cast<double>(value)); };
        built.numeric_setters["phasebal"] = [block](double value) { block->set_phasebal(static_cast<double>(value)); };
        built.numeric_setters["q_ofs"] = [block](double value) { block->set_q_ofs(static_cast<double>(value)); };
        built.numeric_setters["i_ofs"] = [block](double value) { block->set_i_ofs(static_cast<double>(value)); };
        built.numeric_setters["freq_offset"] = [block](double value) { block->set_freq_offset(static_cast<double>(value)); };
        built.numeric_setters["gamma"] = [block](double value) { block->set_gamma(static_cast<double>(value)); };
        built.numeric_setters["beta"] = [block](double value) { block->set_beta(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_iqbal_gen", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = IqbalGen::make(wasm_registry::number<double>(p, "mag", 0.0), wasm_registry::number<double>(p, "phase", 0.0), wasm_registry::choice(p, "mode", {{"0", 0}, {"1", 1}}, 0));
        BuiltBlock built{ block };
        built.numeric_setters["mag"] = [block](double value) { block->set_magnitude(static_cast<double>(value)); };
        built.numeric_setters["phase"] = [block](double value) { block->set_phase(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_phase_bal", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = PhaseBal::make(wasm_registry::number<double>(p, "alpha", 0.0));
        BuiltBlock built{ block };
        built.numeric_setters["alpha"] = [block](double value) { block->set_alpha(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_phase_noise_gen", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = PhaseNoiseGen::make(wasm_registry::number<double>(p, "noise_mag", 0.0), wasm_registry::number<double>(p, "alpha", 0.1));
        BuiltBlock built{ block };
        built.numeric_setters["noise_mag"] = [block](double value) { block->set_noise_mag(static_cast<double>(value)); };
        built.numeric_setters["alpha"] = [block](double value) { block->set_alpha(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_quantizer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = Quantizer::make(wasm_registry::number<int>(p, "bits", 16));
        BuiltBlock built{ block };
        built.numeric_setters["bits"] = [block](double value) { block->set_bits(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("channels_selective_fading_model2", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = channels::selective_fading_model2::make(wasm_registry::number<int>(p, "N", 8), wasm_registry::number<double>(p, "fDTs", 0.0), wasm_registry::choice(p, "LOS", {{"False", false}, {"True", true}}, false), wasm_registry::number<double>(p, "K", 4.0), wasm_registry::number<int>(p, "seed", 0), wasm_registry::vector<float>(p, "delays"), wasm_registry::vector<float>(p, "delay_std"), wasm_registry::vector<float>(p, "delay_maxdev"), wasm_registry::vector<float>(p, "mags"), wasm_registry::number<int>(p, "ntaps", 8));
        BuiltBlock built{ block };
        built.numeric_setters["fDTs"] = [block](double value) { block->set_fDTs(static_cast<double>(value)); };
        built.numeric_setters["K"] = [block](double value) { block->set_K(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_sro_model", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = channels::sro_model::make(wasm_registry::number<double>(p, "srate", 0.0), wasm_registry::number<double>(p, "stdev", 0.01), wasm_registry::number<double>(p, "maxdev", 1000.0), wasm_registry::number<int>(p, "seed", 0));
        BuiltBlock built{ block };
        built.numeric_setters["stdev"] = [block](double value) { block->set_std_dev(static_cast<double>(value)); };
        built.numeric_setters["maxdev"] = [block](double value) { block->set_max_dev(static_cast<double>(value)); };
        built.numeric_setters["srate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
        return built;
    });
    }
} g_registrar_channels;
} // namespace
