// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <correctiq/SwapIQ.h>
#include <correctiq/correctiq.h>
#include <correctiq/correctiq_auto.h>
#include <correctiq/correctiq_man.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_correctiq {
    Registrar_correctiq()
    {
    wasm_registry_add("correctiq_SwapIQ", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "datatype", "complex") == "complex") {
            auto block = correctiq::SwapIQ::make(1, sizeof(gr_complex));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "datatype", "complex") == "short") {
            auto block = correctiq::SwapIQ::make(2, sizeof(short));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "datatype", "complex") == "byte") {
            auto block = correctiq::SwapIQ::make(3, sizeof(char));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for correctiq_SwapIQ");
    });
    wasm_registry_add("correctiq_correctiq", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = correctiq::correctiq::make();
        return { block, nullptr };
    });
    wasm_registry_add("correctiq_correctiq_auto", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = correctiq::correctiq_auto::make(wasm_registry::number<double>(p, "samp_rate", 0.0), wasm_registry::number<double>(p, "freq", 0.0), wasm_registry::number<double>(p, "gain", 0.0), wasm_registry::number<double>(p, "syncWindow", 2.0));
        BuiltBlock built{ block };
        built.numeric_setters["freq"] = [block](double value) { block->set_freq(static_cast<double>(value)); };
        built.numeric_setters["gain"] = [block](double value) { block->set_gain(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("correctiq_correctiq_man", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = correctiq::correctiq_man::make(wasm_registry::number<double>(p, "real", 0.0), wasm_registry::number<double>(p, "imag", 0.0));
        BuiltBlock built{ block };
        built.numeric_setters["real"] = [block](double value) { block->set_real(static_cast<double>(value)); };
        built.numeric_setters["imag"] = [block](double value) { block->set_imag(static_cast<double>(value)); };
        return built;
    });
    }
} g_registrar_correctiq;
} // namespace
