// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include "gsm_hier.hpp"
#include <gnuradio/gsm/decoding/control_channels_decoder.h>
#include <gnuradio/gsm/decoding/tch_f_decoder.h>
#include <gnuradio/gsm/decoding/tch_h_decoder.h>
#include <gnuradio/gsm/decryption/decryption.h>
#include <gnuradio/gsm/demapping/tch_f_chans_demapper.h>
#include <gnuradio/gsm/demapping/tch_h_chans_demapper.h>
#include <gnuradio/gsm/demapping/universal_ctrl_chans_demapper.h>
#include <gnuradio/gsm/misc_utils/bursts_printer.h>
#include <gnuradio/gsm/misc_utils/controlled_fractional_resampler_cc.h>
#include <gnuradio/gsm/misc_utils/controlled_rotator_cc.h>
#include <gnuradio/gsm/misc_utils/extract_assignment_cmd.h>
#include <gnuradio/gsm/misc_utils/extract_immediate_assignment.h>
#include <gnuradio/gsm/misc_utils/extract_system_info.h>
#include <gnuradio/gsm/misc_utils/message_printer.h>
#include <gnuradio/gsm/misc_utils/msg_to_tag.h>
#include <gnuradio/gsm/qa_utils/burst_sink.h>
#include <gnuradio/gsm/qa_utils/burst_source.h>
#include <gnuradio/gsm/qa_utils/message_sink.h>
#include <gnuradio/gsm/qa_utils/message_source.h>
#include <gnuradio/gsm/receiver/cx_channel_hopper.h>
#include <gnuradio/gsm/receiver/receiver.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_gsm {
    Registrar_gsm()
    {
    wasm_registry_add("gsm_control_channels_decoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::control_channels_decoder::make();
        return { block, nullptr };
    });
    wasm_registry_add("gsm_tch_f_decoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::tch_f_decoder::make(wasm_registry::choice(p, "mode", {{"gsm::TCH_FS", gsm::TCH_FS}, {"gsm::TCH_EFR", gsm::TCH_EFR}, {"gsm::TCH_AFS12_2", gsm::TCH_AFS12_2}, {"gsm::TCH_AFS10_2", gsm::TCH_AFS10_2}, {"gsm::TCH_AFS7_95", gsm::TCH_AFS7_95}, {"gsm::TCH_AFS7_4", gsm::TCH_AFS7_4}, {"gsm::TCH_AFS6_7", gsm::TCH_AFS6_7}, {"gsm::TCH_AFS5_9", gsm::TCH_AFS5_9}, {"gsm::TCH_AFS5_15", gsm::TCH_AFS5_15}, {"gsm::TCH_AFS4_75", gsm::TCH_AFS4_75}}, gsm::TCH_FS), wasm_registry::boolean(p, "boundary_check", false));
        return { block, nullptr };
    });
    wasm_registry_add("gsm_tch_h_decoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::tch_h_decoder::make(wasm_registry::number<int>(p, "sub_channel", 0), wasm_registry::text(p, "multi_rate", ""), wasm_registry::boolean(p, "boundary_check", false));
        return { block, nullptr };
    });
    wasm_registry_add("gsm_decryption", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::decryption::make(wasm_registry::vector<std::uint8_t>(p, "k_c"), wasm_registry::number<int>(p, "a5_version", 1));
        return { block, nullptr };
    });
    wasm_registry_add("gsm_bcch_ccch_demapper", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_gsm::bcch_ccch_demapper::make(wasm_registry::number<int>(p, "timeslot_nr", 0));
        BuiltBlock built{ block };
        built.numeric_setters["timeslot_nr"] = [block](double value) { block->set_timeslot_nr(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("gsm_bcch_ccch_sdcch4_demapper", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_gsm::bcch_ccch_sdcch4_demapper::make(wasm_registry::number<int>(p, "timeslot_nr", 0));
        BuiltBlock built{ block };
        built.numeric_setters["timeslot_nr"] = [block](double value) { block->set_timeslot_nr(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("gsm_sdcch8_demapper", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_gsm::sdcch8_demapper::make(wasm_registry::number<int>(p, "timeslot_nr", 1));
        BuiltBlock built{ block };
        built.numeric_setters["timeslot_nr"] = [block](double value) { block->set_timeslot_nr(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("gsm_tch_f_chans_demapper", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::tch_f_chans_demapper::make(wasm_registry::number<int>(p, "timeslot_nr", 2));
        return { block, nullptr };
    });
    wasm_registry_add("gsm_tch_h_chans_demapper", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::tch_h_chans_demapper::make(wasm_registry::number<int>(p, "timeslot_nr", 2), wasm_registry::number<int>(p, "tch_h_channel", 0));
        return { block, nullptr };
    });
    wasm_registry_add("gsm_universal_ctrl_chans_demapper", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::universal_ctrl_chans_demapper::make(wasm_registry::number<int>(p, "timeslot_nr", 0),
            wasm_registry::vector<int>(p, "downlink_starts_fn_mod51"), wasm_registry::vector<int>(p, "downlink_channel_types"), wasm_registry::vector<int>(p, "downlink_subslots"),
            wasm_registry::vector<int>(p, "uplink_starts_fn_mod51"), wasm_registry::vector<int>(p, "uplink_channel_types"), wasm_registry::vector<int>(p, "uplink_subslots"));
        return { block, nullptr };
    });
    wasm_registry_add("gsm_bursts_printer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::bursts_printer::make(pmt::intern(wasm_registry::text(p, "prepend_string", "")), wasm_registry::boolean(p, "prepend_fnr", false),
            wasm_registry::boolean(p, "prepend_frame_count", false), wasm_registry::boolean(p, "print_payload_only", false), wasm_registry::boolean(p, "ignore_dummy_bursts", false));
        return { block, nullptr };
    });
    wasm_registry_add("gsm_clock_offset_corrector_tagged", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_gsm::clock_offset_corrector_tagged::make(wasm_registry::number<double>(p, "fc", 936600000.0), wasm_registry::number<int>(p, "osr", 4), wasm_registry::number<double>(p, "ppm", 0.0), wasm_registry::number<double>(p, "samp_rate_in", 1083333.3333333333));
        BuiltBlock built{ block };
        built.numeric_setters["fc"] = [block](double value) { block->set_fc(static_cast<double>(value)); };
        built.numeric_setters["ppm"] = [block](double value) { block->set_ppm(static_cast<double>(value)); };
        built.numeric_setters["samp_rate_in"] = [block](double value) { block->set_samp_rate_in(static_cast<double>(value)); };
        built.numeric_setters["osr"] = [block](double value) { block->set_osr(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("gsm_controlled_fractional_resampler_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::controlled_fractional_resampler_cc::make(wasm_registry::number<double>(p, "phase_shift", 0.0), wasm_registry::number<double>(p, "resamp_ratio", 1.0));
        BuiltBlock built{ block };
        built.numeric_setters["resamp_ratio"] = [block](double value) { block->set_resamp_ratio(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("gsm_controlled_rotator_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::controlled_rotator_cc::make(wasm_registry::number<double>(p, "phase_inc", 0.0));
        BuiltBlock built{ block };
        built.numeric_setters["phase_inc"] = [block](double value) { block->set_phase_inc(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("gsm_extract_assignment_cmd", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::extract_assignment_cmd::make();
        return { block, nullptr };
    });
    wasm_registry_add("gsm_extract_immediate_assignment", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::extract_immediate_assignment::make(wasm_registry::boolean(p, "print_immediate_assignments", false),
            wasm_registry::boolean(p, "ignore_gprs", false), wasm_registry::boolean(p, "unique_references", false));
        return { block, nullptr };
    });
    wasm_registry_add("gsm_extract_system_info", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::extract_system_info::make();
        return { block, nullptr };
    });
    wasm_registry_add("gsm_message_printer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::message_printer::make(pmt::intern(wasm_registry::text(p, "prepend_string", "")), wasm_registry::boolean(p, "prepend_fnr", false),
            wasm_registry::boolean(p, "prepend_frame_count", false), wasm_registry::boolean(p, "print_gsmtap_header", false));
        return { block, nullptr };
    });
    wasm_registry_add("gsm_msg_to_tag", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::msg_to_tag::make();
        return { block, nullptr };
    });
    wasm_registry_add("gsm_burst_sink", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::burst_sink::make();
        return { block, nullptr };
    });
    wasm_registry_add("gsm_burst_source", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::burst_source::make(wasm_registry::vector<int>(p, "framenumbers"), wasm_registry::vector<int>(p, "timeslots"), wasm_registry::string_vector(p, "bursts"));
        return { block, nullptr };
    });
    wasm_registry_add("gsm_message_sink", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::message_sink::make();
        return { block, nullptr };
    });
    wasm_registry_add("gsm_message_source", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::message_source::make(wasm_registry::string_vector(p, "messages"));
        return { block, nullptr };
    });
    wasm_registry_add("gsm_cx_channel_hopper", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::cx_channel_hopper::make(wasm_registry::vector<int>(p, "ma"), wasm_registry::number<int>(p, "maio", 0), wasm_registry::number<int>(p, "hsn", 0));
        return { block, nullptr };
    });
    wasm_registry_add("gsm_receiver", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::receiver::make(wasm_registry::number<int>(p, "osr", 4), wasm_registry::vector<int>(p, "cell_allocation"), wasm_registry::vector<int>(p, "tseq_nums"), false);
        return { block, nullptr };
    });
    wasm_registry_add("gsm_receiver_with_uplink", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gsm::receiver::make(wasm_registry::number<int>(p, "osr", 4), wasm_registry::vector<int>(p, "cell_allocation"), wasm_registry::vector<int>(p, "tseq_nums"), true);
        return { block, nullptr };
    });
    }
} g_registrar_gsm;
} // namespace
