// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include "ieee802_11_params.hpp"
#include <ieee802_11/append_crc32.h>
#include <ieee802_11/chunks_to_symbols.h>
#include <ieee802_11/decode_mac.h>
#include <ieee802_11/ether_encap.h>
#include <ieee802_11/extract_csi.h>
#include <ieee802_11/frame_equalizer.h>
#include <ieee802_11/mac.h>
#include <ieee802_11/mapper.h>
#include <ieee802_11/parse_mac.h>
#include <ieee802_11/sync_long.h>
#include <ieee802_11/sync_short.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_ieee802_11 {
    Registrar_ieee802_11()
    {
    wasm_registry_add("ieee802_11_append_crc32", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_11::append_crc32::make(wasm_registry::boolean(p, "append", true));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_11_chunks_to_symbols_xx", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_11::chunks_to_symbols::make();
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_11_decode_mac", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_11::decode_mac::make(wasm_registry::boolean(p, "log", false), wasm_registry::boolean(p, "debug", false));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_11_ether_encap", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_11::ether_encap::make(wasm_registry::boolean(p, "debug", false));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_11_extract_csi", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_11::extract_csi::make();
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_11_frame_equalizer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_11::frame_equalizer::make(wasm_ieee802_11::equalizer(wasm_registry::text(p, "algo", "ieee802_11.LS")), wasm_registry::number<double>(p, "freq", 5890000000.0), wasm_registry::number<double>(p, "bw", 10000000.0), wasm_registry::boolean(p, "log", false), wasm_registry::boolean(p, "debug", false));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_11_mac", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_11::mac::make(wasm_ieee802_11::mac_address(wasm_registry::vector<int>(p, "src_mac")), wasm_ieee802_11::mac_address(wasm_registry::vector<int>(p, "dst_mac")), wasm_ieee802_11::mac_address(wasm_registry::vector<int>(p, "bss_mac")));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_11_mapper", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_11::mapper::make(wasm_ieee802_11::encoding(wasm_registry::text(p, "encoding", "ieee802_11.BPSK_1_2")), wasm_registry::boolean(p, "debug", false));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_11_parse_mac", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_11::parse_mac::make(wasm_registry::boolean(p, "log", false), wasm_registry::boolean(p, "debug", false));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_11_sync_long", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_11::sync_long::make(wasm_registry::number<int>(p, "sync_length", 240), wasm_registry::boolean(p, "log", false), wasm_registry::boolean(p, "debug", false));
        return { block, nullptr };
    });
    wasm_registry_add("ieee802_11_sync_short", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ieee802_11::sync_short::make(wasm_registry::number<double>(p, "threshold", 0.8), wasm_registry::number<int>(p, "min_plateau", 2), wasm_registry::boolean(p, "log", false), wasm_registry::boolean(p, "debug", false));
        return { block, nullptr };
    });
    }
} g_registrar_ieee802_11;
} // namespace
