// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <iridium/burst_downmix.h>
#include <iridium/fft_burst_tagger.h>
#include <iridium/fft_channelizer.h>
#include <iridium/frame_sorter.h>
#include <iridium/iridium_frame_printer.h>
#include <iridium/iridium_qpsk_demod.h>
#include <iridium/iuchar_to_complex.h>
#include <iridium/pdu_null_sink.h>
#include <iridium/pdu_round_robin.h>
#include <iridium/tagged_burst_to_pdu.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_iridium {
    Registrar_iridium()
    {
    wasm_registry_add("iridium_burst_downmix", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = iridium::burst_downmix::make(wasm_registry::number<int>(p, "output_sample_rate", 0), wasm_registry::number<int>(p, "search_depth", 0), wasm_registry::number<int>(p, "hard_max_queue_len", 0), wasm_registry::vector<float>(p, "input_taps"), wasm_registry::vector<float>(p, "start_finder_taps"), wasm_registry::boolean(p, "handle_multiple_frames_per_burst", false));
        return { block, nullptr };
    });
    wasm_registry_add("iridium_fft_burst_tagger", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = iridium::fft_burst_tagger::make(wasm_registry::number<double>(p, "center_frequency", 1626000000.0), wasm_registry::number<int>(p, "fft_size", 1024), wasm_registry::number<int>(p, "sample_rate", 0), wasm_registry::number<int>(p, "burst_pre_len", 1000), wasm_registry::number<int>(p, "burst_post_len", 1000), wasm_registry::number<int>(p, "burst_width", 100), wasm_registry::number<int>(p, "max_bursts", 0), wasm_registry::number<int>(p, "max_burst_len", 0), wasm_registry::number<double>(p, "threshold", 7.0), wasm_registry::number<int>(p, "history_size", 512), false, wasm_registry::boolean(p, "debug", false));
        return { block, nullptr };
    });
    wasm_registry_add("iridium_fft_channelizer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = iridium::fft_channelizer::make(wasm_registry::number<int>(p, "fft_size", 1024), wasm_registry::number<int>(p, "decimation", 8), wasm_registry::boolean(p, "activate_streams", false), wasm_registry::number<int>(p, "pdu_ports", 1), wasm_registry::number<int>(p, "max_burst_size", 100000), wasm_registry::number<int>(p, "max_outstanding", 500), wasm_registry::boolean(p, "drop_overflow", false));
        return { block, nullptr };
    });
    wasm_registry_add("iridium_frame_sorter", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = iridium::frame_sorter::make();
        return { block, nullptr };
    });
    wasm_registry_add("iridium_iridium_frame_printer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = iridium::iridium_frame_printer::make("");
        return { block, nullptr };
    });
    wasm_registry_add("iridium_iridium_qpsk_demod", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = iridium::iridium_qpsk_demod::make(wasm_registry::number<int>(p, "channels", 1));
        return { block, nullptr };
    });
    wasm_registry_add("iridium_iuchar_to_complex", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = iridium::iuchar_to_complex::make();
        return { block, nullptr };
    });
    wasm_registry_add("iridium_pdu_null_sink", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = iridium::pdu_null_sink::make();
        return { block, nullptr };
    });
    wasm_registry_add("iridium_pdu_round_robin", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = iridium::pdu_round_robin::make(wasm_registry::number<int>(p, "output_count", 2));
        return { block, nullptr };
    });
    wasm_registry_add("iridium_tagged_burst_to_pdu", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = iridium::tagged_burst_to_pdu::make(wasm_registry::number<int>(p, "max_burst_size", 100000), wasm_registry::number<double>(p, "relative_center_frequency", 0.0), wasm_registry::number<double>(p, "relative_span", 1.0), wasm_registry::number<double>(p, "relative_sample_rate", 1.0), wasm_registry::number<double>(p, "sample_offset", 0.0), wasm_registry::number<int>(p, "max_outstanding", 500), wasm_registry::boolean(p, "drop_overflow", false));
        return { block, nullptr };
    });
    }
} g_registrar_iridium;
} // namespace
