// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <hrpt/fengyun_diff_decoder.h>
#include <hrpt/metop_cadu_deframer.h>
#include <hrpt/noaa_hrpt_decoder.h>
#include <hrpt/noaa_hrpt_deframer.h>
#include <hrpt/noaa_hrpt_pll_cf.h>
#include <hrpt/viterbi_fengyun_decoder.h>
#include <hrpt/viterbi_metop_decoder.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_hrpt {
    Registrar_hrpt()
    {
    wasm_registry_add("hrpt_fengyun_diff_decoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = hrpt::fengyun_diff_decoder::make();
        return { block, nullptr };
    });
    wasm_registry_add("metop_cadu_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = hrpt::metop_cadu_deframer::make(wasm_registry::boolean(p, "sync_check", true),
            wasm_registry::number<int>(p, "frame_length", 1024), wasm_registry::number<int>(p, "insync_after", 5), wasm_registry::number<int>(p, "outsync_after", 0));
        return { block, nullptr };
    });
    wasm_registry_add("noaa_hrpt_decoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = hrpt::noaa_hrpt_decoder::make(wasm_registry::boolean(p, "verbose", false), wasm_registry::boolean(p, "output", false));
        return { block, nullptr };
    });
    wasm_registry_add("noaa_hrpt_deframer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = hrpt::noaa_hrpt_deframer::make();
        return { block, nullptr };
    });
    wasm_registry_add("noaa_hrpt_pll_cf", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = hrpt::noaa_hrpt_pll_cf::make(wasm_registry::number<double>(p, "alpha", 0.0), wasm_registry::number<double>(p, "beta", 0.0),
            wasm_registry::number<double>(p, "max_offset", 0.0));
        return { block, nullptr };
    });
    wasm_registry_add("viterbi_fengyun_decoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = hrpt::viterbi_fengyun_decoder::make(wasm_registry::boolean(p, "sync_check", true),
            wasm_registry::number<double>(p, "ber_threshold", 0.1), wasm_registry::number<int>(p, "insync_after", 5), wasm_registry::number<int>(p, "outsync_after", 0),
            wasm_registry::number<int>(p, "reset_after", 50));
        return { block, nullptr };
    });
    wasm_registry_add("viterbi_metop_decoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = hrpt::viterbi_metop_decoder::make(wasm_registry::boolean(p, "sync_check", true),
            wasm_registry::number<double>(p, "ber_threshold", 0.1), wasm_registry::number<int>(p, "insync_after", 5), wasm_registry::number<int>(p, "outsync_after", 0),
            wasm_registry::number<int>(p, "reset_after", 50));
        return { block, nullptr };
    });
    }
} g_registrar_hrpt;
} // namespace
