// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include "adsb_blocks.hpp"

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_adsb {
    Registrar_adsb()
    {
    wasm_registry_add("adsb_decoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_adsb::make_decoder(wasm_registry::choice(p, "msg_filter", {{"\"Extended Squitter Only\"", "Extended Squitter Only"}, {"\"All Messages\"", "All Messages"}}, "Extended Squitter Only"), wasm_registry::choice(p, "error_corr", {{"\"None\"", "None"}, {"\"Conservative\"", "Conservative"}, {"\"Brute Force\"", "Brute Force"}}, "None"), wasm_registry::choice(p, "print_level", {{"\"None\"", "None"}, {"\"Brief\"", "Brief"}, {"\"Verbose\"", "Verbose"}}, "Brief"));
        return { block, nullptr };
    });
    wasm_registry_add("adsb_demod", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_adsb::make_demod(wasm_registry::number<double>(p, "fs", 2000000.0));
        return { block, nullptr };
    });
    wasm_registry_add("adsb_framer", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_adsb::make_framer(wasm_registry::number<double>(p, "fs", 2000000.0), wasm_registry::number<double>(p, "threshold", 0.01));
        BuiltBlock built{ block };
        built.numeric_setters["threshold"] = [block](double value) { block->set_threshold(static_cast<double>(value)); };
        return built;
    });
    }
} g_registrar_adsb;
} // namespace
