// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <gnuradio/vocoder/alaw_decode_bs.h>
#include <gnuradio/vocoder/alaw_encode_sb.h>
#include <gnuradio/vocoder/cvsd_decode_bs.h>
#include <gnuradio/vocoder/cvsd_encode_sb.h>
#include <gnuradio/vocoder/g721_decode_bs.h>
#include <gnuradio/vocoder/g721_encode_sb.h>
#include <gnuradio/vocoder/g723_24_decode_bs.h>
#include <gnuradio/vocoder/g723_24_encode_sb.h>
#include <gnuradio/vocoder/g723_40_decode_bs.h>
#include <gnuradio/vocoder/g723_40_encode_sb.h>
#include <gnuradio/vocoder/ulaw_decode_bs.h>
#include <gnuradio/vocoder/ulaw_encode_sb.h>
#include <vocoder_hier.hpp>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_vocoder {
    Registrar_vocoder()
    {
    wasm_registry_add("vocoder_alaw_decode_bs", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = vocoder::alaw_decode_bs::make();
        return { block, nullptr };
    });
    wasm_registry_add("vocoder_alaw_encode_sb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = vocoder::alaw_encode_sb::make();
        return { block, nullptr };
    });
    wasm_registry_add("vocoder_cvsd_decode_bf", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = CvsdDecode::make(wasm_registry::number<int>(p, "resample", 8), wasm_registry::number<double>(p, "bw", 0.5));
        return { block, nullptr };
    });
    wasm_registry_add("vocoder_cvsd_decode_bs", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = vocoder::cvsd_decode_bs::make();
        return { block, nullptr };
    });
    wasm_registry_add("vocoder_cvsd_encode_fb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = CvsdEncode::make(wasm_registry::number<int>(p, "resample", 8), wasm_registry::number<double>(p, "bw", 0.5));
        return { block, nullptr };
    });
    wasm_registry_add("vocoder_cvsd_encode_sb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = vocoder::cvsd_encode_sb::make();
        return { block, nullptr };
    });
    wasm_registry_add("vocoder_g721_decode_bs", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = vocoder::g721_decode_bs::make();
        return { block, nullptr };
    });
    wasm_registry_add("vocoder_g721_encode_sb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = vocoder::g721_encode_sb::make();
        return { block, nullptr };
    });
    wasm_registry_add("vocoder_g723_24_decode_bs", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = vocoder::g723_24_decode_bs::make();
        return { block, nullptr };
    });
    wasm_registry_add("vocoder_g723_24_encode_sb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = vocoder::g723_24_encode_sb::make();
        return { block, nullptr };
    });
    wasm_registry_add("vocoder_g723_40_decode_bs", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = vocoder::g723_40_decode_bs::make();
        return { block, nullptr };
    });
    wasm_registry_add("vocoder_g723_40_encode_sb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = vocoder::g723_40_encode_sb::make();
        return { block, nullptr };
    });
    wasm_registry_add("vocoder_ulaw_decode_bs", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = vocoder::ulaw_decode_bs::make();
        return { block, nullptr };
    });
    wasm_registry_add("vocoder_ulaw_encode_sb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = vocoder::ulaw_encode_sb::make();
        return { block, nullptr };
    });
    }
} g_registrar_vocoder;
} // namespace
