// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <gnuradio/channels/cfo_model.h>
#include <gnuradio/channels/channel_model.h>
#include <gnuradio/channels/channel_model2.h>
#include <gnuradio/channels/dynamic_channel_model.h>
#include <gnuradio/channels/selective_fading_model2.h>
#include <gnuradio/channels/sro_model.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_channels {
    Registrar_channels()
    {
    wasm_registry_add("channels_cfo_model", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = channels::cfo_model::make(wasm_registry::number<double>(p, "srate", 0.0), wasm_registry::number<double>(p, "stdev", 0.01), wasm_registry::number<double>(p, "maxdev", 1000.0), wasm_registry::number<int>(p, "seed", 0));
        BuiltBlock built{ block };
        built.numeric_setters["stdev"] = [block](double value) { block->set_std_dev(static_cast<double>(value)); };
        built.numeric_setters["maxdev"] = [block](double value) { block->set_max_dev(static_cast<double>(value)); };
        built.numeric_setters["srate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_channel_model", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = channels::channel_model::make(wasm_registry::number<double>(p, "noise_voltage", 0.0), wasm_registry::number<double>(p, "freq_offset", 0.0), wasm_registry::number<double>(p, "epsilon", 1.0), wasm_registry::vector<gr_complex>(p, "taps"), wasm_registry::number<int>(p, "seed", 0), wasm_registry::choice(p, "block_tags", {{"True", true}, {"False", false}}, false));
        BuiltBlock built{ block };
        built.numeric_setters["noise_voltage"] = [block](double value) { block->set_noise_voltage(static_cast<double>(value)); };
        built.numeric_setters["freq_offset"] = [block](double value) { block->set_frequency_offset(static_cast<double>(value)); };
        built.numeric_setters["epsilon"] = [block](double value) { block->set_timing_offset(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_channel_model2", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = channels::channel_model2::make(wasm_registry::number<double>(p, "noise_voltage", 0.0), wasm_registry::number<double>(p, "epsilon", 1.0), wasm_registry::vector<gr_complex>(p, "taps"), wasm_registry::number<int>(p, "seed", 0), wasm_registry::choice(p, "block_tags", {{"True", true}, {"False", false}}, false));
        BuiltBlock built{ block };
        built.numeric_setters["noise_voltage"] = [block](double value) { block->set_noise_voltage(static_cast<double>(value)); };
        built.numeric_setters["epsilon"] = [block](double value) { block->set_timing_offset(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_dynamic_channel_model", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = channels::dynamic_channel_model::make(wasm_registry::number<double>(p, "samp_rate", 0.0), wasm_registry::number<double>(p, "sro_stdev", 0.01), wasm_registry::number<double>(p, "sro_maxdev", 1000.0), wasm_registry::number<double>(p, "cfo_stdev", 0.01), wasm_registry::number<double>(p, "cfo_maxdev", 1000.0), wasm_registry::number<int>(p, "N", 8), wasm_registry::number<double>(p, "fD", 2.0), wasm_registry::choice(p, "LOS", {{"False", false}, {"True", true}}, false), wasm_registry::number<double>(p, "K", 4.0), wasm_registry::vector<float>(p, "delays"), wasm_registry::vector<float>(p, "mags"), wasm_registry::number<int>(p, "ntaps", 8), wasm_registry::number<double>(p, "noise_amp", 1.0), wasm_registry::number<int>(p, "seed", 0));
        BuiltBlock built{ block };
        built.numeric_setters["samp_rate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
        built.numeric_setters["sro_stdev"] = [block](double value) { block->set_sro_dev_std(static_cast<double>(value)); };
        built.numeric_setters["sro_maxdev"] = [block](double value) { block->set_sro_dev_max(static_cast<double>(value)); };
        built.numeric_setters["cfo_stdev"] = [block](double value) { block->set_cfo_dev_std(static_cast<double>(value)); };
        built.numeric_setters["cfo_maxdev"] = [block](double value) { block->set_cfo_dev_max(static_cast<double>(value)); };
        built.numeric_setters["noise_amp"] = [block](double value) { block->set_noise_amp(static_cast<double>(value)); };
        built.numeric_setters["fD"] = [block](double value) { block->set_doppler_freq(static_cast<double>(value)); };
        built.numeric_setters["K"] = [block](double value) { block->set_K(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_selective_fading_model2", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = channels::selective_fading_model2::make(wasm_registry::number<int>(p, "N", 8), wasm_registry::number<double>(p, "fDTs", 0.0), wasm_registry::choice(p, "LOS", {{"False", false}, {"True", true}}, false), wasm_registry::number<double>(p, "K", 4.0), wasm_registry::number<int>(p, "seed", 0), wasm_registry::vector<float>(p, "delays"), wasm_registry::vector<float>(p, "delay_std"), wasm_registry::vector<float>(p, "delay_maxdev"), wasm_registry::vector<float>(p, "mags"), wasm_registry::number<int>(p, "ntaps", 8));
        BuiltBlock built{ block };
        built.numeric_setters["fDTs"] = [block](double value) { block->set_fDTs(static_cast<double>(value)); };
        built.numeric_setters["K"] = [block](double value) { block->set_K(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("channels_sro_model", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = channels::sro_model::make(wasm_registry::number<double>(p, "srate", 0.0), wasm_registry::number<double>(p, "stdev", 0.01), wasm_registry::number<double>(p, "maxdev", 1000.0), wasm_registry::number<int>(p, "seed", 0));
        BuiltBlock built{ block };
        built.numeric_setters["stdev"] = [block](double value) { block->set_std_dev(static_cast<double>(value)); };
        built.numeric_setters["maxdev"] = [block](double value) { block->set_max_dev(static_cast<double>(value)); };
        built.numeric_setters["srate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
        return built;
    });
    }
} g_registrar_channels;
} // namespace
