// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include "ais_hier.hpp"
#include <gnuradio/ais/freqest.h>
#include <gnuradio/ais/invert.h>
#include <gnuradio/ais/pdu_to_nmea.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_ais {
    Registrar_ais()
    {
    wasm_registry_add("ais_invert", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ais::invert::make();
        return { block, nullptr };
    });
    wasm_registry_add("ais_pdu_to_nmea", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ais::pdu_to_nmea::make(wasm_registry::text(p, "designator", "A"));
        return { block, nullptr };
    });
    wasm_registry_add("ais_square_and_fft_sync", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_ais::make_square_and_fft_sync(wasm_registry::number<double>(p, "rate", 0.0), wasm_registry::number<double>(p, "sps", 9600.0), wasm_registry::number<int>(p, "fftlen", 1024));
        return { block, nullptr };
    });
    wasm_registry_add("ais_burst_demod", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_ais::make_ais_burst_demod(wasm_registry::number<int>(p, "samples_per_symbol", 5), wasm_registry::number<double>(p, "bits_per_sec", 9600.0), wasm_registry::number<double>(p, "freq_span", 1200.0), wasm_registry::number<double>(p, "threshold", 0.4), wasm_registry::number<int>(p, "burst_slots", 1));
        return { block, nullptr };
    });
    wasm_registry_add("ais_demod", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_ais::make_ais_demod(wasm_registry::number<double>(p, "samples_per_symbol", 0.0), wasm_registry::number<double>(p, "bits_per_sec", 9600.0), wasm_registry::number<double>(p, "clockrec_gain", 0.01), wasm_registry::number<double>(p, "omega_relative_limit", 0.01), wasm_registry::number<int>(p, "fftlen", 1024), wasm_registry::choice(p, "coherent", {{"True", true}, {"False", false}}, true));
        return { block, nullptr };
    });
    wasm_registry_add("ais_freqest", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = ais::freqest::make(wasm_registry::number<double>(p, "sample_rate", 0.0), wasm_registry::number<int>(p, "data_rate", 9600), wasm_registry::number<int>(p, "fftlen", 1024));
        return { block, nullptr };
    });
    wasm_registry_add("ais_viterbi_cpm_cb", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_ais::make_gmsk_viterbi(wasm_registry::number<int>(p, "samples_per_symbol", 2), wasm_registry::number<int>(p, "traceback_len", 48), wasm_registry::number<double>(p, "phase_gain", 0.1));
        return { block, nullptr };
    });
    }
} g_registrar_ais;
} // namespace
