// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <gnuradio/network/socket_pdu.h>
#include <gnuradio/network/tuntap_pdu.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_network {
    Registrar_network()
    {
    wasm_registry_add("network_socket_pdu", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = network::socket_pdu::make(wasm_registry::text(p, "type", "TCP_SERVER"), wasm_registry::text(p, "host", ""), wasm_registry::text(p, "port", "52001"), wasm_registry::number<int>(p, "mtu", 10000), wasm_registry::choice(p, "tcp_no_delay", {{"True", true}, {"False", false}}, false));
        return { block, nullptr };
    });
    wasm_registry_add("network_tuntap_pdu", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = network::tuntap_pdu::make(wasm_registry::text(p, "ifn", "tap0"), wasm_registry::number<int>(p, "mtu", 10000), wasm_registry::choice(p, "istunflag", {{"True", true}, {"False", false}}, false));
        return { block, nullptr };
    });
    }
} g_registrar_network;
} // namespace
