// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <gnuradio/channels/channel_model.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_channels {
    Registrar_channels()
    {
    wasm_registry_add("channels_channel_model", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = channels::channel_model::make(wasm_registry::number<double>(p, "noise_voltage", 0.0), wasm_registry::number<double>(p, "freq_offset", 0.0), wasm_registry::number<double>(p, "epsilon", 1.0), wasm_registry::vector<gr_complex>(p, "taps"), wasm_registry::number<int>(p, "seed", 0), wasm_registry::choice(p, "block_tags", {{"True", true}, {"False", false}}, false));
        BuiltBlock built{ block };
        built.numeric_setters["noise_voltage"] = [block](double value) { block->set_noise_voltage(static_cast<double>(value)); };
        built.numeric_setters["freq_offset"] = [block](double value) { block->set_frequency_offset(static_cast<double>(value)); };
        built.numeric_setters["epsilon"] = [block](double value) { block->set_timing_offset(static_cast<double>(value)); };
        return built;
    });
    }
} g_registrar_channels;
} // namespace
