// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <dvbs2rx/bbdeheader_bb.h>
#include <dvbs2rx/bbdescrambler_bb.h>
#include <dvbs2rx/bch_decoder_bb.h>
#include <dvbs2rx/ldpc_decoder_cb.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_dvbs2rx {
    Registrar_dvbs2rx()
    {
    wasm_registry_add("dvbs2rx_bbdeheader_bb", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::bbdeheader_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate3", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C9_10", dvbs2rx::C9_10}, {"C2_9_VLSNR", dvbs2rx::C2_9_VLSNR}, {"C13_45", dvbs2rx::C13_45}, {"C9_20", dvbs2rx::C9_20}, {"C90_180", dvbs2rx::C90_180}, {"C96_180", dvbs2rx::C96_180}, {"C11_20", dvbs2rx::C11_20}, {"C100_180", dvbs2rx::C100_180}, {"C104_180", dvbs2rx::C104_180}, {"C26_45", dvbs2rx::C26_45}, {"C18_30", dvbs2rx::C18_30}, {"C28_45", dvbs2rx::C28_45}, {"C23_36", dvbs2rx::C23_36}, {"C116_180", dvbs2rx::C116_180}, {"C20_30", dvbs2rx::C20_30}, {"C124_180", dvbs2rx::C124_180}, {"C25_36", dvbs2rx::C25_36}, {"C128_180", dvbs2rx::C128_180}, {"C13_18", dvbs2rx::C13_18}, {"C132_180", dvbs2rx::C132_180}, {"C22_30", dvbs2rx::C22_30}, {"C135_180", dvbs2rx::C135_180}, {"C140_180", dvbs2rx::C140_180}, {"C7_9", dvbs2rx::C7_9}, {"C154_180", dvbs2rx::C154_180}}, dvbs2rx::C1_4)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::bbdeheader_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_MEDIUM,
            wasm_registry::choice(p, "rate4", {{"C1_5_MEDIUM", dvbs2rx::C1_5_MEDIUM}, {"C11_45_MEDIUM", dvbs2rx::C11_45_MEDIUM}, {"C1_3_MEDIUM", dvbs2rx::C1_3_MEDIUM}}, dvbs2rx::C1_5_MEDIUM)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::bbdeheader_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate5", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C11_45", dvbs2rx::C11_45}, {"C4_15", dvbs2rx::C4_15}, {"C14_45", dvbs2rx::C14_45}, {"C7_15", dvbs2rx::C7_15}, {"C8_15", dvbs2rx::C8_15}, {"C26_45", dvbs2rx::C26_45}, {"C32_45", dvbs2rx::C32_45}, {"C1_5_VLSNR_SF2", dvbs2rx::C1_5_VLSNR_SF2}, {"C11_45_VLSNR_SF2", dvbs2rx::C11_45_VLSNR_SF2}, {"C1_5_VLSNR", dvbs2rx::C1_5_VLSNR}, {"C4_15_VLSNR", dvbs2rx::C4_15_VLSNR}, {"C1_3_VLSNR", dvbs2rx::C1_3_VLSNR}}, dvbs2rx::C1_4)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::bbdeheader_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate3", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C9_10", dvbs2rx::C9_10}, {"C2_9_VLSNR", dvbs2rx::C2_9_VLSNR}, {"C13_45", dvbs2rx::C13_45}, {"C9_20", dvbs2rx::C9_20}, {"C90_180", dvbs2rx::C90_180}, {"C96_180", dvbs2rx::C96_180}, {"C11_20", dvbs2rx::C11_20}, {"C100_180", dvbs2rx::C100_180}, {"C104_180", dvbs2rx::C104_180}, {"C26_45", dvbs2rx::C26_45}, {"C18_30", dvbs2rx::C18_30}, {"C28_45", dvbs2rx::C28_45}, {"C23_36", dvbs2rx::C23_36}, {"C116_180", dvbs2rx::C116_180}, {"C20_30", dvbs2rx::C20_30}, {"C124_180", dvbs2rx::C124_180}, {"C25_36", dvbs2rx::C25_36}, {"C128_180", dvbs2rx::C128_180}, {"C13_18", dvbs2rx::C13_18}, {"C132_180", dvbs2rx::C132_180}, {"C22_30", dvbs2rx::C22_30}, {"C135_180", dvbs2rx::C135_180}, {"C140_180", dvbs2rx::C140_180}, {"C7_9", dvbs2rx::C7_9}, {"C154_180", dvbs2rx::C154_180}}, dvbs2rx::C1_4)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::bbdeheader_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_MEDIUM,
            wasm_registry::choice(p, "rate4", {{"C1_5_MEDIUM", dvbs2rx::C1_5_MEDIUM}, {"C11_45_MEDIUM", dvbs2rx::C11_45_MEDIUM}, {"C1_3_MEDIUM", dvbs2rx::C1_3_MEDIUM}}, dvbs2rx::C1_5_MEDIUM)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::bbdeheader_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate5", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C11_45", dvbs2rx::C11_45}, {"C4_15", dvbs2rx::C4_15}, {"C14_45", dvbs2rx::C14_45}, {"C7_15", dvbs2rx::C7_15}, {"C8_15", dvbs2rx::C8_15}, {"C26_45", dvbs2rx::C26_45}, {"C32_45", dvbs2rx::C32_45}, {"C1_5_VLSNR_SF2", dvbs2rx::C1_5_VLSNR_SF2}, {"C11_45_VLSNR_SF2", dvbs2rx::C11_45_VLSNR_SF2}, {"C1_5_VLSNR", dvbs2rx::C1_5_VLSNR}, {"C4_15_VLSNR", dvbs2rx::C4_15_VLSNR}, {"C1_3_VLSNR", dvbs2rx::C1_3_VLSNR}}, dvbs2rx::C1_4)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::bbdeheader_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate1", {{"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_2)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::bbdeheader_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate1", {{"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_2)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::bbdeheader_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate1", {{"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_2)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::bbdeheader_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate2", {{"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_3)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::bbdeheader_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate2", {{"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_3)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::bbdeheader_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate2", {{"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_3)
            );
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for dvbs2rx_bbdeheader_bb");
    });
    wasm_registry_add("dvbs2rx_bbdescrambler_bb", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::bbdescrambler_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate3", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C9_10", dvbs2rx::C9_10}, {"C2_9_VLSNR", dvbs2rx::C2_9_VLSNR}, {"C13_45", dvbs2rx::C13_45}, {"C9_20", dvbs2rx::C9_20}, {"C90_180", dvbs2rx::C90_180}, {"C96_180", dvbs2rx::C96_180}, {"C11_20", dvbs2rx::C11_20}, {"C100_180", dvbs2rx::C100_180}, {"C104_180", dvbs2rx::C104_180}, {"C26_45", dvbs2rx::C26_45}, {"C18_30", dvbs2rx::C18_30}, {"C28_45", dvbs2rx::C28_45}, {"C23_36", dvbs2rx::C23_36}, {"C116_180", dvbs2rx::C116_180}, {"C20_30", dvbs2rx::C20_30}, {"C124_180", dvbs2rx::C124_180}, {"C25_36", dvbs2rx::C25_36}, {"C128_180", dvbs2rx::C128_180}, {"C13_18", dvbs2rx::C13_18}, {"C132_180", dvbs2rx::C132_180}, {"C22_30", dvbs2rx::C22_30}, {"C135_180", dvbs2rx::C135_180}, {"C140_180", dvbs2rx::C140_180}, {"C7_9", dvbs2rx::C7_9}, {"C154_180", dvbs2rx::C154_180}}, dvbs2rx::C1_4)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::bbdescrambler_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_MEDIUM,
            wasm_registry::choice(p, "rate4", {{"C1_5_MEDIUM", dvbs2rx::C1_5_MEDIUM}, {"C11_45_MEDIUM", dvbs2rx::C11_45_MEDIUM}, {"C1_3_MEDIUM", dvbs2rx::C1_3_MEDIUM}}, dvbs2rx::C1_5_MEDIUM)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::bbdescrambler_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate5", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C11_45", dvbs2rx::C11_45}, {"C4_15", dvbs2rx::C4_15}, {"C14_45", dvbs2rx::C14_45}, {"C7_15", dvbs2rx::C7_15}, {"C8_15", dvbs2rx::C8_15}, {"C26_45", dvbs2rx::C26_45}, {"C32_45", dvbs2rx::C32_45}, {"C1_5_VLSNR_SF2", dvbs2rx::C1_5_VLSNR_SF2}, {"C11_45_VLSNR_SF2", dvbs2rx::C11_45_VLSNR_SF2}, {"C1_5_VLSNR", dvbs2rx::C1_5_VLSNR}, {"C4_15_VLSNR", dvbs2rx::C4_15_VLSNR}, {"C1_3_VLSNR", dvbs2rx::C1_3_VLSNR}}, dvbs2rx::C1_4)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::bbdescrambler_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate3", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C9_10", dvbs2rx::C9_10}, {"C2_9_VLSNR", dvbs2rx::C2_9_VLSNR}, {"C13_45", dvbs2rx::C13_45}, {"C9_20", dvbs2rx::C9_20}, {"C90_180", dvbs2rx::C90_180}, {"C96_180", dvbs2rx::C96_180}, {"C11_20", dvbs2rx::C11_20}, {"C100_180", dvbs2rx::C100_180}, {"C104_180", dvbs2rx::C104_180}, {"C26_45", dvbs2rx::C26_45}, {"C18_30", dvbs2rx::C18_30}, {"C28_45", dvbs2rx::C28_45}, {"C23_36", dvbs2rx::C23_36}, {"C116_180", dvbs2rx::C116_180}, {"C20_30", dvbs2rx::C20_30}, {"C124_180", dvbs2rx::C124_180}, {"C25_36", dvbs2rx::C25_36}, {"C128_180", dvbs2rx::C128_180}, {"C13_18", dvbs2rx::C13_18}, {"C132_180", dvbs2rx::C132_180}, {"C22_30", dvbs2rx::C22_30}, {"C135_180", dvbs2rx::C135_180}, {"C140_180", dvbs2rx::C140_180}, {"C7_9", dvbs2rx::C7_9}, {"C154_180", dvbs2rx::C154_180}}, dvbs2rx::C1_4)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::bbdescrambler_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_MEDIUM,
            wasm_registry::choice(p, "rate4", {{"C1_5_MEDIUM", dvbs2rx::C1_5_MEDIUM}, {"C11_45_MEDIUM", dvbs2rx::C11_45_MEDIUM}, {"C1_3_MEDIUM", dvbs2rx::C1_3_MEDIUM}}, dvbs2rx::C1_5_MEDIUM)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::bbdescrambler_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate5", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C11_45", dvbs2rx::C11_45}, {"C4_15", dvbs2rx::C4_15}, {"C14_45", dvbs2rx::C14_45}, {"C7_15", dvbs2rx::C7_15}, {"C8_15", dvbs2rx::C8_15}, {"C26_45", dvbs2rx::C26_45}, {"C32_45", dvbs2rx::C32_45}, {"C1_5_VLSNR_SF2", dvbs2rx::C1_5_VLSNR_SF2}, {"C11_45_VLSNR_SF2", dvbs2rx::C11_45_VLSNR_SF2}, {"C1_5_VLSNR", dvbs2rx::C1_5_VLSNR}, {"C4_15_VLSNR", dvbs2rx::C4_15_VLSNR}, {"C1_3_VLSNR", dvbs2rx::C1_3_VLSNR}}, dvbs2rx::C1_4)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::bbdescrambler_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate1", {{"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_2)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::bbdescrambler_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate1", {{"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_2)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::bbdescrambler_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate1", {{"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_2)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::bbdescrambler_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate2", {{"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_3)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::bbdescrambler_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate2", {{"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_3)
            );
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::bbdescrambler_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate2", {{"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_3)
            );
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for dvbs2rx_bbdescrambler_bb");
    });
    wasm_registry_add("dvbs2rx_bch_decoder_bb", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::bch_decoder_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate3", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C9_10", dvbs2rx::C9_10}, {"C2_9_VLSNR", dvbs2rx::C2_9_VLSNR}, {"C13_45", dvbs2rx::C13_45}, {"C9_20", dvbs2rx::C9_20}, {"C90_180", dvbs2rx::C90_180}, {"C96_180", dvbs2rx::C96_180}, {"C11_20", dvbs2rx::C11_20}, {"C100_180", dvbs2rx::C100_180}, {"C104_180", dvbs2rx::C104_180}, {"C26_45", dvbs2rx::C26_45}, {"C18_30", dvbs2rx::C18_30}, {"C28_45", dvbs2rx::C28_45}, {"C23_36", dvbs2rx::C23_36}, {"C116_180", dvbs2rx::C116_180}, {"C20_30", dvbs2rx::C20_30}, {"C124_180", dvbs2rx::C124_180}, {"C25_36", dvbs2rx::C25_36}, {"C128_180", dvbs2rx::C128_180}, {"C13_18", dvbs2rx::C13_18}, {"C132_180", dvbs2rx::C132_180}, {"C22_30", dvbs2rx::C22_30}, {"C135_180", dvbs2rx::C135_180}, {"C140_180", dvbs2rx::C140_180}, {"C7_9", dvbs2rx::C7_9}, {"C154_180", dvbs2rx::C154_180}}, dvbs2rx::C1_4),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::bch_decoder_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_MEDIUM,
            wasm_registry::choice(p, "rate4", {{"C1_5_MEDIUM", dvbs2rx::C1_5_MEDIUM}, {"C11_45_MEDIUM", dvbs2rx::C11_45_MEDIUM}, {"C1_3_MEDIUM", dvbs2rx::C1_3_MEDIUM}}, dvbs2rx::C1_5_MEDIUM),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::bch_decoder_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate5", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C11_45", dvbs2rx::C11_45}, {"C4_15", dvbs2rx::C4_15}, {"C14_45", dvbs2rx::C14_45}, {"C7_15", dvbs2rx::C7_15}, {"C8_15", dvbs2rx::C8_15}, {"C26_45", dvbs2rx::C26_45}, {"C32_45", dvbs2rx::C32_45}, {"C1_5_VLSNR_SF2", dvbs2rx::C1_5_VLSNR_SF2}, {"C11_45_VLSNR_SF2", dvbs2rx::C11_45_VLSNR_SF2}, {"C1_5_VLSNR", dvbs2rx::C1_5_VLSNR}, {"C4_15_VLSNR", dvbs2rx::C4_15_VLSNR}, {"C1_3_VLSNR", dvbs2rx::C1_3_VLSNR}}, dvbs2rx::C1_4),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::bch_decoder_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate3", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C9_10", dvbs2rx::C9_10}, {"C2_9_VLSNR", dvbs2rx::C2_9_VLSNR}, {"C13_45", dvbs2rx::C13_45}, {"C9_20", dvbs2rx::C9_20}, {"C90_180", dvbs2rx::C90_180}, {"C96_180", dvbs2rx::C96_180}, {"C11_20", dvbs2rx::C11_20}, {"C100_180", dvbs2rx::C100_180}, {"C104_180", dvbs2rx::C104_180}, {"C26_45", dvbs2rx::C26_45}, {"C18_30", dvbs2rx::C18_30}, {"C28_45", dvbs2rx::C28_45}, {"C23_36", dvbs2rx::C23_36}, {"C116_180", dvbs2rx::C116_180}, {"C20_30", dvbs2rx::C20_30}, {"C124_180", dvbs2rx::C124_180}, {"C25_36", dvbs2rx::C25_36}, {"C128_180", dvbs2rx::C128_180}, {"C13_18", dvbs2rx::C13_18}, {"C132_180", dvbs2rx::C132_180}, {"C22_30", dvbs2rx::C22_30}, {"C135_180", dvbs2rx::C135_180}, {"C140_180", dvbs2rx::C140_180}, {"C7_9", dvbs2rx::C7_9}, {"C154_180", dvbs2rx::C154_180}}, dvbs2rx::C1_4),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::bch_decoder_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_MEDIUM,
            wasm_registry::choice(p, "rate4", {{"C1_5_MEDIUM", dvbs2rx::C1_5_MEDIUM}, {"C11_45_MEDIUM", dvbs2rx::C11_45_MEDIUM}, {"C1_3_MEDIUM", dvbs2rx::C1_3_MEDIUM}}, dvbs2rx::C1_5_MEDIUM),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::bch_decoder_bb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate5", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C11_45", dvbs2rx::C11_45}, {"C4_15", dvbs2rx::C4_15}, {"C14_45", dvbs2rx::C14_45}, {"C7_15", dvbs2rx::C7_15}, {"C8_15", dvbs2rx::C8_15}, {"C26_45", dvbs2rx::C26_45}, {"C32_45", dvbs2rx::C32_45}, {"C1_5_VLSNR_SF2", dvbs2rx::C1_5_VLSNR_SF2}, {"C11_45_VLSNR_SF2", dvbs2rx::C11_45_VLSNR_SF2}, {"C1_5_VLSNR", dvbs2rx::C1_5_VLSNR}, {"C4_15_VLSNR", dvbs2rx::C4_15_VLSNR}, {"C1_3_VLSNR", dvbs2rx::C1_3_VLSNR}}, dvbs2rx::C1_4),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::bch_decoder_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate1", {{"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_2),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::bch_decoder_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate1", {{"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_2),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::bch_decoder_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate1", {{"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_2),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::bch_decoder_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate2", {{"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_3),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::bch_decoder_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate2", {{"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_3),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::bch_decoder_bb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate2", {{"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_3),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for dvbs2rx_bch_decoder_bb");
    });
    wasm_registry_add("dvbs2rx_ldpc_decoder_cb", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::ldpc_decoder_cb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate3", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C9_10", dvbs2rx::C9_10}, {"C2_9_VLSNR", dvbs2rx::C2_9_VLSNR}, {"C13_45", dvbs2rx::C13_45}, {"C9_20", dvbs2rx::C9_20}, {"C90_180", dvbs2rx::C90_180}, {"C96_180", dvbs2rx::C96_180}, {"C11_20", dvbs2rx::C11_20}, {"C100_180", dvbs2rx::C100_180}, {"C104_180", dvbs2rx::C104_180}, {"C26_45", dvbs2rx::C26_45}, {"C18_30", dvbs2rx::C18_30}, {"C28_45", dvbs2rx::C28_45}, {"C23_36", dvbs2rx::C23_36}, {"C116_180", dvbs2rx::C116_180}, {"C20_30", dvbs2rx::C20_30}, {"C124_180", dvbs2rx::C124_180}, {"C25_36", dvbs2rx::C25_36}, {"C128_180", dvbs2rx::C128_180}, {"C13_18", dvbs2rx::C13_18}, {"C132_180", dvbs2rx::C132_180}, {"C22_30", dvbs2rx::C22_30}, {"C135_180", dvbs2rx::C135_180}, {"C140_180", dvbs2rx::C140_180}, {"C7_9", dvbs2rx::C7_9}, {"C154_180", dvbs2rx::C154_180}}, dvbs2rx::C1_4),
            wasm_registry::choice(p, "constellation2", {{"MOD_QPSK", dvbs2rx::MOD_QPSK}, {"MOD_8PSK", dvbs2rx::MOD_8PSK}}, dvbs2rx::MOD_QPSK),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD), wasm_registry::choice(p, "infomode", {{"INFO_OFF", dvbs2rx::INFO_OFF}, {"INFO_ON", dvbs2rx::INFO_ON}}, dvbs2rx::INFO_OFF));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::ldpc_decoder_cb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_MEDIUM,
            wasm_registry::choice(p, "rate4", {{"C1_5_MEDIUM", dvbs2rx::C1_5_MEDIUM}, {"C11_45_MEDIUM", dvbs2rx::C11_45_MEDIUM}, {"C1_3_MEDIUM", dvbs2rx::C1_3_MEDIUM}}, dvbs2rx::C1_5_MEDIUM),
            wasm_registry::choice(p, "constellation2", {{"MOD_QPSK", dvbs2rx::MOD_QPSK}, {"MOD_8PSK", dvbs2rx::MOD_8PSK}}, dvbs2rx::MOD_QPSK),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD), wasm_registry::choice(p, "infomode", {{"INFO_OFF", dvbs2rx::INFO_OFF}, {"INFO_ON", dvbs2rx::INFO_ON}}, dvbs2rx::INFO_OFF));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::ldpc_decoder_cb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate5", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C11_45", dvbs2rx::C11_45}, {"C4_15", dvbs2rx::C4_15}, {"C14_45", dvbs2rx::C14_45}, {"C7_15", dvbs2rx::C7_15}, {"C8_15", dvbs2rx::C8_15}, {"C26_45", dvbs2rx::C26_45}, {"C32_45", dvbs2rx::C32_45}, {"C1_5_VLSNR_SF2", dvbs2rx::C1_5_VLSNR_SF2}, {"C11_45_VLSNR_SF2", dvbs2rx::C11_45_VLSNR_SF2}, {"C1_5_VLSNR", dvbs2rx::C1_5_VLSNR}, {"C4_15_VLSNR", dvbs2rx::C4_15_VLSNR}, {"C1_3_VLSNR", dvbs2rx::C1_3_VLSNR}}, dvbs2rx::C1_4),
            wasm_registry::choice(p, "constellation2", {{"MOD_QPSK", dvbs2rx::MOD_QPSK}, {"MOD_8PSK", dvbs2rx::MOD_8PSK}}, dvbs2rx::MOD_QPSK),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD), wasm_registry::choice(p, "infomode", {{"INFO_OFF", dvbs2rx::INFO_OFF}, {"INFO_ON", dvbs2rx::INFO_ON}}, dvbs2rx::INFO_OFF));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::ldpc_decoder_cb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate3", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C9_10", dvbs2rx::C9_10}, {"C2_9_VLSNR", dvbs2rx::C2_9_VLSNR}, {"C13_45", dvbs2rx::C13_45}, {"C9_20", dvbs2rx::C9_20}, {"C90_180", dvbs2rx::C90_180}, {"C96_180", dvbs2rx::C96_180}, {"C11_20", dvbs2rx::C11_20}, {"C100_180", dvbs2rx::C100_180}, {"C104_180", dvbs2rx::C104_180}, {"C26_45", dvbs2rx::C26_45}, {"C18_30", dvbs2rx::C18_30}, {"C28_45", dvbs2rx::C28_45}, {"C23_36", dvbs2rx::C23_36}, {"C116_180", dvbs2rx::C116_180}, {"C20_30", dvbs2rx::C20_30}, {"C124_180", dvbs2rx::C124_180}, {"C25_36", dvbs2rx::C25_36}, {"C128_180", dvbs2rx::C128_180}, {"C13_18", dvbs2rx::C13_18}, {"C132_180", dvbs2rx::C132_180}, {"C22_30", dvbs2rx::C22_30}, {"C135_180", dvbs2rx::C135_180}, {"C140_180", dvbs2rx::C140_180}, {"C7_9", dvbs2rx::C7_9}, {"C154_180", dvbs2rx::C154_180}}, dvbs2rx::C1_4),
            wasm_registry::choice(p, "constellation2", {{"MOD_QPSK", dvbs2rx::MOD_QPSK}, {"MOD_8PSK", dvbs2rx::MOD_8PSK}}, dvbs2rx::MOD_QPSK),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD), wasm_registry::choice(p, "infomode", {{"INFO_OFF", dvbs2rx::INFO_OFF}, {"INFO_ON", dvbs2rx::INFO_ON}}, dvbs2rx::INFO_OFF));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::ldpc_decoder_cb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_MEDIUM,
            wasm_registry::choice(p, "rate4", {{"C1_5_MEDIUM", dvbs2rx::C1_5_MEDIUM}, {"C11_45_MEDIUM", dvbs2rx::C11_45_MEDIUM}, {"C1_3_MEDIUM", dvbs2rx::C1_3_MEDIUM}}, dvbs2rx::C1_5_MEDIUM),
            wasm_registry::choice(p, "constellation2", {{"MOD_QPSK", dvbs2rx::MOD_QPSK}, {"MOD_8PSK", dvbs2rx::MOD_8PSK}}, dvbs2rx::MOD_QPSK),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD), wasm_registry::choice(p, "infomode", {{"INFO_OFF", dvbs2rx::INFO_OFF}, {"INFO_ON", dvbs2rx::INFO_ON}}, dvbs2rx::INFO_OFF));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBS2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::ldpc_decoder_cb::make(dvbs2rx::STANDARD_DVBS2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate5", {{"C1_4", dvbs2rx::C1_4}, {"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}, {"C8_9", dvbs2rx::C8_9}, {"C11_45", dvbs2rx::C11_45}, {"C4_15", dvbs2rx::C4_15}, {"C14_45", dvbs2rx::C14_45}, {"C7_15", dvbs2rx::C7_15}, {"C8_15", dvbs2rx::C8_15}, {"C26_45", dvbs2rx::C26_45}, {"C32_45", dvbs2rx::C32_45}, {"C1_5_VLSNR_SF2", dvbs2rx::C1_5_VLSNR_SF2}, {"C11_45_VLSNR_SF2", dvbs2rx::C11_45_VLSNR_SF2}, {"C1_5_VLSNR", dvbs2rx::C1_5_VLSNR}, {"C4_15_VLSNR", dvbs2rx::C4_15_VLSNR}, {"C1_3_VLSNR", dvbs2rx::C1_3_VLSNR}}, dvbs2rx::C1_4),
            wasm_registry::choice(p, "constellation2", {{"MOD_QPSK", dvbs2rx::MOD_QPSK}, {"MOD_8PSK", dvbs2rx::MOD_8PSK}}, dvbs2rx::MOD_QPSK),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD), wasm_registry::choice(p, "infomode", {{"INFO_OFF", dvbs2rx::INFO_OFF}, {"INFO_ON", dvbs2rx::INFO_ON}}, dvbs2rx::INFO_OFF));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::ldpc_decoder_cb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate1", {{"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_2),
            wasm_registry::choice(p, "constellation1", {{"MOD_QPSK", dvbs2rx::MOD_QPSK}, {"MOD_16QAM", dvbs2rx::MOD_16QAM}, {"MOD_64QAM", dvbs2rx::MOD_64QAM}, {"MOD_256QAM", dvbs2rx::MOD_256QAM}}, dvbs2rx::MOD_QPSK),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD), wasm_registry::choice(p, "infomode", {{"INFO_OFF", dvbs2rx::INFO_OFF}, {"INFO_ON", dvbs2rx::INFO_ON}}, dvbs2rx::INFO_OFF));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::ldpc_decoder_cb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate1", {{"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_2),
            wasm_registry::choice(p, "constellation1", {{"MOD_QPSK", dvbs2rx::MOD_QPSK}, {"MOD_16QAM", dvbs2rx::MOD_16QAM}, {"MOD_64QAM", dvbs2rx::MOD_64QAM}, {"MOD_256QAM", dvbs2rx::MOD_256QAM}}, dvbs2rx::MOD_QPSK),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD), wasm_registry::choice(p, "infomode", {{"INFO_OFF", dvbs2rx::INFO_OFF}, {"INFO_ON", dvbs2rx::INFO_ON}}, dvbs2rx::INFO_OFF));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_NORMAL" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::ldpc_decoder_cb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_NORMAL,
            wasm_registry::choice(p, "rate1", {{"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_2),
            wasm_registry::choice(p, "constellation1", {{"MOD_QPSK", dvbs2rx::MOD_QPSK}, {"MOD_16QAM", dvbs2rx::MOD_16QAM}, {"MOD_64QAM", dvbs2rx::MOD_64QAM}, {"MOD_256QAM", dvbs2rx::MOD_256QAM}}, dvbs2rx::MOD_QPSK),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD), wasm_registry::choice(p, "infomode", {{"INFO_OFF", dvbs2rx::INFO_OFF}, {"INFO_ON", dvbs2rx::INFO_ON}}, dvbs2rx::INFO_OFF));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_NORMAL") {
            auto block = dvbs2rx::ldpc_decoder_cb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate2", {{"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_3),
            wasm_registry::choice(p, "constellation1", {{"MOD_QPSK", dvbs2rx::MOD_QPSK}, {"MOD_16QAM", dvbs2rx::MOD_16QAM}, {"MOD_64QAM", dvbs2rx::MOD_64QAM}, {"MOD_256QAM", dvbs2rx::MOD_256QAM}}, dvbs2rx::MOD_QPSK),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD), wasm_registry::choice(p, "infomode", {{"INFO_OFF", dvbs2rx::INFO_OFF}, {"INFO_ON", dvbs2rx::INFO_ON}}, dvbs2rx::INFO_OFF));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_MEDIUM") {
            auto block = dvbs2rx::ldpc_decoder_cb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate2", {{"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_3),
            wasm_registry::choice(p, "constellation1", {{"MOD_QPSK", dvbs2rx::MOD_QPSK}, {"MOD_16QAM", dvbs2rx::MOD_16QAM}, {"MOD_64QAM", dvbs2rx::MOD_64QAM}, {"MOD_256QAM", dvbs2rx::MOD_256QAM}}, dvbs2rx::MOD_QPSK),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD), wasm_registry::choice(p, "infomode", {{"INFO_OFF", dvbs2rx::INFO_OFF}, {"INFO_ON", dvbs2rx::INFO_ON}}, dvbs2rx::INFO_OFF));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "standard", "STANDARD_DVBS2") == "STANDARD_DVBT2" && wasm_registry::text(p, "framesize1", "FECFRAME_NORMAL") == "FECFRAME_SHORT" && wasm_registry::text(p, "framesize2", "FECFRAME_NORMAL") == "FECFRAME_SHORT") {
            auto block = dvbs2rx::ldpc_decoder_cb::make(dvbs2rx::STANDARD_DVBT2,
            dvbs2rx::FECFRAME_SHORT,
            wasm_registry::choice(p, "rate2", {{"C1_3", dvbs2rx::C1_3}, {"C2_5", dvbs2rx::C2_5}, {"C1_2", dvbs2rx::C1_2}, {"C3_5", dvbs2rx::C3_5}, {"C2_3", dvbs2rx::C2_3}, {"C3_4", dvbs2rx::C3_4}, {"C4_5", dvbs2rx::C4_5}, {"C5_6", dvbs2rx::C5_6}}, dvbs2rx::C1_3),
            wasm_registry::choice(p, "constellation1", {{"MOD_QPSK", dvbs2rx::MOD_QPSK}, {"MOD_16QAM", dvbs2rx::MOD_16QAM}, {"MOD_64QAM", dvbs2rx::MOD_64QAM}, {"MOD_256QAM", dvbs2rx::MOD_256QAM}}, dvbs2rx::MOD_QPSK),
            wasm_registry::choice(p, "outputmode", {{"OM_CODEWORD", dvbs2rx::OM_CODEWORD}, {"OM_MESSAGE", dvbs2rx::OM_MESSAGE}}, dvbs2rx::OM_CODEWORD), wasm_registry::choice(p, "infomode", {{"INFO_OFF", dvbs2rx::INFO_OFF}, {"INFO_ON", dvbs2rx::INFO_ON}}, dvbs2rx::INFO_OFF));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for dvbs2rx_ldpc_decoder_cb");
    });
    }
} g_registrar_dvbs2rx;
} // namespace
