// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <gnuradio/pdu/pdu_to_stream.h>
#include <gnuradio/pdu/pdu_to_tagged_stream.h>
#include <gnuradio/pdu/tagged_stream_to_pdu.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_pdu {
    Registrar_pdu()
    {
    wasm_registry_add("pdu_pdu_to_stream_x", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "complex") == "complex") {
            auto block = pdu::pdu_to_stream_c::make(wasm_registry::choice(p, "early_behavior", {{"pdu::EARLY_BURST_APPEND", pdu::EARLY_BURST_APPEND}, {"pdu::EARLY_BURST_DROP", pdu::EARLY_BURST_DROP}, {"pdu::EARLY_BURST_BALK", pdu::EARLY_BURST_BALK}}, pdu::EARLY_BURST_APPEND), wasm_registry::number<int>(p, "depth", 64));
            BuiltBlock built{ block };
            built.numeric_setters["depth"] = [block](double value) { block->set_max_queue_size(static_cast<int>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "complex") == "float") {
            auto block = pdu::pdu_to_stream_f::make(wasm_registry::choice(p, "early_behavior", {{"pdu::EARLY_BURST_APPEND", pdu::EARLY_BURST_APPEND}, {"pdu::EARLY_BURST_DROP", pdu::EARLY_BURST_DROP}, {"pdu::EARLY_BURST_BALK", pdu::EARLY_BURST_BALK}}, pdu::EARLY_BURST_APPEND), wasm_registry::number<int>(p, "depth", 64));
            BuiltBlock built{ block };
            built.numeric_setters["depth"] = [block](double value) { block->set_max_queue_size(static_cast<int>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "complex") == "int") {
            auto block = pdu::pdu_to_stream_i::make(wasm_registry::choice(p, "early_behavior", {{"pdu::EARLY_BURST_APPEND", pdu::EARLY_BURST_APPEND}, {"pdu::EARLY_BURST_DROP", pdu::EARLY_BURST_DROP}, {"pdu::EARLY_BURST_BALK", pdu::EARLY_BURST_BALK}}, pdu::EARLY_BURST_APPEND), wasm_registry::number<int>(p, "depth", 64));
            BuiltBlock built{ block };
            built.numeric_setters["depth"] = [block](double value) { block->set_max_queue_size(static_cast<int>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "complex") == "short") {
            auto block = pdu::pdu_to_stream_s::make(wasm_registry::choice(p, "early_behavior", {{"pdu::EARLY_BURST_APPEND", pdu::EARLY_BURST_APPEND}, {"pdu::EARLY_BURST_DROP", pdu::EARLY_BURST_DROP}, {"pdu::EARLY_BURST_BALK", pdu::EARLY_BURST_BALK}}, pdu::EARLY_BURST_APPEND), wasm_registry::number<int>(p, "depth", 64));
            BuiltBlock built{ block };
            built.numeric_setters["depth"] = [block](double value) { block->set_max_queue_size(static_cast<int>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "complex") == "byte") {
            auto block = pdu::pdu_to_stream_b::make(wasm_registry::choice(p, "early_behavior", {{"pdu::EARLY_BURST_APPEND", pdu::EARLY_BURST_APPEND}, {"pdu::EARLY_BURST_DROP", pdu::EARLY_BURST_DROP}, {"pdu::EARLY_BURST_BALK", pdu::EARLY_BURST_BALK}}, pdu::EARLY_BURST_APPEND), wasm_registry::number<int>(p, "depth", 64));
            BuiltBlock built{ block };
            built.numeric_setters["depth"] = [block](double value) { block->set_max_queue_size(static_cast<int>(value)); };
            return built;
        }
        throw std::runtime_error("unsupported type selection for pdu_pdu_to_stream_x");
    });
    wasm_registry_add("pdu_pdu_to_tagged_stream", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "byte") == "byte") {
            auto block = pdu::pdu_to_tagged_stream::make(gr::types::byte_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "complex") {
            auto block = pdu::pdu_to_tagged_stream::make(gr::types::complex_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "float") {
            auto block = pdu::pdu_to_tagged_stream::make(gr::types::float_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for pdu_pdu_to_tagged_stream");
    });
    wasm_registry_add("pdu_tagged_stream_to_pdu", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "byte") == "byte") {
            auto block = pdu::tagged_stream_to_pdu::make(gr::types::byte_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "complex") {
            auto block = pdu::tagged_stream_to_pdu::make(gr::types::complex_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "float") {
            auto block = pdu::tagged_stream_to_pdu::make(gr::types::float_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for pdu_tagged_stream_to_pdu");
    });
    }
} g_registrar_pdu;
} // namespace
