// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <paint/paint_bc.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_paint {
    Registrar_paint()
    {
    wasm_registry_add("paint_paint_bc", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "randomsrc", "INTERNAL") == "INTERNAL") {
            auto block = paint::paint_bc::make(wasm_registry::number<int>(p, "width", 1920), wasm_registry::number<int>(p, "repeats", 8), wasm_registry::choice(p, "equalization", {{"EQUALIZATION_OFF", paint::EQUALIZATION_OFF}, {"EQUALIZATION_ON", paint::EQUALIZATION_ON}}, paint::EQUALIZATION_OFF), paint::INTERNAL, 1);
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "randomsrc", "INTERNAL") == "EXTERNAL") {
            auto block = paint::paint_bc::make(wasm_registry::number<int>(p, "width", 1920), wasm_registry::number<int>(p, "repeats", 8), wasm_registry::choice(p, "equalization", {{"EQUALIZATION_OFF", paint::EQUALIZATION_OFF}, {"EQUALIZATION_ON", paint::EQUALIZATION_ON}}, paint::EQUALIZATION_OFF), paint::EXTERNAL, 2);
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for paint_paint_bc");
    });
    }
} g_registrar_paint;
} // namespace
