// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <lte/extract_subcarriers_vcvc.h>
#include <lte/pss_calculator_vcm.h>
#include <lte/pss_symbol_selector_cvc.h>
#include <lte/pss_tagger_cc.h>
#include <lte/rough_symbol_sync_cc.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_lte {
    Registrar_lte()
    {
    wasm_registry_add("lte_extract_subcarriers_vcvc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lte::extract_subcarriers_vcvc::make(wasm_registry::number<int>(p, "N_rb_dl", 0), wasm_registry::number<int>(p, "fftl", 0), "block");
        return { block, nullptr };
    });
    wasm_registry_add("lte_pss_calculator_vcm", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lte::pss_calculator_vcm::make(wasm_registry::number<int>(p, "fftl", 0), "block");
        return { block, nullptr };
    });
    wasm_registry_add("lte_pss_symbol_selector_cvc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lte::pss_symbol_selector_cvc::make(wasm_registry::number<int>(p, "fftl", 0), "block");
        return { block, nullptr };
    });
    wasm_registry_add("lte_pss_tagger_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lte::pss_tagger_cc::make(wasm_registry::number<int>(p, "fftl", 0), "block");
        return { block, nullptr };
    });
    wasm_registry_add("lte_rough_symbol_sync_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = lte::rough_symbol_sync_cc::make(wasm_registry::number<int>(p, "fftl", 0), wasm_registry::number<int>(p, "vlen", 0), "block");
        return { block, nullptr };
    });
    }
} g_registrar_lte;
} // namespace
