// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include "bbc_blocks.hpp"

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_bbc {
    Registrar_bbc()
    {
    wasm_registry_add("bbc_OOKDemodulator", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_bbc::make_ook_demodulator(wasm_registry::number<double>(p, "carrier_freq", 20000.0), wasm_registry::number<double>(p, "samp_rate", 128000.0), wasm_registry::number<double>(p, "symbol_rate", 500.0), wasm_registry::number<double>(p, "bandwidth", 0.0), wasm_registry::number<double>(p, "threshold", 0.25));
        return { block, nullptr };
    });
    wasm_registry_add("bbc_OOKModulator", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_bbc::make_ook_modulator(wasm_registry::number<double>(p, "carrier_freq", 20000.0), wasm_registry::number<double>(p, "samp_rate", 128000.0), wasm_registry::number<double>(p, "symbol_rate", 500.0));
        return { block, nullptr };
    });
    wasm_registry_add("bbc_bbc_decoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_bbc::make_decoder(wasm_registry::number<int>(p, "message_length", 128), wasm_registry::number<int>(p, "codeword_length", 131072), wasm_registry::number<int>(p, "checksum_length", 32), wasm_registry::number<int>(p, "max_candidates", 256), wasm_registry::number<int>(p, "max_steps", 5000000), wasm_registry::choice(p, "checksum_mode", {{"zeros", "zeros"}, {"sha256", "sha256"}}, "zeros"));
        return { block, nullptr };
    });
    wasm_registry_add("bbc_bbc_encoder", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = wasm_bbc::make_encoder(wasm_registry::number<int>(p, "message_length", 128), wasm_registry::number<int>(p, "codeword_length", 131072), wasm_registry::number<int>(p, "checksum_length", 32), wasm_registry::choice(p, "checksum_mode", {{"zeros", "zeros"}, {"sha256", "sha256"}}, "zeros"));
        return { block, nullptr };
    });
    }
} g_registrar_bbc;
} // namespace
