// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <gnuradio/pdu/add_system_time.h>
#include <gnuradio/pdu/pdu_filter.h>
#include <gnuradio/pdu/pdu_remove.h>
#include <gnuradio/pdu/pdu_set.h>
#include <gnuradio/pdu/pdu_split.h>
#include <gnuradio/pdu/pdu_to_stream.h>
#include <gnuradio/pdu/pdu_to_tagged_stream.h>
#include <gnuradio/pdu/random_pdu.h>
#include <gnuradio/pdu/tagged_stream_to_pdu.h>
#include <gnuradio/pdu/tags_to_pdu.h>
#include <gnuradio/pdu/take_skip_to_pdu.h>
#include <gnuradio/pdu/time_delta.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_pdu {
    Registrar_pdu()
    {
    wasm_registry_add("pdu_add_system_time", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = pdu::add_system_time::make(wasm_registry::pmt_value(p, "key", "pmt.intern(\"system_time\")"));
        return { block, nullptr };
    });
    wasm_registry_add("pdu_pdu_filter", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = pdu::pdu_filter::make(wasm_registry::pmt_value(p, "k", "pmt.intern(\"key\")"), wasm_registry::pmt_value(p, "v", "pmt.intern(\"value\")"), wasm_registry::boolean(p, "invert", false));
        BuiltBlock built{ block };
        built.numeric_setters["invert"] = [block](double value) { block->set_inversion(static_cast<bool>(value)); };
        return built;
    });
    wasm_registry_add("pdu_pdu_remove", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = pdu::pdu_remove::make(wasm_registry::pmt_value(p, "k", "pmt.intern(\"key\")"));
        return { block, nullptr };
    });
    wasm_registry_add("pdu_pdu_set", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = pdu::pdu_set::make(wasm_registry::pmt_value(p, "k", "pmt.intern(\"key\")"), wasm_registry::pmt_value(p, "v", "pmt.intern(\"value\")"));
        return { block, nullptr };
    });
    wasm_registry_add("pdu_pdu_split", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = pdu::pdu_split::make(wasm_registry::choice(p, "pass_empty", {{"False", false}, {"True", true}}, false));
        return { block, nullptr };
    });
    wasm_registry_add("pdu_pdu_to_stream_x", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "complex") == "complex") {
            auto block = pdu::pdu_to_stream_c::make(wasm_registry::choice(p, "early_behavior", {{"pdu::EARLY_BURST_APPEND", pdu::EARLY_BURST_APPEND}, {"pdu::EARLY_BURST_DROP", pdu::EARLY_BURST_DROP}, {"pdu::EARLY_BURST_BALK", pdu::EARLY_BURST_BALK}}, pdu::EARLY_BURST_APPEND), wasm_registry::number<int>(p, "depth", 64));
            BuiltBlock built{ block };
            built.numeric_setters["depth"] = [block](double value) { block->set_max_queue_size(static_cast<int>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "complex") == "float") {
            auto block = pdu::pdu_to_stream_f::make(wasm_registry::choice(p, "early_behavior", {{"pdu::EARLY_BURST_APPEND", pdu::EARLY_BURST_APPEND}, {"pdu::EARLY_BURST_DROP", pdu::EARLY_BURST_DROP}, {"pdu::EARLY_BURST_BALK", pdu::EARLY_BURST_BALK}}, pdu::EARLY_BURST_APPEND), wasm_registry::number<int>(p, "depth", 64));
            BuiltBlock built{ block };
            built.numeric_setters["depth"] = [block](double value) { block->set_max_queue_size(static_cast<int>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "complex") == "int") {
            auto block = pdu::pdu_to_stream_i::make(wasm_registry::choice(p, "early_behavior", {{"pdu::EARLY_BURST_APPEND", pdu::EARLY_BURST_APPEND}, {"pdu::EARLY_BURST_DROP", pdu::EARLY_BURST_DROP}, {"pdu::EARLY_BURST_BALK", pdu::EARLY_BURST_BALK}}, pdu::EARLY_BURST_APPEND), wasm_registry::number<int>(p, "depth", 64));
            BuiltBlock built{ block };
            built.numeric_setters["depth"] = [block](double value) { block->set_max_queue_size(static_cast<int>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "complex") == "short") {
            auto block = pdu::pdu_to_stream_s::make(wasm_registry::choice(p, "early_behavior", {{"pdu::EARLY_BURST_APPEND", pdu::EARLY_BURST_APPEND}, {"pdu::EARLY_BURST_DROP", pdu::EARLY_BURST_DROP}, {"pdu::EARLY_BURST_BALK", pdu::EARLY_BURST_BALK}}, pdu::EARLY_BURST_APPEND), wasm_registry::number<int>(p, "depth", 64));
            BuiltBlock built{ block };
            built.numeric_setters["depth"] = [block](double value) { block->set_max_queue_size(static_cast<int>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "complex") == "byte") {
            auto block = pdu::pdu_to_stream_b::make(wasm_registry::choice(p, "early_behavior", {{"pdu::EARLY_BURST_APPEND", pdu::EARLY_BURST_APPEND}, {"pdu::EARLY_BURST_DROP", pdu::EARLY_BURST_DROP}, {"pdu::EARLY_BURST_BALK", pdu::EARLY_BURST_BALK}}, pdu::EARLY_BURST_APPEND), wasm_registry::number<int>(p, "depth", 64));
            BuiltBlock built{ block };
            built.numeric_setters["depth"] = [block](double value) { block->set_max_queue_size(static_cast<int>(value)); };
            return built;
        }
        throw std::runtime_error("unsupported type selection for pdu_pdu_to_stream_x");
    });
    wasm_registry_add("pdu_pdu_to_tagged_stream", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "byte") == "byte") {
            auto block = pdu::pdu_to_tagged_stream::make(gr::types::byte_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "complex") {
            auto block = pdu::pdu_to_tagged_stream::make(gr::types::complex_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "float") {
            auto block = pdu::pdu_to_tagged_stream::make(gr::types::float_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for pdu_pdu_to_tagged_stream");
    });
    wasm_registry_add("pdu_random_pdu", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = pdu::random_pdu::make(wasm_registry::number<int>(p, "minsize", 50), wasm_registry::number<int>(p, "maxsize", 2000), wasm_registry::number<int>(p, "mask", 255), wasm_registry::number<int>(p, "length_modulo", 2));
        return { block, nullptr };
    });
    wasm_registry_add("pdu_tagged_stream_to_pdu", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "byte") == "byte") {
            auto block = pdu::tagged_stream_to_pdu::make(gr::types::byte_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "complex") {
            auto block = pdu::tagged_stream_to_pdu::make(gr::types::complex_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        else if (wasm_registry::text(p, "type", "byte") == "float") {
            auto block = pdu::tagged_stream_to_pdu::make(gr::types::float_t, wasm_registry::text(p, "tag", "packet_len"));
            return { block, nullptr };
        }
        throw std::runtime_error("unsupported type selection for pdu_tagged_stream_to_pdu");
    });
    wasm_registry_add("pdu_tags_to_pdu_x", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "c") == "c") {
            auto block = pdu::tags_to_pdu_c::make(pmt::intern(wasm_registry::text(p, "start_tag", "SOB")), pmt::intern(wasm_registry::text(p, "end_tag", "EOB")), wasm_registry::number<int>(p, "max_pdu_size", 1024), wasm_registry::number<double>(p, "rate", 0.0), wasm_registry::vector<gr_complex>(p, "prepend"), wasm_registry::choice(p, "pub_det", {{"True", true}, {"False", false}}, false), wasm_registry::number<int>(p, "tail_size", 0), wasm_registry::number<double>(p, "start_time", 0.0));
            block->set_eob_parameters(wasm_registry::number<int>(p, "eob_alignment", 1), wasm_registry::number<int>(p, "eob_offset", 0));
            block->enable_time_debug(wasm_registry::choice(p, "boost_time", {{"True", true}, {"False", false}}, false));
            BuiltBlock built{ block };
            struct LiveCallbackParams {
                int p_eob_alignment;
                int p_eob_offset;
            };
            auto live = std::make_shared<LiveCallbackParams>();
            live->p_eob_alignment = wasm_registry::number<int>(p, "eob_alignment", 1);
            live->p_eob_offset = wasm_registry::number<int>(p, "eob_offset", 0);
            auto apply_callback_0 = [block, live]() { block->set_eob_parameters(live->p_eob_alignment, live->p_eob_offset); };
            built.numeric_setters["max_pdu_size"] = [block](double value) { block->set_max_pdu_size(static_cast<int>(value)); };
            built.numeric_setters["rate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
            built.numeric_setters["tail_size"] = [block](double value) { block->set_tail_size(static_cast<int>(value)); };
            built.numeric_setters["start_time"] = [block](double value) { block->set_start_time(static_cast<double>(value)); };
            wasm_registry::add_numeric_setter(built, "eob_alignment", live, &LiveCallbackParams::p_eob_alignment, apply_callback_0);
            wasm_registry::add_numeric_setter(built, "eob_offset", live, &LiveCallbackParams::p_eob_offset, apply_callback_0);
            return built;
        }
        else if (wasm_registry::text(p, "type", "c") == "f") {
            auto block = pdu::tags_to_pdu_f::make(pmt::intern(wasm_registry::text(p, "start_tag", "SOB")), pmt::intern(wasm_registry::text(p, "end_tag", "EOB")), wasm_registry::number<int>(p, "max_pdu_size", 1024), wasm_registry::number<double>(p, "rate", 0.0), wasm_registry::vector<float>(p, "prepend"), wasm_registry::choice(p, "pub_det", {{"True", true}, {"False", false}}, false), wasm_registry::number<int>(p, "tail_size", 0), wasm_registry::number<double>(p, "start_time", 0.0));
            block->set_eob_parameters(wasm_registry::number<int>(p, "eob_alignment", 1), wasm_registry::number<int>(p, "eob_offset", 0));
            block->enable_time_debug(wasm_registry::choice(p, "boost_time", {{"True", true}, {"False", false}}, false));
            BuiltBlock built{ block };
            struct LiveCallbackParams {
                int p_eob_alignment;
                int p_eob_offset;
            };
            auto live = std::make_shared<LiveCallbackParams>();
            live->p_eob_alignment = wasm_registry::number<int>(p, "eob_alignment", 1);
            live->p_eob_offset = wasm_registry::number<int>(p, "eob_offset", 0);
            auto apply_callback_0 = [block, live]() { block->set_eob_parameters(live->p_eob_alignment, live->p_eob_offset); };
            built.numeric_setters["max_pdu_size"] = [block](double value) { block->set_max_pdu_size(static_cast<int>(value)); };
            built.numeric_setters["rate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
            built.numeric_setters["tail_size"] = [block](double value) { block->set_tail_size(static_cast<int>(value)); };
            built.numeric_setters["start_time"] = [block](double value) { block->set_start_time(static_cast<double>(value)); };
            wasm_registry::add_numeric_setter(built, "eob_alignment", live, &LiveCallbackParams::p_eob_alignment, apply_callback_0);
            wasm_registry::add_numeric_setter(built, "eob_offset", live, &LiveCallbackParams::p_eob_offset, apply_callback_0);
            return built;
        }
        else if (wasm_registry::text(p, "type", "c") == "i") {
            auto block = pdu::tags_to_pdu_i::make(pmt::intern(wasm_registry::text(p, "start_tag", "SOB")), pmt::intern(wasm_registry::text(p, "end_tag", "EOB")), wasm_registry::number<int>(p, "max_pdu_size", 1024), wasm_registry::number<double>(p, "rate", 0.0), wasm_registry::vector<std::int32_t>(p, "prepend"), wasm_registry::choice(p, "pub_det", {{"True", true}, {"False", false}}, false), wasm_registry::number<int>(p, "tail_size", 0), wasm_registry::number<double>(p, "start_time", 0.0));
            block->set_eob_parameters(wasm_registry::number<int>(p, "eob_alignment", 1), wasm_registry::number<int>(p, "eob_offset", 0));
            block->enable_time_debug(wasm_registry::choice(p, "boost_time", {{"True", true}, {"False", false}}, false));
            BuiltBlock built{ block };
            struct LiveCallbackParams {
                int p_eob_alignment;
                int p_eob_offset;
            };
            auto live = std::make_shared<LiveCallbackParams>();
            live->p_eob_alignment = wasm_registry::number<int>(p, "eob_alignment", 1);
            live->p_eob_offset = wasm_registry::number<int>(p, "eob_offset", 0);
            auto apply_callback_0 = [block, live]() { block->set_eob_parameters(live->p_eob_alignment, live->p_eob_offset); };
            built.numeric_setters["max_pdu_size"] = [block](double value) { block->set_max_pdu_size(static_cast<int>(value)); };
            built.numeric_setters["rate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
            built.numeric_setters["tail_size"] = [block](double value) { block->set_tail_size(static_cast<int>(value)); };
            built.numeric_setters["start_time"] = [block](double value) { block->set_start_time(static_cast<double>(value)); };
            wasm_registry::add_numeric_setter(built, "eob_alignment", live, &LiveCallbackParams::p_eob_alignment, apply_callback_0);
            wasm_registry::add_numeric_setter(built, "eob_offset", live, &LiveCallbackParams::p_eob_offset, apply_callback_0);
            return built;
        }
        else if (wasm_registry::text(p, "type", "c") == "s") {
            auto block = pdu::tags_to_pdu_s::make(pmt::intern(wasm_registry::text(p, "start_tag", "SOB")), pmt::intern(wasm_registry::text(p, "end_tag", "EOB")), wasm_registry::number<int>(p, "max_pdu_size", 1024), wasm_registry::number<double>(p, "rate", 0.0), wasm_registry::vector<std::int16_t>(p, "prepend"), wasm_registry::choice(p, "pub_det", {{"True", true}, {"False", false}}, false), wasm_registry::number<int>(p, "tail_size", 0), wasm_registry::number<double>(p, "start_time", 0.0));
            block->set_eob_parameters(wasm_registry::number<int>(p, "eob_alignment", 1), wasm_registry::number<int>(p, "eob_offset", 0));
            block->enable_time_debug(wasm_registry::choice(p, "boost_time", {{"True", true}, {"False", false}}, false));
            BuiltBlock built{ block };
            struct LiveCallbackParams {
                int p_eob_alignment;
                int p_eob_offset;
            };
            auto live = std::make_shared<LiveCallbackParams>();
            live->p_eob_alignment = wasm_registry::number<int>(p, "eob_alignment", 1);
            live->p_eob_offset = wasm_registry::number<int>(p, "eob_offset", 0);
            auto apply_callback_0 = [block, live]() { block->set_eob_parameters(live->p_eob_alignment, live->p_eob_offset); };
            built.numeric_setters["max_pdu_size"] = [block](double value) { block->set_max_pdu_size(static_cast<int>(value)); };
            built.numeric_setters["rate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
            built.numeric_setters["tail_size"] = [block](double value) { block->set_tail_size(static_cast<int>(value)); };
            built.numeric_setters["start_time"] = [block](double value) { block->set_start_time(static_cast<double>(value)); };
            wasm_registry::add_numeric_setter(built, "eob_alignment", live, &LiveCallbackParams::p_eob_alignment, apply_callback_0);
            wasm_registry::add_numeric_setter(built, "eob_offset", live, &LiveCallbackParams::p_eob_offset, apply_callback_0);
            return built;
        }
        else if (wasm_registry::text(p, "type", "c") == "b") {
            auto block = pdu::tags_to_pdu_b::make(pmt::intern(wasm_registry::text(p, "start_tag", "SOB")), pmt::intern(wasm_registry::text(p, "end_tag", "EOB")), wasm_registry::number<int>(p, "max_pdu_size", 1024), wasm_registry::number<double>(p, "rate", 0.0), wasm_registry::vector<std::uint8_t>(p, "prepend"), wasm_registry::choice(p, "pub_det", {{"True", true}, {"False", false}}, false), wasm_registry::number<int>(p, "tail_size", 0), wasm_registry::number<double>(p, "start_time", 0.0));
            block->set_eob_parameters(wasm_registry::number<int>(p, "eob_alignment", 1), wasm_registry::number<int>(p, "eob_offset", 0));
            block->enable_time_debug(wasm_registry::choice(p, "boost_time", {{"True", true}, {"False", false}}, false));
            BuiltBlock built{ block };
            struct LiveCallbackParams {
                int p_eob_alignment;
                int p_eob_offset;
            };
            auto live = std::make_shared<LiveCallbackParams>();
            live->p_eob_alignment = wasm_registry::number<int>(p, "eob_alignment", 1);
            live->p_eob_offset = wasm_registry::number<int>(p, "eob_offset", 0);
            auto apply_callback_0 = [block, live]() { block->set_eob_parameters(live->p_eob_alignment, live->p_eob_offset); };
            built.numeric_setters["max_pdu_size"] = [block](double value) { block->set_max_pdu_size(static_cast<int>(value)); };
            built.numeric_setters["rate"] = [block](double value) { block->set_samp_rate(static_cast<double>(value)); };
            built.numeric_setters["tail_size"] = [block](double value) { block->set_tail_size(static_cast<int>(value)); };
            built.numeric_setters["start_time"] = [block](double value) { block->set_start_time(static_cast<double>(value)); };
            wasm_registry::add_numeric_setter(built, "eob_alignment", live, &LiveCallbackParams::p_eob_alignment, apply_callback_0);
            wasm_registry::add_numeric_setter(built, "eob_offset", live, &LiveCallbackParams::p_eob_offset, apply_callback_0);
            return built;
        }
        throw std::runtime_error("unsupported type selection for pdu_tags_to_pdu_x");
    });
    wasm_registry_add("pdu_take_skip_to_pdu", +[](const nlohmann::json& p) -> BuiltBlock {
        if (wasm_registry::text(p, "type", "complex") == "complex") {
            auto block = pdu::take_skip_to_pdu_c::make(wasm_registry::number<int>(p, "take", 1024), wasm_registry::number<int>(p, "skip", 4096));
            BuiltBlock built{ block };
            built.numeric_setters["take"] = [block](double value) { block->set_take(static_cast<int>(value)); };
            built.numeric_setters["skip"] = [block](double value) { block->set_skip(static_cast<int>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "complex") == "float") {
            auto block = pdu::take_skip_to_pdu_f::make(wasm_registry::number<int>(p, "take", 1024), wasm_registry::number<int>(p, "skip", 4096));
            BuiltBlock built{ block };
            built.numeric_setters["take"] = [block](double value) { block->set_take(static_cast<int>(value)); };
            built.numeric_setters["skip"] = [block](double value) { block->set_skip(static_cast<int>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "complex") == "int") {
            auto block = pdu::take_skip_to_pdu_i::make(wasm_registry::number<int>(p, "take", 1024), wasm_registry::number<int>(p, "skip", 4096));
            BuiltBlock built{ block };
            built.numeric_setters["take"] = [block](double value) { block->set_take(static_cast<int>(value)); };
            built.numeric_setters["skip"] = [block](double value) { block->set_skip(static_cast<int>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "complex") == "short") {
            auto block = pdu::take_skip_to_pdu_s::make(wasm_registry::number<int>(p, "take", 1024), wasm_registry::number<int>(p, "skip", 4096));
            BuiltBlock built{ block };
            built.numeric_setters["take"] = [block](double value) { block->set_take(static_cast<int>(value)); };
            built.numeric_setters["skip"] = [block](double value) { block->set_skip(static_cast<int>(value)); };
            return built;
        }
        else if (wasm_registry::text(p, "type", "complex") == "byte") {
            auto block = pdu::take_skip_to_pdu_b::make(wasm_registry::number<int>(p, "take", 1024), wasm_registry::number<int>(p, "skip", 4096));
            BuiltBlock built{ block };
            built.numeric_setters["take"] = [block](double value) { block->set_take(static_cast<int>(value)); };
            built.numeric_setters["skip"] = [block](double value) { block->set_skip(static_cast<int>(value)); };
            return built;
        }
        throw std::runtime_error("unsupported type selection for pdu_take_skip_to_pdu");
    });
    wasm_registry_add("pdu_time_delta", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = pdu::time_delta::make(wasm_registry::pmt_value(p, "delta_key", "pmt.intern(\"time_delta_ms\")"), wasm_registry::pmt_value(p, "time_key", "pmt.intern(\"system_time\")"));
        return { block, nullptr };
    });
    }
} g_registrar_pdu;
} // namespace
