// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <gnuradio/fosphor/overlap_cc.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_fosphor {
    Registrar_fosphor()
    {
    wasm_registry_add("overlap_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = gr::fosphor::overlap_cc::make(wasm_registry::number<int>(p, "wlen", 1024), wasm_registry::number<int>(p, "overlap", 1));
        return { block, nullptr };
    });
    }
} g_registrar_fosphor;
} // namespace
