// Generated by gen_registry.py; do not edit.
#include "registry_helpers.hpp"
#include <radar/crop_matrix_vcvc.h>
#include <radar/estimator_cw.h>
#include <radar/estimator_fmcw.h>
#include <radar/estimator_fsk.h>
#include <radar/estimator_ofdm.h>
#include <radar/estimator_rcs.h>
#include <radar/estimator_sync_pulse_c.h>
#include <radar/find_max_peak_c.h>
#include <radar/msg_gate.h>
#include <radar/msg_manipulator.h>
#include <radar/ofdm_cyclic_prefix_remover_cvc.h>
#include <radar/ofdm_divide_vcvc.h>
#include <radar/os_cfar_2d_vc.h>
#include <radar/os_cfar_c.h>
#include <radar/print_results.h>
#include <radar/signal_generator_cw_c.h>
#include <radar/signal_generator_fmcw_c.h>
#include <radar/signal_generator_fsk_c.h>
#include <radar/signal_generator_sync_pulse_c.h>
#include <radar/split_cc.h>
#include <radar/split_fsk_cc.h>
#include <radar/static_target_simulator_cc.h>
#include <radar/tracking_singletarget.h>
#include <radar/transpose_matrix_vcvc.h>
#include <radar/ts_fft_cc.h>

using namespace gr;

// Provided by the main module (registry.cpp).
extern "C" void wasm_registry_add(const char* id,
                                  BuiltBlock (*factory)(const nlohmann::json&));

namespace {
struct Registrar_radar {
    Registrar_radar()
    {
    wasm_registry_add("radar_crop_matrix_vcvc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::crop_matrix_vcvc::make(wasm_registry::number<int>(p, "vlen", 0), wasm_registry::vector<int>(p, "crop_x"), wasm_registry::vector<int>(p, "crop_y"), wasm_registry::text(p, "len_key", "packet_len"));
        return { block, nullptr };
    });
    wasm_registry_add("radar_estimator_cw", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::estimator_cw::make(wasm_registry::number<double>(p, "center_freq", 0.0));
        return { block, nullptr };
    });
    wasm_registry_add("radar_estimator_fmcw", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::estimator_fmcw::make(wasm_registry::number<int>(p, "samp_rate", 0), wasm_registry::number<double>(p, "center_freq", 0.0), wasm_registry::number<double>(p, "sweep_freq", 0.0), wasm_registry::number<int>(p, "samp_up", 0), wasm_registry::number<int>(p, "samp_down", 0), wasm_registry::boolean(p, "push_power", false));
        return { block, nullptr };
    });
    wasm_registry_add("radar_estimator_fsk", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::estimator_fsk::make(wasm_registry::number<double>(p, "center_freq", 0.0), wasm_registry::number<double>(p, "delta_freq", 0.0), wasm_registry::boolean(p, "push_power", false));
        return { block, nullptr };
    });
    wasm_registry_add("radar_estimator_ofdm", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::estimator_ofdm::make(wasm_registry::text(p, "symbol_x", ""), wasm_registry::number<int>(p, "len_x", 0), wasm_registry::vector<float>(p, "axis_x"), wasm_registry::text(p, "symbol_y", ""), wasm_registry::number<int>(p, "len_y", 0), wasm_registry::vector<float>(p, "axis_y"), wasm_registry::boolean(p, "merge_consecutive", true));
        return { block, nullptr };
    });
    wasm_registry_add("radar_estimator_rcs", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::estimator_rcs::make(wasm_registry::number<int>(p, "num_mean", 0), wasm_registry::number<double>(p, "center_freq", 0.0), wasm_registry::number<double>(p, "antenna_gain_tx", 0.0), wasm_registry::number<double>(p, "antenna_gain_rx", 0.0), wasm_registry::number<double>(p, "usrp_gain_rx", 0.0), wasm_registry::number<double>(p, "power_tx", 0.0), wasm_registry::number<double>(p, "corr_factor", 0.0), wasm_registry::number<double>(p, "exponent", 1.0));
        BuiltBlock built{ block };
        built.numeric_setters["num_mean"] = [block](double value) { block->set_num_mean(static_cast<int>(value)); };
        built.numeric_setters["center_freq"] = [block](double value) { block->set_center_freq(static_cast<double>(value)); };
        built.numeric_setters["antenna_gain_tx"] = [block](double value) { block->set_antenna_gain_tx(static_cast<double>(value)); };
        built.numeric_setters["antenna_gain_rx"] = [block](double value) { block->set_antenna_gain_rx(static_cast<double>(value)); };
        built.numeric_setters["usrp_gain_rx"] = [block](double value) { block->set_usrp_gain_rx(static_cast<double>(value)); };
        built.numeric_setters["power_tx"] = [block](double value) { block->set_power_tx(static_cast<double>(value)); };
        built.numeric_setters["corr_factor"] = [block](double value) { block->set_corr_factor(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("radar_estimator_sync_pulse_c", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::estimator_sync_pulse_c::make(wasm_registry::number<int>(p, "num_xcorr", 0), wasm_registry::text(p, "len_key", "packet_len"));
        BuiltBlock built{ block };
        built.numeric_setters["num_xcorr"] = [block](double value) { block->set_num_xcorr(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("radar_find_max_peak_c", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::find_max_peak_c::make(wasm_registry::number<int>(p, "samp_rate", 0), wasm_registry::number<double>(p, "threshold", 0.0), wasm_registry::number<int>(p, "samp_protect", 0), wasm_registry::vector<float>(p, "max_freq"), wasm_registry::boolean(p, "cut_max_freq", false), wasm_registry::text(p, "len_key", "packet_len"));
        BuiltBlock built{ block };
        built.numeric_setters["threshold"] = [block](double value) { block->set_threshold(static_cast<double>(value)); };
        built.numeric_setters["samp_protect"] = [block](double value) { block->set_samp_protect(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("radar_msg_gate", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::msg_gate::make(wasm_registry::string_vector(p, "msg_keys"), wasm_registry::vector<float>(p, "val_min"), wasm_registry::vector<float>(p, "val_max"));
        return { block, nullptr };
    });
    wasm_registry_add("radar_msg_manipulator", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::msg_manipulator::make(wasm_registry::string_vector(p, "symbols"), wasm_registry::vector<float>(p, "const_add"), wasm_registry::vector<float>(p, "const_mult"));
        return { block, nullptr };
    });
    wasm_registry_add("radar_ofdm_cyclic_prefix_remover_cvc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::ofdm_cyclic_prefix_remover_cvc::make(wasm_registry::number<int>(p, "fft_len", 0), wasm_registry::number<int>(p, "cp_len", 0), wasm_registry::text(p, "len_key", "packet_len"));
        return { block, nullptr };
    });
    wasm_registry_add("radar_ofdm_divide_vcvc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::ofdm_divide_vcvc::make(wasm_registry::number<int>(p, "vlen_in", 0), wasm_registry::number<int>(p, "vlen_out", 0), wasm_registry::vector<int>(p, "discarded_carriers"), wasm_registry::number<int>(p, "num_sync_words", 0), wasm_registry::text(p, "len_key", "packet_len"));
        return { block, nullptr };
    });
    wasm_registry_add("radar_os_cfar_2d_vc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::os_cfar_2d_vc::make(wasm_registry::number<int>(p, "vlen", 0), wasm_registry::vector<int>(p, "samp_compare"), wasm_registry::vector<int>(p, "samp_protect"), wasm_registry::number<double>(p, "rel_threshold", 0.0), wasm_registry::number<double>(p, "mult_threshold", 0.0), wasm_registry::text(p, "len_key", "packet_len"));
        BuiltBlock built{ block };
        built.numeric_setters["rel_threshold"] = [block](double value) { block->set_rel_threshold(static_cast<double>(value)); };
        built.numeric_setters["mult_threshold"] = [block](double value) { block->set_mult_threshold(static_cast<double>(value)); };
        return built;
    });
    wasm_registry_add("radar_os_cfar_c", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::os_cfar_c::make(wasm_registry::number<int>(p, "samp_rate", 0), wasm_registry::number<int>(p, "samp_compare", 0), wasm_registry::number<int>(p, "samp_protect", 0), wasm_registry::number<double>(p, "rel_threshold", 0.0), wasm_registry::number<double>(p, "mult_threshold", 0.0), wasm_registry::boolean(p, "merge_consecutive", true), wasm_registry::text(p, "len_key", "packet_len"));
        BuiltBlock built{ block };
        built.numeric_setters["rel_threshold"] = [block](double value) { block->set_rel_threshold(static_cast<double>(value)); };
        built.numeric_setters["mult_threshold"] = [block](double value) { block->set_mult_threshold(static_cast<double>(value)); };
        built.numeric_setters["samp_compare"] = [block](double value) { block->set_samp_compare(static_cast<int>(value)); };
        built.numeric_setters["samp_protect"] = [block](double value) { block->set_samp_protect(static_cast<int>(value)); };
        return built;
    });
    wasm_registry_add("radar_print_results", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::print_results::make(wasm_registry::boolean(p, "store_msg", false), wasm_registry::text(p, "filename", ""));
        return { block, nullptr };
    });
    wasm_registry_add("radar_signal_generator_cw_c", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::signal_generator_cw_c::make(wasm_registry::number<int>(p, "packet_len", 0), wasm_registry::number<int>(p, "samp_rate", 0), wasm_registry::vector<float>(p, "frequency"), wasm_registry::number<double>(p, "amplitude", 0.0), wasm_registry::text(p, "len_key", "packet_len"));
        return { block, nullptr };
    });
    wasm_registry_add("radar_signal_generator_fmcw_c", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::signal_generator_fmcw_c::make(wasm_registry::number<int>(p, "samp_rate", 0), wasm_registry::number<int>(p, "samp_up", 0), wasm_registry::number<int>(p, "samp_down", 0), wasm_registry::number<int>(p, "samp_cw", 0), wasm_registry::number<double>(p, "freq_cw", 0.0), wasm_registry::number<double>(p, "freq_sweep", 0.0), wasm_registry::number<double>(p, "amplitude", 0.0), wasm_registry::text(p, "len_key", "packet_len"));
        return { block, nullptr };
    });
    wasm_registry_add("radar_signal_generator_fsk_c", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::signal_generator_fsk_c::make(wasm_registry::number<int>(p, "samp_rate", 0), wasm_registry::number<int>(p, "samp_per_freq", 0), wasm_registry::number<int>(p, "blocks_per_tag", 0), wasm_registry::number<double>(p, "freq_low", 0.0), wasm_registry::number<double>(p, "freq_high", 0.0), wasm_registry::number<double>(p, "amplitude", 0.0), wasm_registry::text(p, "len_key", "packet_len"));
        return { block, nullptr };
    });
    wasm_registry_add("radar_signal_generator_sync_pulse_c", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::signal_generator_sync_pulse_c::make(wasm_registry::number<int>(p, "packet_len", 0), wasm_registry::vector<int>(p, "pulse_len"), wasm_registry::vector<int>(p, "pulse_pause"), wasm_registry::number<double>(p, "pulse_amplitude", 0.0), wasm_registry::text(p, "len_key", "packet_len"));
        return { block, nullptr };
    });
    wasm_registry_add("radar_split_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::split_cc::make(wasm_registry::number<int>(p, "packet_num", 0), wasm_registry::vector<int>(p, "packet_parts"), wasm_registry::text(p, "len_key", "packet_len"));
        return { block, nullptr };
    });
    wasm_registry_add("radar_split_fsk_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::split_fsk_cc::make(wasm_registry::number<int>(p, "samp_per_freq", 0), wasm_registry::number<int>(p, "samp_discard", 0), wasm_registry::text(p, "len_key", "packet_len"));
        return { block, nullptr };
    });
    wasm_registry_add("radar_static_target_simulator_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::static_target_simulator_cc::make(wasm_registry::vector<float>(p, "range"), wasm_registry::vector<float>(p, "velocity"), wasm_registry::vector<float>(p, "rcs"), wasm_registry::vector<float>(p, "azimuth"), wasm_registry::vector<float>(p, "position_rx"), wasm_registry::number<int>(p, "samp_rate", 0), wasm_registry::number<double>(p, "center_freq", 0.0), wasm_registry::number<double>(p, "self_coupling_db", 0.0), wasm_registry::boolean(p, "rndm_phaseshift", true), wasm_registry::boolean(p, "self_coupling", true), wasm_registry::text(p, "len_key", "packet_len"));
        BuiltBlock built{ block };
        struct LiveCallbackParams {
            std::vector<float> p_range;
            std::vector<float> p_velocity;
            std::vector<float> p_rcs;
            std::vector<float> p_azimuth;
            std::vector<float> p_position_rx;
            int p_samp_rate;
            double p_center_freq;
            double p_self_coupling_db;
            bool p_rndm_phaseshift;
            bool p_self_coupling;
        };
        auto live = std::make_shared<LiveCallbackParams>();
        live->p_range = wasm_registry::vector<float>(p, "range");
        live->p_velocity = wasm_registry::vector<float>(p, "velocity");
        live->p_rcs = wasm_registry::vector<float>(p, "rcs");
        live->p_azimuth = wasm_registry::vector<float>(p, "azimuth");
        live->p_position_rx = wasm_registry::vector<float>(p, "position_rx");
        live->p_samp_rate = wasm_registry::number<int>(p, "samp_rate", 0);
        live->p_center_freq = wasm_registry::number<double>(p, "center_freq", 0.0);
        live->p_self_coupling_db = wasm_registry::number<double>(p, "self_coupling_db", 0.0);
        live->p_rndm_phaseshift = wasm_registry::boolean(p, "rndm_phaseshift", true);
        live->p_self_coupling = wasm_registry::boolean(p, "self_coupling", true);
        auto apply_callback_0 = [block, live]() { block->setup_targets(live->p_range, live->p_velocity, live->p_rcs, live->p_azimuth, live->p_position_rx, live->p_samp_rate, live->p_center_freq, live->p_self_coupling_db, live->p_rndm_phaseshift, live->p_self_coupling); };
        wasm_registry::add_numeric_setter(built, "range", live, &LiveCallbackParams::p_range, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "velocity", live, &LiveCallbackParams::p_velocity, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "rcs", live, &LiveCallbackParams::p_rcs, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "azimuth", live, &LiveCallbackParams::p_azimuth, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "position_rx", live, &LiveCallbackParams::p_position_rx, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "samp_rate", live, &LiveCallbackParams::p_samp_rate, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "center_freq", live, &LiveCallbackParams::p_center_freq, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "self_coupling_db", live, &LiveCallbackParams::p_self_coupling_db, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "rndm_phaseshift", live, &LiveCallbackParams::p_rndm_phaseshift, apply_callback_0);
        wasm_registry::add_numeric_setter(built, "self_coupling", live, &LiveCallbackParams::p_self_coupling, apply_callback_0);
        return built;
    });
    wasm_registry_add("radar_tracking_singletarget", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::tracking_singletarget::make(wasm_registry::number<int>(p, "num_particle", 0), wasm_registry::number<double>(p, "std_range_meas", 0.0), wasm_registry::number<double>(p, "std_velocity_meas", 0.0), wasm_registry::number<double>(p, "std_accel_sys", 0.0), wasm_registry::number<double>(p, "threshold_track", 0.0), wasm_registry::number<int>(p, "threshold_lost", 0), wasm_registry::text(p, "filter", "kalman"));
        return { block, nullptr };
    });
    wasm_registry_add("radar_transpose_matrix_vcvc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::transpose_matrix_vcvc::make(wasm_registry::number<int>(p, "vlen_in", 0), wasm_registry::number<int>(p, "vlen_out", 0), wasm_registry::text(p, "len_key", "packet_len"));
        return { block, nullptr };
    });
    wasm_registry_add("radar_ts_fft_cc", +[](const nlohmann::json& p) -> BuiltBlock {
        auto block = radar::ts_fft_cc::make(wasm_registry::number<int>(p, "packet_len", 0), wasm_registry::text(p, "len_key", "packet_len"));
        return { block, nullptr };
    });
    }
} g_registrar_radar;
} // namespace
